### ISSUE TITLE
Issues with the Build System section of the Getting Started document

### ISSUE THREAD

**Issue by flatcap-monty** [elementary/website#1014]
Point 2: Folder created is called `cmake-modules`. It should be made clearer that this needs to be renamed and copied into the `hello-again` folder.
Point 3: With the CMakeLists.txt file used as-is, the application will not build, and the `cmake -DCMAKE_INSTALL_PREFIX=/usr ../ ` command from the next section will not run.  
Change line 8 to `list (APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/src)`

**Comment by flatcap-monty** [comment]
Additionally, the instructions should include to remove the `.bzr` folder from the `/cmake` directory, otherwise the directory cannot be added to the repository

**Comment by tkegan** [comment]
Was having the same issue, came up with a different fix. I copied the files in cmake-modules/src to a ~/Projects/${PROJECT_NAME}/cmake to work around the bzr issue.

**Comment by fabianthoma** [comment]
This section needs to be updated as we now ship these cmake options as a development dependency which makes them update in all applications automatically instead of pulling them manually from version control. This needs input from our desktop developers.

**Comment by tkegan** [comment]
Is there a better forum for questions on the Getting Started/Developer documentation? I'm having a hard time with the localization stuff too. I think the documentation is out sync there too.

**Comment by tintou** [comment]
The website isn't that outdated, you have two options:
 * move cmake-module into the cmake folder of your project, then nothing has changed.
 * use the cmake-elementary package (that is available starting from Loki)

**Comment by benwaffle** [comment]
If you're on arch, use the `cmake-elementary-bzr` package in the AUR

**Comment by danrabbit** [comment]
This is being addressed in #1157
