### ISSUE TITLE
Bug Reporting Guide mentions IRC channel

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1051]
https://elementary.io/docs/code/reference#you-can-get-a-bit-of-help

Our IRC channel isn't actively monitored anymore, meaning we're sending contributors to a dead end.

**Comment by btkostner** [comment]
I would say our biggest population is on Google+ or Stackoverflow. Which one should we direct to?

**Comment by lewisgoddard** [comment]
StackExchange, that's the official channel for help. Google+ is for discussion.

**Comment by danrabbit** [comment]
I am very -1 on sending people to StackExchange who are trying to report issues. Bug reports are strictly off topic there.

**Comment by lewisgoddard** [comment]
I'm not sure they would mostly be bug reports, it's a code reference. It would mostly be developers saying "How do I do _cool thing_ in Vala on elementary OS?"

**Comment by danrabbit** [comment]
This about getting help _with filing bug reports_, not with programming.

**Comment by lewisgoddard** [comment]
We're trying to replace this line, right? That looks targeted to developers, not end users. Indeed, the same page lists code styles and proposing changes.

> If you're not sure about anything above, you are always welcome to our development IRC channel: #elementary-dev on irc.freenode.net.

**Comment by danrabbit** [comment]
Yes, the act of bug reporting is not targeted to end users. The bug reporting guide is part of the developer reference. The title of this report is "Bug Reporting Guide mentions IRC channel" the link goes to the bug reporting guide. It's about reporting bugs -_-

**Comment by lewisgoddard** [comment]
This is kind of a #968 thing, no?

**Comment by danrabbit** [comment]
FWIW, #elementary-dev is still bridged to Slack
