### ISSUE TITLE
Change U+0027 ' to U+2019 ’

### ISSUE THREAD

**Issue by ArchangeGabriel** [elementary/website#1165]
I’m a kind of typonazi, and it hurts my eyes every time I see a U+0027 ' instead of U+2019 ’ in texts. Especially when everything else is so carefully designed like in the case of elementary.

I’m going to fix that in the french translation, but it would be nice if it was fixed in the default english website too. ;)

I can make a pull request for this if you want, but I’m not sure in which files I should look for those. Plus, it means people should take care when adding new strings. ;)

**Comment by lewisgoddard** [comment]
I disagree with this, this is a font-selection issue if you believe that it is not displayed accurately.

[U+0027](http://unicode.org/cldr/utility/character.jsp?a=0027) - Unicode Character 'APOSTROPHE'
[U+2019](http://unicode.org/cldr/utility/character.jsp?a=2019) - Unicode Character 'RIGHT SINGLE QUOTATION MARK'

**Comment by danrabbit** [comment]
@ArchangeGabriel can you give an example of where this is being used incorrectly? As Lewis stated, these are different characters.

**Comment by ArchangeGabriel** [comment]
That’s their Unicode names, sure, but a typographic apostrophe isn’t that U+0027 ' thing. Read the two first lines there:

https://en.wikipedia.org/wiki/Apostrophe#Unicode

That’s a mistake almost everyone makes, for several reasons. There is much more documentation available on the subject if you want.

**Comment by danrabbit** [comment]
@ArchangeGabriel Okay, but can you give an example on the website where the wrong character is being used?

**Comment by ArchangeGabriel** [comment]
Just everywhere. The right one isn’t being used at all AFAICS. If you really need one example, look at the bottom of the home page for this: “We don't make advertising deals and we don't collect sensitive personal data.”. Both instances of “don't” whereas it should be “don’t” (or even “do not”, but that’s another debate).

**Comment by ArchangeGabriel** [comment]
On a side note, I’m already amazed that you correctly make uses of “ and ” instead of " and the same " for quotes. Unless that’s something done automatically, in which case you should consider doing the same for ’ instead of '. ;)

**Comment by danrabbit** [comment]
Thanks for providing an example! For reference:
![screenshot from 2016-06-01 08 44 11](https://cloud.githubusercontent.com/assets/7277719/15715875/1478bed4-27d5-11e6-9a77-d0ea905040eb.png)

The top is U+0027 and the bottom is U+2019

**Comment by ArchangeGabriel** [comment]
That’s the opposite actually (unless you use a weird font…).

**Comment by danrabbit** [comment]
Oops sorry, corrected. I typed that in backwards haha.

At least to my eye, U+2019 is very acute and kind of invades the space of the following characters. I'm not terribly keen on changing it. But I'm not particularly opposed either.

**Comment by snwh** [comment]
I don't think U+2019 is correct for contractions (like the don't example) it is the right-hand quotation mark and not an apostrophe.

**Comment by ArchangeGabriel** [comment]
@danrabbit Actually, that behaviour depends a lot on the fonts used. I don’t know in which fonts you see my posts here for instance, but for me U+2019 is much more vertical.

@snwh Please read the above wikipedia link. BTW, the “Computing” section of this article (right below the Unicode one I pointed at) expands a bit more this debate.

U+2019 is definitively the right character for anything in a text that is an apostrophe, I suggest that you try that in your favourite office writer, most of them do auto-replace those. And if you know about LaTeX, this last one does too, and when talking of typography, it’s quite a reference. ;)

The only right use of ' I’m aware of is in source code. Or in environment where you can’t go beyond ASCII (and BTW, note that some ASCII fonts have thus replaced U+0027 for U+2019), but those should not exists anymore today, and we’re not in a such case here.

It’s in the same range of common computing typographic mistakes as “...” vs “…”.

And finally, if you want to talk about contractions, I think that the convention is one should not use them for writing, but not being an english native nor expert, I might be wrong on this one. But that’s not something I enforce myself anywhere in fact, as you can see by my posts here at least.

**Comment by danrabbit** [comment]
@ArchangeGabriel well of course here the only context that matters is the fonts that we're using on the website :p So I don't think "it depends on the font" is a valid argument. We already know the font.

**Comment by ArchangeGabriel** [comment]
@danrabbit Oh, didn’t recognized it, it looks much better here, but that’s probably HiDPI at play. ;)

**Comment by ArchangeGabriel** [comment]
I agree that this font doesn’t have the best rendering of U+2019 I’ve seen for sure (just tested it too on the same example). But I’m still in favour of this change for what matters. That’s said, if your guys don’t want, that’s no big deal, it’s your website after all, not mine. So I’ll wait for your opinions here before going any further on the french translation. ;)

**Comment by danrabbit** [comment]
I'm indifferent, I'll leave it up to @snwh :)

**Comment by snwh** [comment]
The use of a typographic apostrophe is fine by me

**Comment by cassidyjames** [comment]
Right-hand single quote (rsquo, U+2019, `’`) is typographically more correct for English contractions than the straight up-and-down apostrophe (U+0027, `'`). Most CMSes and word processors transparently replace the apostrophe character with the rsquo, and when typesetting for the web it's common to use the rsquo.

The names are dumb basically because typewriters. xD

**Comment by lewisgoddard** [comment]
Examples:

### We won't do that.
### Why won’t we do that?

**Comment by lewisgoddard** [comment]
I just realised, this is going to break so many translations. Held until after Loki.

**Comment by ArchangeGabriel** [comment]
https://github.com/elementary/website/issues/1445 is in the same vein. Both should be handled at the same time I think.

Best thing would be to have a way to keep string correspondences in Transifex. Another option could be to stay with current strings and add a dummy “english” translation that would switch for correct apostrophe and quotes, but not sure if that’s possible/desirable.

**Comment by cassidyjames** [comment]
Honestly, since this is such a huge grab-bag issue I’m inclined to close it. Any new or updates strings should use typographic apostrophes (as we’ve started doing elsewhere), but I don’t think one big massive change is really appropriate or realistic.

**Comment by ArchangeGabriel** [comment]
@cassidyjames OK, fine. They are bigger issues than this anyway. ;)

**Comment by ValZapod** [comment]
This is just a bug in Microsoft 365 (Word). Wikipedia and github and android use 0x27. UTF-8 or UTF-16 /UTF-32 are also very very buggy still even in 2021.

**Comment by ArchangeGabriel** [comment]
This is not a bug, it is a feature. The Apple thread does say you should disable it for login. And elementary website has nothing to do with logins. Regarding Wikipedia, this is highly debated, at least in the French one. If I had time for this, I would fight for making ’ the correct one there, but my time is better employed doing other things.
