### ISSUE TITLE
"Reference for Granite" link doesn't take the user to the Granite reference

### ISSUE THREAD

**Issue by aldoiljazi** [elementary/website#1227]
**Reference for Granite** link in the **[Developer](https://elementary.io/developer)** page doesn't take the user to the Granite reference.

[Video](https://my.mixtape.moe/wdciyv.webm)

**Comment by btkostner** [comment]
https://github.com/flobrosch/valadoc-org/pull/65

**Comment by danrabbit** [comment]
Works now :)
