### ISSUE TITLE
Center modals with flex

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1255]
because that's easy and reliable and doesn't cause weird half-pixel blurring issues like transform does. As easy as:

```
.Aligner {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

**Comment by lewisgoddard** [comment]
See upstream: eustasy/jquery.leanmodal2#7

**Comment by p-shannon** [comment]
Still relevant?

**Comment by lewisgoddard** [comment]
@p-shannon It is.

**Comment by p-shannon** [comment]
Okay, so I'm extremely confused as to how to resolve this.

I found the offending code on the live site:
![inline-modal live](https://user-images.githubusercontent.com/31411889/36108176-2db21d56-0fea-11e8-9744-3d2d005e41bc.png)

The code is written on the element inline. However such code isn't reflected on the dev version of the site:
![inline-modal dev-site](https://user-images.githubusercontent.com/31411889/36108241-5d8b2ec8-0fea-11e8-872a-354b0488621f.png)

and finally, the seemingly relevent code block on index.php:
![inline-modal code](https://user-images.githubusercontent.com/31411889/36108289-7a0472d0-0fea-11e8-9f52-3e0493bf3b06.png)

Is it a script causing this behavior?

**Comment by p-shannon** [comment]
Okay I'm 100% certain that there's a possibility that I may have found [the relevant code](https://github.com/eustasy/jQuery.leanModal2/blob/master/jQuery.leanModal2.js#L101) kinda. Now as per the issue's suggestion, we'd have to go to the parent element, make that into flexbox, and give it the justify and align rules. I'll keep tinkering with it so I may create a solution, but just a forewarning, I have no idea how to test the modals on the dev build.
