### ISSUE TITLE
low contrast: white font on white picture

### ISSUE THREAD

**Issue by davidak** [elementary/website#1257]
### Expected behavior

readable text (high contrast)

### Actual behavior

not readable text (low contrast)

![bildschirmfoto 2016-08-18 um 19 29 08](https://cloud.githubusercontent.com/assets/91113/17783912/91e3b5b2-657a-11e6-96e9-5a9e53c951f3.png)

### Steps to reproduce the behavior

https://elementary.io/de/

**Comment by danrabbit** [comment]
This is being addressed in #1157
