### ISSUE TITLE
Make a more attractive empty cart page

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1267]
There's an opportunity to do something fun and attractive here. Couple examples I like:

https://dribbble.com/shots/2719091-Empty-Cart-Swish

https://dribbble.com/shots/2691265-Empty-Cart

Some nice image, a big call-to-action button, etc

**Comment by lewisgoddard** [comment]
If someone can get me an image or some copy I can get this done. I get the idea of what we want, but I'm not sure if we want a custom image to go here.
