### ISSUE TITLE
Organise folders and files and document their usage.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1282]
Currently the folder system in this website is a little muddled and could do with being tidied.
### Not externally accessible.

Any file or folder prefixed with a `.` or a `_` is not externally accessible.
- [x] `.github` is for special GitHub files only.
- [x] `.tx` is for special Transifex files only.
- [x] `_backend` is for storing backend files and libraries.
- [x] `_data` is for private data that is handled by some part of the site before being exposed.
- [x] `_lang` (previously `lang`) contains the translated Transifex files.
- [x] `_scripts` is for raw javascript, before being processed.
- [x] `_styles` is for raw stylesheets, before being processed.
- [x] `_templates` is for reusable sections of HTML.
- [x] `_tests` is for tests.
### Externally accessible.
- [x] `api` (previously `hook`) should contain hooks hit by other services, like printful, or ourselves.
- [x] `data` is for public data, like the slingshot json. This is loaded over HTTP.
- [x] `docs` is a site run by MDR, and should otherwise only contain `*.md` files.
- [x] `fonts` contains fonts we rely on.
- [x] `images` is for images.

**Comment by btkostner** [comment]
I would also like to add, that we should create an `api` folder, and move `backend` to `_backend`. This should be a lot easier to understand for new people contributing as everything in the `_backend` directory would be pure PHP functions, no echos or outputs. 

Things that we can include right now
- `api/configuration` for sending site variables like the release and stripe public key. Moving them away from inline `script` tags
- `store/inventory` -> `api/store/inventory` for setting store cookies
- `api/stripe/payment` for making payments

**Comment by btkostner** [comment]
I would like to make note that we probably don't want to move `lang` to `_lang` as it may come in handy for translating client side code unless we want to do an api endpoint (probably unnecessary).

**Comment by btkostner** [comment]
And here are my future plans for the `_scripts` folder in a bit more detail

- `_scripts/helpers` is for small snippets used in multiple parts of code
- `_scripts/lib` is for any and all external loaded libraries
- `_scripts/pages` is for all compiled files. One per page with the exception of `main.js`
- `_scripts/widgets` is for all small reusable components
