### ISSUE TITLE
Send a shirt when someone subs to that reward tier on Patreon

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1285]
Need to figure out a way to automate sending someone a shirt who's subscribed to a specific reward tier on Patreon. Major problem? Patreon gets shipping address but not size. So we need to find some way to collect the size data.

For interacting with Patreon looks like there's: https://github.com/Patreon/patreon-php

**Comment by cassidyjames** [comment]
Risks to consider here: if someone subscribes and immediately unsubscribes, do they get a shirt? If someone has subscribed previously and got a shirt, should resubscribing send them another shirt? Etc. Gotta make it hard to abuse. :)

**Comment by btkostner** [comment]
I should add that we currently validate the shipping hook with stripe payment id. So if we are sending out free stuff (or things without a charge ID) we will need to redo validation for the hook.
