### ISSUE TITLE
Fix cart page removing error

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1292]
I currently have no way of reproducing, but it was mentioned in slack, so it's not just me.

This related to when you have a single item in the cart and you try to remove it, sometimes JS will fail to get the product ID and variant ID, resulting in a 500 error.

Current fixes:
1) clear cache
2) add another item to cart, then remove both

**Comment by lewisgoddard** [comment]
I'm going to close this as I haven't seen any more reports about this. We can re-open it if we see more reports, but we are collecting JS errors and nothing like this has shown up.
