### ISSUE TITLE
Add a Tri-blend shirt

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1293]
I think we all agreed that we want to do a "heather" black shirt with the white logo. I think we want to make this its own item since it will be significantly more expensive and a different material.

The [TR401](https://www.theprintful.com/custom/t-shirts/141/american-apparel-tr401-unisex-tri-blend-short-sleeve-track-shirt?tab=Info) and [TR301](https://www.theprintful.com/custom/t-shirts/150/american-apparel-tr301-tri-blend-short-sleeve-womens-track-t?tab=Info) from American Apparel come in a "tri-black" and a "tri-oatmeal". Could be cool to do a white shirt. This is a nice shirt but it's $18. We could still sell it for $25, but it would be a significantly lower profit margin and doesn't leave much wiggle room to do sales. They recommend retailing it at $28.50. I think for simplicities sake it would be better to just make that $28 or $29
- [ ] We'll need mockup images
  - [x] Men's Black
  - [x] Women's Black
  - [ ] Men's Oatmeal
  - [ ] Women's Oatmeal
- [ ] Design a color selector
- [ ] Add the color selector

**Comment by danrabbit** [comment]
I'm gonna re-open this because I still want to add the Oatmeal shirts

**Comment by lewisgoddard** [comment]
Do you know what I'd love to see? Something like the current store, but gender agonistic. Make that selection like your size, but then switch all product images to the most recent gender selection.

**Comment by danrabbit** [comment]
Yeah Blake and I talked this morning about adding a gender selector. I think for now it's okay because it adds volume to an otherwise pretty empty store, but yes in a future revision it should be a selector like size and color

**Comment by btkostner** [comment]
To add my 2 cents:

There are quite a bit of things I would like to do, but I'm waiting for webpack to get merged so I can start using `es6` and `vue` for rendering instead of class selecting with jQuery. Because depending on how many selectors we have, the jQuery will get out of hand very fast.

Top of my head I was thinking:
- Size selector (already implemented)
- Color selector (kinda implemented)
- Fabric selector (cotton vs track tee maybe? probably bad idea)
- Gender selector

**Comment by danrabbit** [comment]
I don't think we should do fabric selection because the products will vary in price, weight, and in cut. It's especially noticeable in the women's tee where the track tee has a lower neck and (it looks like) shorter sleeves. So I think we should consider these fully different products

**Comment by cassidyjames** [comment]
Addressed as part of the new store
