### ISSUE TITLE
Some pages do not accept trailing slash in their URL

### ISSUE THREAD

**Issue by inad9300** [elementary/website#1297]
### Expected behavior

Access the [Development page](https://elementary.io/developer) should be possible when adding a trailing slash.

### Actual behavior

It is not. Others work (e.g. the [Store page](https://elementary.io/support)), but neither the [Development page]() nor the [Get Involve page](https://elementary.io/get-involved) work with a trailing slash.

### Steps to reproduce the behavior

1. Access to https://elementary.io/get-involved/ or https://elementary.io/developer/
2. Watch the disaster

### System information

- **Operating system**: elementary
- **Browser**: Firefox

**Comment by lewisgoddard** [comment]
I can confirm that this is browser independent. URLs should always be posted and linked to without a trailing slash. Currently, individual pages will not accept one, but sections with multiple pages (like the store or documentation) will allow it.

**Comment by lewisgoddard** [comment]
I'm curious as to why you ever entered those links to try them? I'm tempted to just close this.

**Comment by inad9300** [comment]
Well, that's a good question. I'm pretty sure I didn't get to them through a link, so it was either me trying to access the page manually, or simply trying to see if they work with a trailing slash -- which some times I do, and makes sense when you realize that some pages have it and some don't,

**Comment by lewisgoddard** [comment]
Based on our analytics, SEO means this isn't really a problem.
