### ISSUE TITLE
Redirect raw markdown doc links to normal pages

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1299]
We should be redirecting links like https://elementary.io/docs/human-interface-guidelines.md to the correct doc page like https://elementary.io/docs/human-interface-guidelines. This will help us maintain links between GitHub and our own website.

Suggested by @inad9300
Related to PR #1298

**Comment by lewisgoddard** [comment]
I don't agree, I expect those links to work like they do now.

**Comment by inad9300** [comment]
I just happened to found the GitHub's docs first. If I had seen the elementary version first I would have used it (I will from now on). It would be nice to make the links work on both sides though, but since the resources are limited, we shouldn't give high priority to this issue.

**Comment by lewisgoddard** [comment]
### Changes

1. Add redirecting under `/docs/*.md` to `/docs/$1`
2. Update all docs links to point to `.md`

### Effects

1. Links in GitHub docs work.
2. Raw view on the website no longer works.
3. Redirection with every docs link.
