### ISSUE TITLE
Scripts not loading as expected

### ISSUE THREAD

**Issue by emersion** [elementary/website#1309]
```
ReferenceError: Slider is not defined
<anonymous>
slider.run.js:7
jQl.unq()
elementary.io:56
jQl.boot()
elementary.io:56
jQl.boot/jQl.bId<()
elementary.io:56
slider.run.js:7:5

Loaded slingshot.js slingshot.js:67:5

Loaded slider.js elementary.io:109:1
```

As a result you can't download elementary (cannot change amount, nothing happens when the download button is clicked).

### Steps to reproduce the behavior

1. Load the main page

### System information

- **Operating system**: Arch
- **Operating system version**: n/a
- **Browser**: Firefox
- **Browser version**: 48
- **Enabled Browser Extensions**: -

**Comment by lewisgoddard** [comment]
Is this reproducible on your end? I can't in Firefox on elementary.

**Comment by btkostner** [comment]
Additionally, was this the first time visiting the site in a while, and / or did you have your developer console on?

**Comment by emersion** [comment]
I can't reproduce anymore. Seems like a cache issue.

**Comment by btkostner** [comment]
I'm reopening as I can consistently see this issue on [this beta site](https://beta.elementary.io/master/) with the developer tools open.

**Comment by lewisgoddard** [comment]
### Relevant Code
```
    jQl.loadjQ('https://cdn.jsdelivr.net/g/jquery@3,flipclock@0.7.7(flipclock.min.js)')
    jQl.loadjQdep("scripts/slider.js")
    jQl.boot()
</script>
<script src="scripts/slider.run.js" async></script>
```

### Issue Cause
> At the moment, inline call executions are not waiting jQuery-dependent modules, but only jQuery core. However, when jQuery is loaded, jQuery-dependent modules already loaded are run before inline scripts. But if some modules are longer to load and arrive after jQuery, they will be run after queued inline calls.

from [Cerdic/jQl](https://github.com/Cerdic/jQl)

**Comment by lewisgoddard** [comment]
Basically, you can't rely on `loadjQdep` to be ready before boot time is called. I guess since `loki` removes these files, we should instead focus on `showcase` over there.
