### ISSUE TITLE
Flipclock makes Webpage scroll to top

### ISSUE THREAD

**Issue by bigfatbird** [elementary/website#1331]
If you come to https://elementary.io/get-involved#desktop-development for example and hit the continue button  the url changes to https://elementary.io/get-involved#  and the webpage scrolls to top!

Firefox 48.0.1 on Mac OS 10.11.6

**Comment by btkostner** [comment]
The countdown is over, but we are going to keep the overlay in case we use it for other events, my bad.

**Comment by p-shannon** [comment]
Is this still valid? Can't seem to duplicate it and this issue is two years old.

**Comment by lewisgoddard** [comment]
I've done a quick and nasty branch under `example-event` to enable an event for you. I can confirm that visiting `/get-involved#desktop-development` on my local copy does scroll to top when clicking the Continue button.

**Comment by p-shannon** [comment]
I'm on the live site and going to the provided path I don't see a 'continue' button in any conspicuous position.
![screenshot from 2018-01-17 13-25-53](https://user-images.githubusercontent.com/31411889/35059675-f9baa9c4-fb89-11e7-88bb-5089ae5e7b3a.png)

I'm afraid I don't understand the issue here, please help?

**Comment by btkostner** [comment]
This is for the release countdown. Because we are not in the release process right now, you will not see it in production. In order to see it, you will need to checkout the `example-event` branch and run that.

Because you already have a working copy of the website, all you should need to do is:
```
git fetch
git checkout example-event
npm i
npm run build
npm start
```

**Comment by p-shannon** [comment]
Oooooh! Okay, this is a hilariously annoying ~bug~ ~feature~ bug
![image](https://user-images.githubusercontent.com/31411889/35061695-fd26fc7e-fb8f-11e7-97e5-694b73177b78.png)
So I assume continue is supposed to dismiss the modal?

**Comment by btkostner** [comment]
Yep. Without scrolling to the top.

**Comment by p-shannon** [comment]
Alright, thanks. Will being looking into a fix tomorrow.
