### ISSUE TITLE
Use a FAB to hide/show the countdown overlay

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/website#1334]
People are confused when the countdown is gone and they can't find a way to bring it back, since there's no way to access it again anywhere on the site. A Floating Action Button would probably be a good way for users to access the countdown.

**Comment by btkostner** [comment]
Less than 4 days... https://elementary.io/countdown

**Comment by lewisgoddard** [comment]
The countdown automatically comes back after a day, also see danrabbit's comment on https://github.com/elementary/website/issues/1337#issuecomment-244999835
