### ISSUE TITLE
Indicate shipping costs before store checkout. 

### ISSUE THREAD

**Issue by nicekiwi** [elementary/website#1336]
Copied from a conversion between myself and Dan on G+. 

It'd be nice to have some sort of indication of shipping costs.  Before You click the Checkout button or fill in any information. Ideally on the Product page. (You'll get way more conversions if you do this). 

An indication only. It doesn't have to be exact or cheap. you can use Geo-location features to get an approx location to estimate a cost. Right now you don't know if there even is a cost. 

Letting me calculate shipping or get an indication of it before I commit to filling out all my info in the checkout will go a long way for customers, Esp when international shipping is involved. 

I was pleasantly surprised at $5ish USD shipping to New Zealand. But I couldn't be bothered going through the checkout to find-out if there were shipping costs the first time you shared the updated store. 

Running a web-store can seem really simple, but its extremely easy to sabotage your own success with these little details that can be easily solved.

**Comment by lewisgoddard** [comment]
We have the country selector now, so we can easily look up the lowest price and say "shipping starts at"

**Comment by lewisgoddard** [comment]
Looks like we need a full address for shipping estimates, not sure though. @btkostner implemented that bit.

**Comment by btkostner** [comment]
For the shipping rate api we need:
- address1
- city
- country_code
- array of items

https://www.theprintful.com/docs/shipping

**Comment by lewisgoddard** [comment]
Huh, looks like this isn't so easy.

**Comment by nicekiwi** [comment]
Ahh, you use a 3rd party API. 

Based on that you could add it to the "Cart" page below the form to automatically fill out once the address is entered. 

Or add it earlier by spoofing the `address1` and `city` based on a users Zip-Code and Country from another 3rd party API. Although that's getting a bit too complicated for a project this size.

**Comment by lewisgoddard** [comment]
I wonder if we can use our current geo-locate to spoof an address line. We should be able to get a city.

**Comment by Laksha-Prashanth** [comment]
Has this been fixed? The shipping costs are being displayed now.

**Comment by lewisgoddard** [comment]
@Laksha-Prashanth This is in the checkout process, but this issue is about indicating estimates on product pages.

**Comment by p-shannon** [comment]
At the risk of sounding silly, I think using a quick and easy third party API as suggested earlier, that uses the information already provided in the shipping form  (red box, and ideally just the green box). Then we can display it where-ever it needs to be displayed.
![shipping tax display proposal](https://user-images.githubusercontent.com/31411889/35062869-732a4536-fb93-11e7-9d6a-3b6b5c6f133b.png)
I'm a terrible UI designer so this isn't a design proposal. If someone else makes a proper design as to how it should look / be displayed I'll happily attempt to code the functionality.

Also I hope I'm displaying a adequate understanding of the problem at hand, if not I apologize and kindly request elaboration on the issue.

**Comment by lewisgoddard** [comment]
I think we need to go back to the original comment here: **The aim is to get estimated shipping costs on the product page, _without_ the user entering any information, to increase conversions within the store.** International shipping can be surprisingly cheap, and we should extort that.

[`_backend/classify.functions.php`](https://github.com/elementary/website/blob/master/_backend/classify.functions.php) has code related to getting locations already. I think we need to use a modified version of this which, according to [MaxMind](https://github.com/maxmind/GeoIP2-php#city-example), can provide Cities and Postal Code estimates.

```
print($record->city->name . "\n"); // 'Minneapolis'

print($record->mostSpecificSubdivision->name . "\n"); // 'Minnesota'
print($record->mostSpecificSubdivision->isoCode . "\n"); // 'MN'

print($record->country->isoCode . "\n"); // 'US'
print($record->country->name . "\n"); // 'United States'

print($record->postal->code . "\n"); // '55455'
```

We should probably expose an endpoint like `/api/geolocate` with these as a JSON array to fetch the users approximate location, query our existing third-party vendor for shipping charges when loading a product, then append "with shipping from $xx" underneath the product price asynchronously.

**Comment by p-shannon** [comment]
This is quite informative, but also outside of the scope of my abilities at the moment. I'll continue passively learning PHP and contributing to other issues in the meantime. Thanks for the elaboration!

**Comment by lewisgoddard** [comment]
Working on this in `fix-1336`
