### ISSUE TITLE
Landing page countdown is uninformative

### ISSUE THREAD

**Issue by mikeanthonywild** [elementary/website#1337]
For those not familiar with the elementary OS release cycle, the countdown timer on the landing page is completely uninformative and potentially confusing. Perhaps a little too late now, but I would suggest the addition of some text announcing the imminent release of Loki above the timer.

**Comment by danrabbit** [comment]
The countdown has always been intentionally vague. For those in the know, it creates a feeling of exclusivity. They have a fun secret for a few days. And for those who don't, it creates a sense of mystery. People post about it on their online accounts speculating about what will happen at the end. Generating intrigue is fun and engaging. It's like the suspense before Christmas morning. You're not quite sure what you're going to get until it comes.

So this is a "won't fix" :)

**Comment by lewisgoddard** [comment]
Just an FYI for @danrabbit: We have a status flag for that.

**Comment by danrabbit** [comment]
Sorry, I was mobile at the time :p
