### ISSUE TITLE
Change home page title

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1340]
Maybe better to change the page title to the tagline "A fast and open replacement for Windows and OS X" since this shows up on social media previews and such

**Comment by btkostner** [comment]
I was just about to comment on that post in G+. Right now it's setup to mirror the download button. Should we drop all if that logic and just keep it "A fast and open replacement for Windows and OS X"?

**Comment by danrabbit** [comment]
Yeah, that would probably be more straightforward code-wise and it would be a more useful title for previews

**Comment by alex285** [comment]
That is the main title on Google (or any other engine) search results. It isn't just on social previews.
