### ISSUE TITLE
Do not translate proper nouns

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1341]
### Expected behavior

Throughout the website we use program titles, and project titles. They are proper nouns and should not be translated with transifex

### Actual behavior

Everything is translated

**Comment by leonardo-lemos** [comment]
Some languages needs to translate everything, like Korean, to match their pronunciation. It's better to leave everything the way it is and let the translation teams apply their translation guidelines based on their languages guidelines.

**Comment by danrabbit** [comment]
Leo is right. We're making this switch on desktop as well to accommodate non-latin char sets
