### ISSUE TITLE
Vagrant box is broken

### ISSUE THREAD

**Issue by mikeanthonywild** [elementary/website#1345]
### Expected behavior

A brand new Vagrant box should be able to build assets without installing any dependencies.
### Actual behavior

`npm run build` fails with:

> sh: 1: gulp: not found

`vagrant up` produced [quite a lot of errors](http://pastebin.com/fZCuGFCD).

Seems related to https://github.com/npm/npm/issues/7308?
### Steps to reproduce the behavior

```
$ vagrant up
$ vagrant ssh
$ cd mvp
$ npm run build
```
### System information
- **Operating system**: Windows
- **Operating system version**: 8.1
- **Vagrant version**: 1.8.4
- **VirtualBox version**: 5.0.26

**Comment by btkostner** [comment]
I have yet to actually test this (and it will probably be a while til I get a windows install up), but I know there are a lot of other projects that have similar issues with node on windows, so I'll confirm this.

**Comment by btkostner** [comment]
I have not tested this in windows, but it seems to run without any weird problems here. Would you mind checking out the [vagrant](https://github.com/elementary/website/tree/vagrant) branch and testing it to make sure the problem is fixed?

**Comment by mikeanthonywild** [comment]
Hi btkostner, I'm afraid I'm travelling at the moment and won't have access to a Windows box for a good few weeks. I will endeavour to test this when I get back.

**Comment by JamyGolden** [comment]
It looks like https://github.com/elementary/website/pull/1501 fixed this issue, so it should be closed.
