### ISSUE TITLE
Backend is very complicated

### ISSUE THREAD

**Issue by Om3rCitak** [elementary/website#1351]
I'm a web back-end developer. I want to contributing the elementary website but website backend is very complicated.

If you want again write to web backend with together?

edit; maybe using modern framework(s) (laravel etc..)

**Comment by lewisgoddard** [comment]
Mostly this is covered by #1282 because if it makes sense and has documentation it shouldn't be a problem.

**Comment by btkostner** [comment]
Along with that, there will also be improvements to the `scripts` folder soon with the introduction of webpack.

**Comment by lewisgoddard** [comment]
I'm closing this as opinion, most of the actionable points are covered elsewhere.
