### ISSUE TITLE
Verify your download should use Rufus (Docs on installation from Windows)

### ISSUE THREAD

**Issue by quassy** [elementary/website#1361]
Recent versions of Rufus support calculating image hashes (click the `#` in the status bar, since [Version 2.3 (2015.08.28)](https://github.com/pbatard/rufus/blob/b3c76b1f61ce380461edf1f8dbccb93626d174da/ChangeLog.txt)) so the [installation instructions on veryfing the download](https://elementary.io/docs/installation#verify-your-download) should also recommend using this feature. As Rufus is needed anyway to create the installation medium this allows users to use one program less and makes the whole process easier.

**Comment by lewisgoddard** [comment]
Oh, that's nice. pbatard/rufus#607
