### ISSUE TITLE
Add keyboard shortcuts cheatsheet

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1368]
It's an oft-requested addition to the docs. We do have shortcuts inline in the getting-started guide, but an easy-to-reference cheatsheet would be a welcome addition.

**Comment by danrabbit** [comment]
Personally, I wouldn't put a bunch of time into this just because we'll get shortcut sheets in Gtk 3.20

**Comment by cassidyjames** [comment]
Yeah, good call. Since it's been requested for Loki specifically, I'll just do something simple and similar to our [old Luna beta blog post](old.elementary.io/journal/keyboard-shortcuts-luna-beta-one).

**Comment by ryanleesipes** [comment]
I added what I thought was missing via #1372 - beyond that, I think the basics are there. Ubuntu features the shortcut window that pops up when you hold the super key for a bit. Is shortcut sheets something similar @danrabbit?

**Comment by danrabbit** [comment]
@ryanleesipes There isn't at the moment, but that's what I was referring to about the shortcuts sheets that are available in Gtk 3.20

**Comment by sudopluto** [comment]
any idea where this would go? the current getting starting guide has most of the important shortcuts inline, but i still think a table - something like what pop os has: https://github.com/pop-os/docs/blob/master/docs/keyboard-shortcuts.md - would be useful at the end of the current guide.

**Comment by sudopluto** [comment]
I think I can get working on this, as long as all the shortcuts I would need to include are in they keyboard plug for switchboard

**Comment by peteruithoven** [comment]
@sudopluto you might want to check: https://github.com/elementary/shortcut-overlay
That is the keyboard shortcut overlay that will be added to the elementary OS Juno release.

**Comment by cassidyjames** [comment]
This is basically solved with the shortcut cheatsheet on the homepage and in the OS. :)
