### ISSUE TITLE
Links to Valadoc  in /developer Are Broken

### ISSUE THREAD

**Issue by graczykr** [elementary/website#1380]
### Expected behavior

For instance on "Granite", the link is pointing to http://valadoc.elementary.io/#!wiki=granite/index.

### Actual behavior

It takes you to http://www.valadate.org:8000/#!wiki=index. One still needs to manually search for the desired item (i.e. Granite in this case, which would be the URL http://www.valadate.org:8000/#!api=granite/Granite)

### Steps to reproduce the behavior

1. Click on any valadoc related link on https://elementary.io/developer

### System information

- **Browser**:  Google Chrome
- **Browser version**: 53.0.2785.116 (64-bit)

**Comment by lewisgoddard** [comment]
Try clicking your third link, the "correct" one. That doesn't work either. The problem is with Valadoc, they don't handle links properly. Fix is here: flobrosch/valadoc-org#65
