### ISSUE TITLE
Fix Purchase button for non-integer amounts less than 1

### ISSUE THREAD

**Issue by tildearrow** [elementary/website#1383]
### Expected behavior

"Purchase" appears.

### Actual behavior

"Download" appears.

### Steps to reproduce the behavior

1. In "Pay What You Want", select "Custom".
2. Enter any lesser than $1 but greater than $0 amount.

### System information

- **Operating system**: GNU/Linux
- **Operating system version**: 4.6.2-rt5-1-rt
- **Browser**: Chromium
- **Browser version**: 53.0.2785.116

**Comment by danrabbit** [comment]
This is intentional. It would actually cost us money to process payments that are too small.
