### ISSUE TITLE
Ask downloaders where they learned about elementary OS

### ISSUE THREAD

**Issue by codygarver** [elementary/website#1390]
Would be nice to know.

**Comment by danrabbit** [comment]
I think we already get this info from analytics right? Would this only show for people who straight type in the URL?

**Comment by codygarver** [comment]
I was thinking something like:
```
* Website Post
* Social Media
* Somewhere else (fill in the blank)
```
I'm sure there are better options than that, it would be nice if we could get some results that make it clear what kind of outreach we could be doing that has a high return.

**Comment by lewisgoddard** [comment]
We have referrers in analytics, but about half of the users are from search engines, and 25% direct or no referrer information. Only 25% come from things we can actually trace.

Now that the thank-you page has been merged, there's somewhere for this to go.

**Comment by lorenzocafaro** [comment]
Hello everyone,

here's my proposal:

![ab1](https://user-images.githubusercontent.com/43943230/61212358-59cea980-a702-11e9-99c0-082aa18328c0.png)

Let me know your opinions about it. Thanks

**Comment by M4rk3h** [comment]
Also as @danrabbit mentioned analytics, i'm totally up for giving my data for analytics. I really liked the way KDE Neon did it, so I could crank the slider to the max!

**Comment by lewisgoddard** [comment]
On [Plausible](https://plausible.io/elementary.io?period=30d) the vast majority of our users are either from Google or Direct. Not sure we're actually all this interested in this given how long it has been open for, might be a candidate for pruning.

**Comment by danirabbit** [comment]
Agreed, closing
