### ISSUE TITLE
Images dead in getting-started.md

### ISSUE THREAD

**Issue by owcz** [elementary/website#1400]
There are dead image links in [getting-started.md](https://github.com/elementary/website/blob/master/docs/code/getting-started.md#developer-sdk-developer-sdk)—either should be removed or updated

**Comment by lewisgoddard** [comment]
Those docs are supposed to be viewed at https://elementary.io/docs/code/getting-started#getting-started, and I don't see any broken links.

**Comment by owcz** [comment]
Yes, the issue is only when viewing the markdown file, not with the website
