### ISSUE TITLE
`SSL handshake failed` on http://elementary.io/api/config in Midori

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1404]
`SSL handshake failed` on http://elementary.io/api/config

https://sentry.io/elementary-llc/elementarywebsite/issues/163350069/

```
Stacktrace (most recent call first):

  at captureException (/g/raven@3.7.0:3:6711)
  at onunhandledrejection (/:44:46)

[object Object]
```

**Comment by lewisgoddard** [comment]
Would be fixed by #1393, but the amount of these we're seeing shows there's a fair few people trying to view it over HTTP. It's possible this is why we're not tracking them.

**Comment by lewisgoddard** [comment]
https://sentry.io/elementary-llc/elementarywebsite/issues/163348690/

**Comment by lewisgoddard** [comment]
This looks to be affecting around 3-4% of people. Totally download / payment breaking. Bumped to critical.

**Comment by btkostner** [comment]
@lewisgoddard this seems to be fixed for midori, but still for some other browsers. Should we close this issue, or would you like to generalize it for the other browsers as well?

**Comment by lewisgoddard** [comment]
Unsure if the SSL is still the issue (it shouldn't be) but there's still lots of "failed to get config" errors.
