### ISSUE TITLE
change the download process on website

### ISSUE THREAD

**Issue by thanosk91** [elementary/website#1428]
I think that "custom amount" and 0$ input to download the distro for free is complicated! Just put another button "download for free" and suggest the user to use Bittorrent method to dowload the distro.

**Comment by danrabbit** [comment]
Unfortunately when there is a free button not enough people will pay to keep elementary in business. We need to be able to cover the costs of making elementary OS.

**Comment by lewisgoddard** [comment]
Duplicate of #342
