### ISSUE TITLE
Developer Valadoc Links not Redirecting Properly

### ISSUE THREAD

**Issue by ryanleesipes** [elementary/website#1429]
### Expected behavior

When clicking the reference links (pictured below), the links do not redirect to the proper page.

![reference_links](https://cloud.githubusercontent.com/assets/2141621/19056370/70f7563c-898e-11e6-975b-927a85ec9848.png)

### Actual behavior

Instead you are presented with this error:

![no_redirect](https://cloud.githubusercontent.com/assets/2141621/19056387/8a76efbe-898e-11e6-8ed1-e760c89e6242.png)

The base URL is: https://valadoc.elementary.io/

### Steps to reproduce the behavior

Click any of the reference links.

### System information

- **Operating system**: Elementary OS
- **Operating system version**: Loki
- **Browser**: Firefox
- **Browser version**: 49 
- **Enabled Browser Extensions**: Ghostery, LastPass, Grammary, DuckDuckGo

**Comment by ryanleesipes** [comment]
Tested in vanilla Epiphany, "Too many redirects" error message.

**Comment by ryanleesipes** [comment]
Why was this closed? Is it a duplicate?

**Comment by btkostner** [comment]
Sorry, we fixed the backend issue, but it has not been pushed yet. I'm working on it now. The close was a bit premature.

**Comment by lewisgoddard** [comment]
The close was automatic from the configuration merge.

**Comment by btkostner** [comment]
It should be resolved now
