### ISSUE TITLE
wrong german translation in get-involved

### ISSUE THREAD

**Issue by subjectdenied** [elementary/website#1432]
on the webpage under "get-involved" the german translation "Sehe unsere Skizzen" should be called "Sieh unsere Skizzen" or better "Betrachte unsere Skizzen"

**Comment by btkostner** [comment]
All of our translations are available for edits on [transifex](https://www.transifex.com/elementary/elementary-mvp/translate/#de/get-involved/82796632).

**Comment by subjectdenied** [comment]
ok, i changed it to my second suggestion above
