### ISSUE TITLE
Show Average Payments

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1443]
Currently not working for platforms, but at least we have the [overall average](https://elementary.io/backend/average-payments). We should implement a small popover when you select custom that shows the average payment

**Comment by sergiouve** [comment]
Hi,

I'd like to try to tackle this issue, but I need a production database replica for testing purposes and maybe a little design mockup for the popup.

**Comment by lewisgoddard** [comment]
@sergiouve The data is presented as a JSON dump available at https://elementary.io/backend/average-payments 

I recall seeing a design mockup somewhere, but cannot recall where.

@danrabbit Do we also want to highlight when someone is donating below average?

**Comment by btkostner** [comment]
Here is the mockup: https://github.com/elementary/mockups/blob/master/web/payment%20data.svg

**Comment by lewisgoddard** [comment]
#421 is related.

**Comment by lewisgoddard** [comment]
In #1463 `_backend/average-payments-output.php` dumps JSON at `data/average-payments.json` every minute through `cron` using code from the current `backend/average-payments.php`

**Comment by btkostner** [comment]
@lewisgoddard are you thinking server rendering or client rendering? I was thinking client side at first would be easier, but I am unsure.

**Comment by btkostner** [comment]
Also, if we expose the number of payments for each OS, we could do cool things like factor in the current custom amount when doing averages.

**Comment by lewisgoddard** [comment]
@btkostner That would also tell people how much money we were making for the period. Plus, after a few days most single payments will have no effect.

I was going to got for a client-side getJSON
