### ISSUE TITLE
Text (and translations) should use typographic (correct) quotation marks

### ISSUE THREAD

**Issue by quassy** [elementary/website#1445]
### Expected behavior
- Use of Englisch quotation marks, like “elementary” (= high 66, high 99)
- Use of German quotation marks, like „elementary“ (= low 99, high 66)
- Probably the same for many other languages
### Actual behavior

Use of so-called “dumb” quotation marks, like "elementary" (in English, German and probably other translations)
### Steps to reproduce the behavior
1. Read most texts on the elementary website which include quotation marks, for example [/brand](https://elementary.io/brand)

---

This is a bit of nit-picking, but the issue is actually more conspicuous in German. The issue should be adressed in the original English text first and then maybe (if that is possible) translation guidelines included in Transifex. 

(P.S.: It's very unfortunate that writing certain typographic symbols, special characters and emojis is so hard on Linux & Windows, so I get why “dumb” quotation marks are so widely used... [related bug on LP](https://bugs.launchpad.net/switchboard-plug-keyboard/+bug/1635090))

**Comment by png2378** [comment]
Translators are responsible for typographical symbols, similarly OS translation process on Launchpad. For example I use correct Russian quotes (`« »`) on [/brand](https://elementary.io/ru/brand) page.

You suggest to automate this process and forcing replace default quotes (`" "`) on correct quotes for each language?

**Comment by ArchangeGabriel** [comment]
See also https://github.com/elementary/website/issues/1165.

I think we agree on the use of correct typographic symbols. Translators are indeed responsible for those, and, as a french translator, I would also make use of « » quotation marks (but I haven’t checked those for now).

Note that currently there is a mixed use of “” and "" in the english website (homepage use the former).

However, for https://github.com/elementary/website/issues/1165 and this one, a lot of strings must be changed and we need to make sure it does not break existing translations. Is there a way to do this automatically or will it require relinking previous translations to new strings?

Then, either substitute them automatically in every language with the correct quotes/apostrophe for this language (lot of work), or just add a note to translation guidelines about that and let translators handle this.

**Comment by lewisgoddard** [comment]
Assuming we treat this the same as #1165 then we'll just try to use correct quotation marks going forward, not break a load of translations.
