### ISSUE TITLE
Implement custom receipts for OS purchases.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1455]
### Pre-deployment

- [ ] Add function to check Order ID exists
- [ ] Add API endpoint to set cookie like order happened in this browser.

### onSuccessfulOrder

- [ ] Add order ID to link in email
- [ ] Send custom, responsive receipt through Mandrill.

### onDownloadAgain

- [ ] Hit `/api/download-again?order-id=SOMETHING_SECRET_AND_LONG`
- [ ] Log the use and set the cookie.
- [ ] Redirect to homepage, who is none the wiser and treats the user like they just ordered it.

#### Ordered Cookie

```
// Set an insecure, HTTP only cookie for 10 years in the future.
$encoded = urlencode(str_replace(' ', '_', 'has_paid_'.$description));
setcookie($encoded, $amount, time() + 315360000, '/', '', 0, 1);
```

[api/payment.php, Line 24](https://github.com/elementary/website/blob/master/api/payment.php#L24)

#### Check Order ID

```
// Check the stripe checkout to make sure we have a _real_ call
try {
    $ch = \Stripe\Charge::retrieve($res['data']['order']['external_id']);
} catch (Exception $e) {
    header('HTTP/1.0 400 Bad Request');
    echo 'Inaccurate data';
    die();
}
```

[hook/store/index.php, Line 39](https://github.com/elementary/website/blob/master/hook/store/index.php#L39)

**Comment by lewisgoddard** [comment]
I'm closing #24 and #34 because desktop or mobile doesn't make any difference so long as the email template is responsive.

**Comment by danrabbit** [comment]
This is smart. You are smart. You're a smart guy. I like that.

**Comment by lewisgoddard** [comment]
So, working like we normally do, I set this up so it sends a super-dumb looking email with the link in that works, then #ux swoop in and make it sexy, seeing as they seem to approve the flow.

**Comment by lewisgoddard** [comment]
@btkostner I want to pull you into the discussion here. Seeing as this orders database is also going to be super-low-usage, but might grow quite a bit, do we want to go ahead and put MariaDB in the package now and just code for failure?

**Comment by btkostner** [comment]
MariaDB sounds good. I'll look at setting up the server side code for it and installing it.

I would try to code for failure as much as possible, just in case something does go wrong, we don't want the whole thing to stop working.

I guess the best thing would be if it cannot connect, it should set (or not) the cookie and continue on like no error occurred.

**Comment by rgb-one** [comment]
Something like paypal or skrill could be used no? That way the user can see an invoice in their paypal/skrill account.

**Comment by lewisgoddard** [comment]
There is a separate issue for adding PayPal to the default payments flow: #1441
