### ISSUE TITLE
/capnet-assist should not have analytics

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1464]
I'm seeing hits from capnet-assist in analytics. I was under the impression that we did not want to include analytics on this page since it's possible for the OS to trigger it, and we do not want to collect data without users actively seeking out the site.

**Comment by lewisgoddard** [comment]
I can confirm. This is likely due to the restructuring of how we handle script loading. Google Analytics is now just included by default. You are right that we need to add an exception case to this.

**Comment by btkostner** [comment]
I notice that we are loading the full header and footer for that page, and using CSS to hide it all. We could (should) split the templates up a bit more so we only load what we need.

Otherwise, here is a PR to stop all the scripts from loading on that page:
