### ISSUE TITLE
Add link to store at Get Involved: Funding

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1467]
Buying from the store is another (albeit slightly less direct) way for people to support us financially. People might be more inclined to purchase a tee or mug if they know it's going toward making elementary OS better.

**Comment by mdalmazan** [comment]
I've never contributed to an open-source project before and this one seems like a perfect beginner issue. I would like to take this one if that is alright.

**Comment by cassidyjames** [comment]
Thinking about the copy for this. Maybe something like 

> Buying merch from our store is another way to help us financially, plus you can get some exclusive elementary gear to show your support to friends, family, and coworkers.

for below the other paragraphs where we talk about funding methods, then just a button with `Store` with the others?

**Comment by mdalmazan** [comment]
Yeah that works. I would have to update the text for it

**Comment by cassidyjames** [comment]
Thanks, @mdalmazan!

**Comment by cassidyjames** [comment]
@mdalmazan checking back up on this as I'm doing some other updates to the store and would love to merge this.
