### ISSUE TITLE
All images should be compressed without losing quality.

### ISSUE THREAD

**Issue by rgb-one** [elementary/website#1471]
### Expected behavior

Website loads swiftly upon visiting the homepage.

### Actual behavior

On both mobile and desktop, the homepage of the website takes a few seconds to fully load (on mobile ~10 seconds and ~9s on desktop).

### Steps to reproduce the behavior

1. Visit the official elementary website 
2. observe the page loading speed and start counting

### System information

- **Operating system**: Elementary OS
- **Operating system version**: Loki
- **Browser**: Firefox
- **Browser version**: 49.0.2 
- **Enabled Browser Extensions**: None

### Observations & Recommendations
I think the culprit or at least major contributor to the slow loading homepage is the notebook.png image. Using a tool like https://tinypng.com/ or https://compressor.io/ can reduce the image size quite a bit. I tried tinypng and the reduction in image size was 74% and I could see no difference in the image quality.

On a larger scale, optimizing the images on the website may improve the web pages load time.

**Comment by lewisgoddard** [comment]
These images do show a massive decrease in size, although I was under the impression they had already been through TinyPNG. The other caveat is making sure you're using a [HTTP/2 supporting browser](http://caniuse.com/#feat=http2).

**Comment by rgb-one** [comment]
shortpixel.com and [image_optim](https://github.com/toy/image_optim) are alternatives to TinyPNG.

**Comment by lewisgoddard** [comment]
I guess #1588 is the current in-progress for this.
