### ISSUE TITLE
Use Etcher for all (cross-platform) installation media creation

### ISSUE THREAD

**Issue by 1j01** [elementary/website#1489]
[Etcher](https://etcher.io/) is already recommended in the macOS instructions. The tool is cross-platform, so I'm wondering, is there a reason it's not used in the instructions across all the platforms? Was it deemed not stable enough to use on Windows/Linux at some point, or have the instructions for other platforms just not been tested and updated yet?

At any rate, it would be even better to be able to automatically download the ISO file, verify it, and burn it to a selected storage device with an application based on Etcher. They actually say it's extensible for developers, which makes me hopeful. I'm not sure how much would be required, but even if it requires forking Etcher, I'd probably be happy to do the initial development. I have experience with Electron, I've made [elementary.css](https://github.com/1j01/elementary.css), and besides, it looks like [the icon's already done.](https://launchpadlibrarian.net/264945382/os-64.png) ;)

(For the experience after flashing, see also: [elementaryos/+bug/1474445](https://bugs.launchpad.net/elementaryos/+bug/1474445))

**Comment by matzipan** [comment]
Hey, if you wanna chat more about a a project which automatically downloads the ISO file, verifies it, and burns it, hop over on IRC, we're pretty responsive there, too. #elementary and #elementary-dev at irc.freenode.net. 

We've certainly been discussing this, especially since Fedora 25 was released this week with [Fedora Media Writer](http://developers.redhat.com/blog/2016/04/26/fedora-media-writer-the-fastest-way-to-create-live-usb-boot-media/). Their implementation is C++ with Qt.

**Comment by 1j01** [comment]
I'd rather discuss it on GitHub, where I can get notifications about the specific topic and people can read and link to the discussion. Maybe the website repo isn't quite the right place but I was told to open an issue here from [Launchpad](https://launchpad.net/elementaryos) which I was obliged to do as I much prefer GitHub.

I brought this up in [gitter.im/resin-io/etcher](https://gitter.im/resin-io/etcher) when I opened the issue and currently there's an [archive format](https://github.com/resin-io/etcher/blob/extended-archives/docs/EXTENDED-ARCHIVES.md) being developed with customization options which could be used as a step in the right direction, but of course it can't provide the full experience.

> It would be great to hear your feedback on how we can make Etcher more customisable for your needs, so you can get it to do what you need without having to fork it. Please feel free to add your thoughts to resin-io/etcher#740 (or create a new issue if you feel that'd be more appropriate)

**Comment by lewisgoddard** [comment]
For a start, Etcher doesn't include the verification option that the Windows option currently in use does.

**Comment by 1j01** [comment]
It's already supposed to do a checksum of the image and [compare it](https://github.com/resin-io/etcher/issues/45) against what gets written, and a [checksum can be included](https://github.com/resin-io/etcher/blob/bdf920f86459d4ab63e62bd3b380f6c2d336ceac/docs/EXTENDED-ARCHIVES.md#checksumtype-string) in an extended archive's metadata so it can verify it all the way through.

**Comment by lewisgoddard** [comment]
Not the verification of the image write, I take that as a given, the sha256sum verification of the downloaded image. Rufus checks that for us.

**Comment by 1j01** [comment]
Rufus doesn't quite "check that for us", it let's you click a button to show it; with etcher's Extended Archives, you'll be able to include a checksum so that it verifies the download automatically.
(Not a sha256 specifically, but it shouldn't be too hard to compute two checksums.)

**Comment by lewisgoddard** [comment]
@brainscript To continue the discussion here, the image catalog, as I understand it, is entirely theory at the moment, correct?

Also I like this animation:

![](https://etcher.io/static/images/product.gif)

**Comment by brainscript** [comment]
@lewisgoddard Well, at the moment, yes. But there are some docs on their plans:
- The `*.etch` file format, which can be used to easily open images in Etcher with metadata and the correct settings. Its structure is describe  [here](https://github.com/resin-io/etcher/pull/707).
- The plans for Etcher in the future. I've already linked [that blog post](https://resin.io/blog/the-future-of-etcher/) in my issue.
- Their [GitHub milestones](https://github.com/resin-io/etcher/milestones).

Of course I don't how near the future is in this case, but it seems quite promising ...

![](https://resin.io/blog/content/images/2017/02/etch-004.png)

With or without these features, Etcher is still the best choice (out of the three) in my opinion.
It's super simple, looks awesome and you can't do anything wrong unless you really want to.

**Comment by S1SYPHOS** [comment]
Full ack for switching to Etcher - especially (and that's what elementary starters want) because it's user/beginner-friendly.

**Comment by felipeozalmeida** [comment]
First of all, I want to congrats all the guys from elementary team! I've bought the OS and I went to the installation instructions. I've already installed elementary before using another tools, but now I just wanted to follow the docs. Unfortunately, I didn't make it with UNetbootin: it doesn't even showed me a GUI after all on a fresh Ubuntu 18.04.2! I've installed UNetbootin from their PPA as they recommend and I don't understand why it doesn't work. I'm following with a more modern tool now (Etcher) and I think the installation instructions for Linux could be updated to use it too. Thank you all!

![Screenshot from 2019-07-27 02-52-59](https://user-images.githubusercontent.com/30023777/61990591-b8a4f480-b019-11e9-91b7-0eed0b0f221c.png)

**Comment by tpow** [comment]
I don't see any reason to care about a cross-platform tool if there is already a tool available that is easy to use. As I mentioned in #2173, on Ubuntu, Startup Disk Creator was easy to use and already installed. Either way, remove the references to UNetbootin.

**Comment by lewisgoddard** [comment]
The guide never specifically targets Ubuntu, it targets Linux, mac OS, or Windows. "Startup Disk Creator" `usb-creator` is specifically an Ubuntu tool, and would almost certainly result in complaints from other Linux distributions users.

**Comment by cassidyjames** [comment]
This was fixed the the OS 6 release, sorry I forgot to close it!

**Comment by 1j01** [comment]
Cool, thanks! Nice video as well. :+1:
