### ISSUE TITLE
Cannot download 32bit elementary Os Loki version

### ISSUE THREAD

**Issue by LeandroJesusG** [elementary/website#1495]
I can not download the 32bit version of the website
The website does not let me choose

**Comment by btkostner** [comment]
Loki is 64bit only

**Comment by lewisgoddard** [comment]
See http://elementaryos.stackexchange.com/questions/7419/loki-32-bit-version/7643#7643

**Comment by LeandroJesusG** [comment]
ah ok, thanks!
