### ISSUE TITLE
Make it very obvious that the Store supports international shipping

### ISSUE THREAD

**Issue by codygarver** [elementary/website#1499]
People still ask if we support international shipping.

I think part of the problem is that the Store is hardcoded English but also a large part is probably that we don't state international is supported anywhere.

**Comment by cassidyjames** [comment]
Something like:

> ### Worldwide Shipping
> 
> We now ship all around the world! Place your order and choose from a number of shipping methods to fit your needs. Orders are made on-demand typically within 2&ndash;7 days.
> 
> <small>_Cuba, Iran, and North Korea excluded. Shipping methods, prices, and times vary by country._</small>

...with that italic text in smaller print instead of italics. :wink:
