### ISSUE TITLE
New URL for capnet assist page

### ISSUE THREAD

**Issue by matzipan** [elementary/website#1503]
As discussed on Slack, the http://elementary.io/capnet-assist was accidentally 301 to https. Now the OS browser will have cached that 301 redirect as https, which means that the captive portal assistant is no longer functioning properly (https requests cannot be intercepted and redirected by captive portals).

We need a new URL to use, one which we need to make sure does not 301 to https.

**Comment by btkostner** [comment]
I just pushed an update to our servers that change the 301 to 302 (temporary redirect). It should fix the issue, but if cache is still a problem I'll create `capnet.elementary.io`. Please test the change first and let me know if it's still an issue.

**Comment by matzipan** [comment]
Hey Blake,

We need a distinct URL too.

**Comment by btkostner** [comment]
I currently have a PR open to create `capnet.elementary.io`

**Comment by btkostner** [comment]
PR was merged, Felipe tested and gave the OK, should be released soon. Closing issue.

**Comment by btkostner** [comment]
PR was merged, Felipe tested and gave the OK, should be released soon. Closing issue.
