### ISSUE TITLE
Tumblr Information on blog.elementary.io

### ISSUE THREAD

**Issue by graczykr** [elementary/website#1511]
### Expected vs. Actual Behavior

Note that this does not constitute a technical issue. When accessing blog.elementary.io on a mobile device an advertisement is displayed for the Tumblr app (see attached screenshot). If possible, it might be a good idea to remove said advertisement.

![screenshot_20161229-174453](https://cloud.githubusercontent.com/assets/1781136/21550001/7ef3327c-cdf6-11e6-96be-6879c5f1211b.png)

### Steps to reproduce the behavior

Access blog.elementary.io on a mobile device.

### System information

- Nexus 5
- Android 7.1
- Chrome 55.0.2883.91

**Comment by danrabbit** [comment]
Since our blog is currently served from Tumblr, I don't think it's possible to remove it

**Comment by danrabbit** [comment]
Currently testing Medium https://medium.com/elementaryos

Gonna close this issue since I don't think we can remove this from Tumblr
