### ISSUE TITLE
100vh hero height breaks scrolling affordance 

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1515]
The 100vh height of the main hero image looks great, but it [breaks scrolling affordance](https://uxdesign.cc/dear-web-designer-let-s-stop-breaking-the-affordance-of-scrolling-fe8bf258df7b#.wuxg7dgwd); it's no longer immediately obvious that there is any more information on our homepage.

Instead, setting the height to 80&ndash;90vh would show the top of the next section, implying there's more information to see below.

**Comment by DXCanas** [comment]
Hi! Seeing as the 2 PR's above were closed with 

> dan said no.

should this issue be closed?

**Comment by bigfatbird** [comment]
Is this bug still relevant?

**Comment by lewisgoddard** [comment]
I think we need to reconsider this problem.

Desktop users have scrollbars so this isn't an issue. Most mobile browsers that didn't use to now have one, although it commonly fades out after a while, so less of an issue. We don't have some garish "scroll arrow" to get rid off, but we don't have the most obvious indication there is more too the homepage. This is less of a problem when you realise the primary call-to-action is above the fold anyway.

Seeing as I confirmed and design declined, I'm going to un-confirm and mark as "Needs Design".

**Comment by bigfatbird** [comment]
It never was a problem to me as I always try to scroll. i am not sure if the majority of the users scroll down or if it is a big problem.


 Given the fact it is tagged as bitesized and you actually could end up redesigning big parts of the website i am not sure if i should start working here! :D

**Comment by cassidyjames** [comment]
This has effectively been solved with more recent style changes.
