### ISSUE TITLE
Inconsitent use of alert class

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1526]
### Expected behavior

Have a class like `.grid__icon` to create the side icon grid we use thoughout our pages.

### Actual behavior

We are using the `.alert` class for things like the technology section of the [developer page](https://developer.elementary.io/). This is inconsistent causes confusion as the `.alert` class is not always an _actual_ alert.

**Comment by btkostner** [comment]
I'm marking this as a high priority as #1541 to fix #1525 has caused this issue:

![screenshot from 2017-01-19 18 03 18](https://cloud.githubusercontent.com/assets/3385679/22131586/a1ff75a6-de71-11e6-88b1-12c9cb606890.png)

should look like this:

![screenshot from 2017-01-19 18 03 34](https://cloud.githubusercontent.com/assets/3385679/22131591/a846b2bc-de71-11e6-9bbf-5130971523e3.png)

**Comment by Tardog** [comment]
Hi, I would like to work on this issue, provided it hasn’t already been claimed by someone else.

**Comment by danrabbit** [comment]
Hey @Tardog as far as I know, nobody has started working on this issue yet. Please feel free to submit a branch. Thanks! :)

**Comment by Tardog** [comment]
All right! One question though: As far as I can tell, the developer site loads several assets from the main site, but the content and HTML doesn’t seem to be a part of this repository. Where can I find the relevant code?

**Comment by danrabbit** [comment]
@Tardog The Developer page is constructed from a pug file [here](https://github.com/elementary/houston/blob/master/src/houston/views/index.pug)

**Comment by Tardog** [comment]
Ah, thanks. I’m going to create branches with identical names for each repo and reference them both in this issue when I’m done, if that’s okay for you.

**Comment by danrabbit** [comment]
sounds good, thank you very much :)

**Comment by Tardog** [comment]
Done. Both pull requests are up and awaiting review. :)
