### ISSUE TITLE
There are duplicated Stripe functions.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1530]
The functions `doStripeCheckout` and `stripeLanguage` in [`_scripts/pages/store/download.js`](https://github.com/elementary/website/blob/master/_scripts/pages/store/download.js) have near duplicates in [`_scripts/pages/store/checkout.js`](https://github.com/elementary/website/blob/master/_scripts/pages/store/checkout.js).

**Comment by btkostner** [comment]
At some point I would really like to split the download functions out of the store and homepage scripts to a seperate download widget.
