### ISSUE TITLE
Year in Copyright sign still showing 2016

### ISSUE THREAD

**Issue by ELChris414** [elementary/website#1535]
### Expected behavior

Show 2017 on the copyright sign at the Developer subdomain of elementary.io

### Actual behavior

Shows 2016 on the copyright sign at the Developer subdomain of elementary.io

### Steps to reproduce the behavior

1. Open [developer.elementary.io](https://developer.elementary.io)

### System information

Doesn't matter.

P.S. Make it self updating with <?php echo date("Y"); ?> for example.

**Comment by cassidyjames** [comment]
This is actually an issue on https://github.com/elementary/houston. I've moved this bug to: https://github.com/elementary/houston/issues/344

**Comment by ELChris414** [comment]
Thanks! I was looking through to find where was the repository for the subdomain!
