### ISSUE TITLE
Common measurements in HIG don't appear to be accurate.

### ISSUE THREAD

**Issue by TraumaD** [elementary/website#1559]
The common measurements for square icons in the HIG on the website don't seem to be accurate? Or at least they aren't lining up with what I am seeing as seen in the screenshot below.

![screenshot from 2017-01-26 13 42 18](https://cloud.githubusercontent.com/assets/10608836/22348786/a8c15646-e3d2-11e6-9604-d772b332d97a.png)

I use the 128x128 utilities-terminal icon from elementary-icons I downloaded from github on 01/26/17.

**Comment by snwh** [comment]
Well the baseline is 9, the mean line height (i.e. the center of the icon) is 64, and the x-height, which is height of the icon from the baseline (i.e. the height of the icon) is 104 (113-9=104).

**Comment by TraumaD** [comment]
Ok I was reading it as height from 0. Sorry about that.
