### ISSUE TITLE
Erro in portuguese translation

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [elementary/website#1561]
https://elementary.io/pt_BR/ Sould be "Pague o quanto quiser"

The same in the footnote - "Pague o quanto quiser" is better than "Pague o que quiser".

![captura de tela de 2017-01-27 11-18-53](https://cloud.githubusercontent.com/assets/12240167/22372220/8f8fce90-e482-11e6-9b6e-7fc8fe5d97f6.png)

**Comment by btkostner** [comment]
Feel free to submit translations for the website on [transifex](https://www.transifex.com/elementary/elementary-mvp/translate/#pt_BR/index/104613593). It will take some time for updates to show on the website.
