### ISSUE TITLE
Offer all available sizes in store

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1563]
Since tees are print-on-demand, there's not a real downside to offering all the sizes that Printful offers. According to the sizing charts, for [Men's fit](https://www.americanapparel.net/sizing/default.asp?chart=mu.shirts) tees it's **XXS** to **3XL**; for [Women's fit](https://www.americanapparel.net/sizing/default.asp?chart=womens.shirts) it's **XXS** to **2XL**.

This will likely require some design tweaking of our modal.

**Comment by comradekingu** [comment]
It might be that scaling is an issue. Does price vary?

**Comment by btkostner** [comment]
Price does change, but we already have products that change price with size implemented.

**Comment by lorenzocafaro** [comment]
We could use a dropdown for that:

![custom – 2](https://user-images.githubusercontent.com/43943230/61309220-118eb480-a7f2-11e9-9b66-8a1aba49fb24.png)

**Comment by lewisgoddard** [comment]
Might be worth moving the "Add to Cart" button to the bottom of the modal if we can.

**Comment by lorenzocafaro** [comment]
Yeah - this should work better:

![custom – 2](https://user-images.githubusercontent.com/43943230/66965840-694fec80-f07b-11e9-9a18-8eaaced586ae.png)

**Comment by cassidyjames** [comment]
Will be addressed in the new store
