### ISSUE TITLE
Promote AppCenter campaign

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1570]
We should add some promotion directing people to the upcoming AppCenter campaign.

Possible updates:
- [ ] Navbar link
- [x] Toast
- [x] Swap AppCenter and Apps sections on homepage
- [x] Update AppCenter homepage copy
- [x] Add link to AppCenter homepage section
- [x] Add section to Get Involved -> Funding

**Comment by cassidyjames** [comment]
We could change

> # The Indie, Open Source App Store
> AppCenter brings handcrafted apps and extensions directly to your desktop. Quickly discover new apps and easily update the ones you already have. No license keys, no subscriptions, no trial periods.
> 
> [Become a Developer](#)

to something like

> # The Indie, Open Source App Store
> AppCenter delivers native, Open Source apps to elementary OS. Quickly discover new apps and easily update the ones you already have. And soon, support indie developers directly through pay-what-you-want purchases.
> 
> [Back AppCenter on Indiegogo](#)
> [Become a Developer](#)

**Comment by cassidyjames** [comment]
The link will be https://igg.me/at/appcenter

**Comment by cassidyjames** [comment]
For Funding, we could add a full section (like the Bountysource one) above the others.

> # Indiegogo
> We&rsquo;re currently crowdfunding AppCenter, the pay-what-you-want app store, on Indiegogo. By backing us there, you'll be helping us pay for our remote team to get together in person with developers from our community for a week long sprint in Denver, Colorado.
> 
> [Back AppCenter](#)

**Comment by danrabbit** [comment]
I'm +1 on both of these ideas

**Comment by tehp** [comment]
Doing this now.
