### ISSUE TITLE
Sidebars are broken in Design and Reference docs

### ISSUE THREAD

**Issue by dberg918** [elementary/website#1575]
Also, the toast looks pretty bad on my Chrome.

![image](https://cloud.githubusercontent.com/assets/15258282/22812029/c714a56c-ef85-11e6-95e8-4cc57c8959f1.png)

**Comment by danrabbit** [comment]
It looks like you an old version of the stylesheet in your browser cache. Can you try clicking refresh while holding down the `ctrl` key to force refresh?

**Comment by btkostner** [comment]
I just manually cleared our cache _again_. This should hopfully force fix those style problems.

For the sidebar, could you please do `F12` and see if anything shows in the console.

**Comment by dberg918** [comment]
Ah shoot, that's my bad guys. `Ctrl+F5` did the trick. Probably should've tried that before posting this. Sidebars are all good, too.

Just FYI, looks like the toast isn't showing up on the Developer landing page. I'm guessing it might have something to do with the link being a subdomain?

**Comment by btkostner** [comment]
It's because that page is not actually part of the website, but is a whole other repository, and only shares a small amount of code.

Going to close this as it seems it was a cache issue.
