### ISSUE TITLE
animate closing the toast

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1577]
#DelightfulDetails

**Comment by btkostner** [comment]
What animation shall it be? Turning into smoke like a launcher in Plank? Flying upward off the screen? Shinking into oblivion?

**Comment by danrabbit** [comment]
Probably like a slide up and fade out would be fine. I can't remember if we're using [animate.css](https://daneden.github.io/animate.css/) but if we are, `fadeOutUp` is probably perfect.
