### ISSUE TITLE
Failed email validation/ bad reg ex for checking emails

### ISSUE THREAD

**Issue by Pix-I** [elementary/website#1591]
### Expected behavior

I expected the email to be validated and receive a email for the beta at:
https://developer.elementary.io/beta

### Actual behavior

Email wasn't validated and it showed an error on the page.

### Steps to reproduce the behavior

1. Go to https://developer.elementary.io/beta
2. Try an email with "-" (Ex. test@test-test.com), there are probably some other valid symbols
that aren't accepted.
3. error shows up

### System information

- **Operating system**: MacOsX
- **Browser**: Firefox Dev edition
- **Browser version**: 53.0a2 (2017-02-09) (64-bit)

**Comment by btkostner** [comment]
This should be visible in production sometime monday
