### ISSUE TITLE
Mention customs for International orders

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1592]
Printful passes customs onto the end user, and as far as I can tell, there is not support in the API to charge that upfront. We should mention this to buyers so they're not surprised when receiving their products.

https://www.printful.com/faq/taxes-and-fees/77-who-pays-the-customs-duties-taxes-

https://twitter.com/CassidyJames/status/831169102504923137

**Comment by Laksha-Prashanth** [comment]
Where do we show this to the users? In the checkout page?

**Comment by lewisgoddard** [comment]
Probably in the worldwide shipping area at the bottom of the store, as well as under the delivery options in the checkout.

**Comment by Laksha-Prashanth** [comment]
Can you please review this?
https://github.com/elementary/website/pull/1702
