### ISSUE TITLE
Vagrant file is not using xenial

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1593]
### Expected behavior

Vagrant mirrors our actual deployment as much as possible

### Actual behavior

`Vagrantfile` is based on trusty and not `xenial`

**Comment by alexgleason** [comment]
The latest Ubuntu Vagrant box has made breaking non-standard changes. For instance, the default user is named "ubuntu" rather than "vagrant." It does not seem that this will be fixed. You could use bento/ubuntu-16.04 for a less painful transition.
