### ISSUE TITLE
Don't name the ISO amd64

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1596]
I've received several emails from confused customers wondering where is the download for their Intel processor. We shouldn't name the download with "amd64".

**Comment by cassidyjames** [comment]
Do we prefer `64-bit` or something, or just unlabeled since we only support 64-bit?

**Comment by lewisgoddard** [comment]
I think we'd be better off just dropping the item from the name, we don't list any other system requirements in there. It's just convention at this point, and when have we ever cared about that?

**Comment by rugglcon** [comment]
What about x64? It means the same thing, but as Cassidy said if only 64-bit is offered then it would make more sense to drop it completely.
