### ISSUE TITLE
Consider rotating potentially exposed secrets

### ISSUE THREAD

**Issue by embik** [elementary/website#1602]
I'm not sure if it's really appropriate here, but [recently Google's Project Zero has found a serious issue with Cloudflare](https://bugs.chromium.org/p/project-zero/issues/detail?id=1139). [This blog post from Cloudflare has more information](https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/) but IMHO doesn't really reflect on the impact of this.

Basically, most data passing through Cloudflare could have been exposed (see [this comment on HN](https://news.ycombinator.com/item?id=13719481) and the whole comment thread for further insight). I'm not 100% sure what data (api keys, secrets, etc) could have been leaked because I'm not familiar with elementary.io's code, however I felt like bringing this to your attention was necessary.

(This should also make you change your private passwords / keys with pages listed [here](https://github.com/pirate/sites-using-cloudflare), but that's another issue altogether).

---

Edit: The page list I linked right above also includes sites such as digitalocean, medium and namecheap. elementary's accounts for hosting and blogging should probably get a new password as well.

---

Edit by lewisgoddard:

Site-wise, these are listed in [`_backend/config.example.php`](https://github.com/elementary/website/blob/master/_backend/config.example.php)

They are:
- [x] Stripe
- [x] Slack
- [x] Printful
- [x] Google Maps
- [x] Mandrill
- [x] Sentry

There are also infastructure providers:
- [x] Cloudflare
- [x] Digital Ocean

**Comment by lewisgoddard** [comment]
@btkostner I don't have access to most of the application keys, but should be able to do the two infrastructure items. Are you okay to do the others?

**Comment by btkostner** [comment]
Yep. I've been talking to Dan about a good time to do this, as I dont have access to all of those accounts

**Comment by btkostner** [comment]
Thank you for bringing this to our attention @embik. At this time all API keys should be changed and deployed to our servers.

**Comment by embik** [comment]
No problem @btkostner - Most likely nothing even happened, but you never know. Better safe than sorry.
