### ISSUE TITLE
Terminal Image missed

### ISSUE THREAD

**Issue by dkotrada** [elementary/website#1609]
### Expected behavior

Terminal screenshot should be shown

### Actual behavior

brocken image is shown

### Steps to reproduce the behavior

goto : https://elementary.io/docs/code/getting-started#terminal

eos loki

chrome

**Comment by lewisgoddard** [comment]
https://elementary.io/images/icons/apps/128/utilities-terminal.svg returns a 404 but https://github.com/elementary/icons/blob/master/apps/128/utilities-terminal.svg exists. @btkostner ?
