### ISSUE TITLE
Notify the user when their card was declined

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1612]
### Expected behavior

When a user's card is declined, a model or something shows telling the user about the error.

### Actual behavior

Silently fails and shows download dialog box.

**Comment by lewisgoddard** [comment]
If we add a Google Analytics event to this, we can have alerts for it too.

**Comment by lewisgoddard** [comment]
[`_scripts/pages/download.js` Line 113](https://github.com/elementary/website/blob/master/_scripts/pages/download.js#L113)

**Comment by lewisgoddard** [comment]
@btkostner Are we happy just not telling the user? Is tracking enough?

**Comment by btkostner** [comment]
@danrabbit ^
