### ISSUE TITLE
Add AppCenter to support page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1622]
What it says on the tin. With the new AppCenter update coming, I think we'll want a place on that page for it.

**Comment by Laksha-Prashanth** [comment]
Wouldn't this require a new design? Adding the AppCenter will result in odd number of apps.

**Comment by lewisgoddard** [comment]
I think ideally the top row would just overhang by half an item each side.

Hey blake ( @btkostner ), want to make another thing flexbox?

**Comment by btkostner** [comment]
Flexbox all the things!
