### ISSUE TITLE
[Blog] Fix the tumblr link redirects

### ISSUE THREAD

**Issue by aolko** [elementary/website#1626]
### Expected behavior

Link redirects should work

### Actual behavior

Tumblr complains about redirects in JSON

### Steps to reproduce the behavior

1. find relatively old article
2. click the external link
3. ???
4. profit

### System information

- **Operating system**: windows
- **Operating system version**: 10
- **Browser**: chrome
- **Browser version**: 57
- **Enabled Browser Extensions**: -

**Comment by danrabbit** [comment]
The redirects have been fixed for the Vala post. If you find any other posts with redirect problems, please name them explicitly
