### ISSUE TITLE
The store empties the cart on checkout when a non-English language is selected.

### ISSUE THREAD

**Issue by shabuninil** [elementary/website#1636]
After selecting the product and filling out my mail data, I get on the page with an empty basket. I expect that I will be able to pay for the goods with a card and expect it in my post office.﻿

The sequence of my actions:
1. opened the store section https://elementary.io/ru/store/
2. clicked on the item
3. in the opened modal chose the quantity 1 and clicked "add to cart"
4. opened the page where I fill out my mail data and after filling I click "check out"
5. the page https://elementary.io/ru/store/cart opens with the inscription "Your basket is empty".

**Comment by lewisgoddard** [comment]
I am able to replicate the error with any language prefix, for instance `fr`.
