### ISSUE TITLE
Make paypal available as a payment option

### ISSUE THREAD

**Issue by bigfatbird** [elementary/website#1639]
Many people in Europe/Germany do not have a credit card. You lose money here!

Solution is to offer paypal (or something else, maybe debit) as a payment option.

**Comment by OT-World** [comment]
Where it says custom just place a 0 in the box and then you will be able to download the file.

**Comment by bigfatbird** [comment]
That was not my point. I am widely aware I can get it for free.

**Comment by lewisgoddard** [comment]
Duplicate of #1441
