### ISSUE TITLE
Get Involved: Link to Needs Design label in GitHub

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1644]
Probably more useful than the current links about posting mockups to Google+

[This Link](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aelementary+label%3A%22Needs+Design%22)

**Comment by Laksha-Prashanth** [comment]
Hi, I'm new here. Heres the change:
https://github.com/elementary/website/pull/1670
