### ISSUE TITLE
Update codebase

### ISSUE THREAD

**Issue by JustSteveKing** [elementary/website#1647]
### Expected behavior

A modern code base which uses technologies that were created this side of 2010

### Actual behavior

Something my grandmother wrote

### Steps to reproduce the behavior

1. Open browser
2. Look at code in repo
3. Feel 100% better about my rushed code jobs

**Comment by JustSteveKing** [comment]
[Update](https://twitter.com/JustSteveKing/status/852092264004407296)

**Comment by btkostner** [comment]
While I agree that it's not pretty and can be improved many places, it works and has little dependency on other libraries. I would love to sit down and rewrite this the best way I can, but there is a lot of other stuff that takes priority right now.

If you have any specific issues with the code, or any _actual_ improvements that should be made, feel free to file a detailed issue.

**Comment by JustSteveKing** [comment]
Surely a modern code base and using libraries would actually increase the standard of the site? It appears that you have reinvented the wheel because you wanted it to be square.

This follows no specific design pattern, there is code smell everywhere, and maintaining this must be an absolute headache.

You use Stripe for payments, you need translations, you want speed and awesomeness but you don't want any dependencies, and you don't want to use a framework for ease .... none of this makes sense. Welcome to 2017, we have composer and coding standards

**Comment by btkostner** [comment]
A modern code base would definitely help the standard of the site, but we would be at the same road in a couple of years. Before this site we had a site with codeigniter. It worked, but could be a pain trying to overcome some of the library code. Originally this site was completely static, with only some PHP for things like translations and download links. Over time it started growing into more dynamic content and got harder and harder to refactor into "clean" code. Here is where we are know.

I would like to know what we reinvented. Aside from maybe the markdown parsing, everything here is pretty basic, or in a library with composer.

I come from a JavaScript background, so PHP tools are kinda foreign to me. I do completely agree that this repo needs some quality assurance tools for PHP, but in my searches I've come up with only really basic tools. I recently found `phpqa` which seems to have a good amount of useful tools, and a linter that actually does stuff. Hopefully soon I'll be able to integrate it with our PR process. Let me know some packages you use and I'll check them out.

My statement on dependencies might have came out the wrong way. It's not that we don't like depending on packages, it's that we don't want to tie our code to a huge framework like laravel, or code ignitor, or what ever else awesome new PHP framework is out. Most of them are designed for huge database driven websites. Completely overkill for a site that is mostly static content. Not to mention it would increase our response time 300%.

Composer is a recent addition and at the time namespace usage wasn't huge in the code base so autoloading is kinda pointless.

**Comment by JustSteveKing** [comment]
Laravel is not exactly huge .... yes it has a few dependencies which it loads in, but all of these are there to make the system super useful. Translations are easy, emailing is easy, integrating with social providers is easy, integrating with Stripe is easy, sending transactional emails is easy.

Seriously, using such an old code base makes me question the quality of the code in the OS itself. If the web tech is this bad - do I trust the tech in the OS?

For what you need, you could even get away with a sqlite database, if you do that little database stuff. Look into Laravel and what it could offer you. If you don't want to go that large possible look at Slim3 framework which is a micro framework. Look at symfony components or Silex, or anything but legacy procedural code with a fluttering of OOP and no architectural pattern.

Web application management should be easy and a breeze. Where do you store the products you use in Stripe? Do you have manual entries in the code to display them? Surely this makes things slower each time you want to add a new one? It means a developer has to add the new prduct instead of getting a simple helper to update the web.

It is sites like this that make PHP seem like a lesser programming language. PHP can be just as powerful as some of the heavier hitters like Python or Ruby. Spend 2 hours looking through Laravel documentation or looking at the Laracasts website and watch the free serieses and you will see how much this could really improve. You could even start getting slack notifications each time a download is started, or a product is purchased.

This code makes me sad

**Comment by btkostner** [comment]
I have looked at laravel, and in fact have used it. It's very nice, but it is _very_ large a framework. We don't need it, and we don't want anything that large. The OOP files you saw were an attempt at updating the code base, but sadly until someone sits down and rewrites all the files, it's going to be in that bad state of in between. I'm not disagreeing with you about the old code, or the need to do a more OOP style, or the need for a code style and linting. But like I said, we have other things that we are currently working on, and updating this code base is a large undertaking.

**Comment by cassidyjames** [comment]
Obviously trolls.
