### ISSUE TITLE
No purchase window for dollars > 0 and < 1

### ISSUE THREAD

**Issue by acagastya** [elementary/website#1649]
### Expected behavior
The download button should read "Purchase Elementary"

### Actual behavior
Even though I use custom amount for donation (US$ 0.99), I can not make the payment since the window won't appear and the button reads "Download Elementary".

### Steps to reproduce the behavior

1. Go to <elementary.io>
2. Enter 1 in the Custom textbox for "Pay What You Want".
3. The button reads "Purchase elementary OS"
4. Now change the value of Custom input to 0.99
5. The button new reads "Download elementary OS"

**Comment by btkostner** [comment]
This is intended behavior. It's not cost effective to process payments under $1.
