### ISSUE TITLE
Use elementary color palette for Get Involved page

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/website#1654]
Buttons and such still use the solarized color palette, we should use our own.

**Comment by lewisgoddard** [comment]
I think this was to intentionally match the color palette used in Scratch.

**Comment by kushalpandya** [comment]
I can take this up, where can I find color palette that we're supposed to use for buttons on the page? Also, is there an already proposed mockup that I can use as reference to update colors?

**Comment by lewisgoddard** [comment]
Brand guidelines can be found here: https://elementary.io/brand

It seems dan is okay with changing it, I kind of liked that it matched our default development environment.

**Comment by danrabbit** [comment]
Yeah I can go either way on it. I like the tie in to our developer tools too, but there's an argument to be made about being consistent with our brand colors. I'm +/- 0 on changing the colors

**Comment by clagosarias** [comment]
Hi there, would love to help on this. I just need to know exactly what you guys need.
Should I use this color palette? http://danielfore.com/palette (the colors here are different from the ones at https://elementary.io/brand)

**Comment by btkostner** [comment]
@clagosarias the http://danielfore.com/palette link is a newer version, and has an issue open to replace the current brand page colors.
