### ISSUE TITLE
Startin linting PHP files

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1657]
### Expected behavior

Nice clean PHP code style.

### Actual behavior

Tabs with spaces and spaces with tabs.

### The solution

We add [CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) with the PSR2 standard to the list of CI tests.

**Comment by btkostner** [comment]
Obviously this is a huge undertaking, so we shouldn't impliment it all at once. But we should make all new code use this standard, and start working on updating old files.

I want to ping @lewisgoddard and see if he is ok with using PSR2, or if there is something he likes more.

**Comment by lewisgoddard** [comment]
I use services like Codacy or Code Climate to run PHPCodeSniffer or PHPMD, although adding it to the existing Travis CI builds would be nice.

I have no major problems with PSR2 itself, it's not that restrictive.

**Comment by lewisgoddard** [comment]
We would need to exclude things pulled in via composer, an potentially `docs/_mdr/Parsedown*` unless that is moved (messing with MDR).

**Comment by lewisgoddard** [comment]
I think the standard is open to discussion depending on how many changes need to be made. PSR2 might be easier to automatically lint for from where we are right now, and would be better than PSR12 if that requires lots of manual work that likely won't get done anytime soon (this issue is over 2 years old).

**Comment by Claudio-code** [comment]
Can the starting point of the lint be the same as this shell file ./_tests/php.sh ? or need another shell to run it lint ?

**Comment by Claudio-code** [comment]
I can resolve it with php CodeSniffer implementing PSR2 but I need resolve these lint errors

![image](https://github.com/elementary/website/assets/42524939/3b5f5e98-6d43-438d-a238-48b05df89d15)
