### ISSUE TITLE
HIG sidebar list styling inconsistent between browsers

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1676]
The sidebar appears to look and function properly on stable Chrome and Epiphany, but has various states of screwy on Firefox and upcoming versions of Chrome.

## Chrome stable and Epiphany:

![chrome-stable](https://cloud.githubusercontent.com/assets/611168/25537857/7a89ac1a-2bfd-11e7-9914-0bd478c7ed2e.png)

## Latest Firefox:

![firefox](https://cloud.githubusercontent.com/assets/611168/25537859/7a9dcb32-2bfd-11e7-8b5d-940d51515a1d.png)

## Chrome Unstable:

![screenshot from 2017-04-28 10-26-05](https://cloud.githubusercontent.com/assets/611168/25537858/7a9b8764-2bfd-11e7-8489-965cd8933ca6.png)

---

It looks like our list styling needs to be revisited as it will get real screwy on future versions of Chrome and also looks oddly different on Firefox.

**Comment by lewisgoddard** [comment]
Apparently `.sidebar > ul` isn't enough to match `.sidebar ul ul` with a high enough priority, which makes no sense spec wise.
