### ISSUE TITLE
lewisgoddard.me.uk

### ISSUE THREAD

**Issue by jairuque** [elementary/website#1677]
### Expected behavior

Warning: require_once(D:\xampp\htdocs\website-master\_backend/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\website-master\_backend\bootstrap.php on line 8

### Actual behavior

Fatal error: require_once(): Failed opening required 'D:\xampp\htdocs\website-master\_backend/vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\website-master\_backend\bootstrap.php on line 8

### System information

- **Windows 10 **: 
- **64bits**: 
- **Firefox**: 
- **52**: 
- **Any**:

**Comment by btkostner** [comment]
This isn't the website for lewisgoddard.me.uk, but it looks like you don't have the dependencies installed. Look for a `composer.json` file and run `composer install`  in that directory. You will need PHP composer installed for this to work.

**Comment by danrabbit** [comment]
Closing as "Invalid" since this report is about another website.

**Comment by lewisgoddard** [comment]
Hey @jairuque,

1. Would you mind heading on over to [lewisgoddard/lewisgoddard.me.uk](https://github.com/lewisgoddard/lewisgoddard.me.uk) and filing this issue there?
2. I'd also like to know how you came about this message, what commands you ran, etc, as well as why you thought you should file it here?
3. Was it because my github has this elementary/website repository pinned?

Thanks a bunch.

**Comment by jairuque** [comment]
Thanks for answering. I am trying to clone elementary.io in xampp to study it but there is no documentation on the js technologies used.

**Comment by btkostner** [comment]
We use node for building client side assets. You will need node, and it's package manager npm installed. Then run `npm install`. 

https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md should have everything.

**Comment by jairuque** [comment]
Thank you, my mistake was not to consult such page.
