### ISSUE TITLE
Don't translate "elementary Symbolic Icon Theme"

### ISSUE THREAD

**Issue by png2378** [elementary/website#1686]
For some reason, "elementary Symbolic Icon Theme" string is [available](https://github.com/elementary/website/blob/master/_lang/ru/index.json#L51) for translation. Apparently this is content of svg-files and this must be excluded from translations.

**Comment by comradekingu** [comment]
@png2378 Where did you find it in use?

**Comment by comradekingu** [comment]
@png2378 @lewisgoddard Those are descriptive tags, so yes, keep them translatable.
Makes all the difference for blind users; which we can't assume to all be English-speaking.
