### ISSUE TITLE
Fix Dutch version of site in IE 11

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#1695]
We have a couple of hundred users issuing an error to sentry every day, referencing:
> TypeError: Kan de eigenschap style van een niet-gedefinieerde verwijzing of een verwijzing naar een lege waarde niet ophalen"

This is in dutch, and translates as "Can not fetch the style of an undefined reference or a reference to an empty value".

**This only seems to happen in IE 11, while using the dutch language, on the homepage.**

1. https://elementary.io/nl/
2. https://sentry.io/elementary-llc/website/issues/248052857/

**Comment by lewisgoddard** [comment]
This has now happened in Russian in Edge, but only in one instance. This may have something to do with the referrer.

**Comment by btkostner** [comment]
I am using a windows 7 VM with IE 11. I setup a redirect with referer header, have a `nl` language cookie, and am redirecting to `https://elementary.io`. I don't see an issue. The console does not show any error like the one mentioned, and everything I tested seems to work. Maybe this is something to do with windows 10?

**Comment by lewisgoddard** [comment]
I can't trigger it either, which makes it difficult to solve, but 3.9k events across 1.4k users seems unlikely to be just us reporting wrong.

**Comment by lewisgoddard** [comment]
I am no longer seeing this issue logged on Sentry.
