### ISSUE TITLE
Update homepage slingshot to use page dots

### ISSUE THREAD

**Issue by btkostner** [elementary/website#1714]
### Expected behavior

The homepage slingshot has dots to indicate the pages, just like current version of slingshot.

### Actual behavior

It's dated and uses numbers.

**Comment by p-shannon** [comment]
Still valid? If so, I'm willing to take a peek at it.

**Comment by btkostner** [comment]
Still valid. Go for it!

**Comment by p-shannon** [comment]
Thanks for the rapid response. I have a few requests;
1. Briefly describe what "Slingshot" is and what it's supposed to do.
2. Please point me in a direction (can be broad as I don't want to be spoonfed too hard) of the affected files.
3. Inform me anything I should know before I attempt my first contribution.

I'd appreciate the cooperation and I'll continue googling answers to my questions in the mean time.

Cheers!

**Comment by btkostner** [comment]
No problem!

1. Slingshot is the elementary application launcher. Right now we have a small "demo" of it on the homepage. On the bottom, in the list view, it currently shows some boxes with page numbers in them. This was from an older version that is no longer in use. It should instead show dots.

Right now:
![screenshot from 2018-01-16 10 57 25](https://user-images.githubusercontent.com/3385679/35004221-7af65cba-faac-11e7-9ece-012979b2f99e.png)

How it should look:
![screenshot from 2018-01-16 10 58 31](https://user-images.githubusercontent.com/3385679/35004238-858910b4-faac-11e7-8b04-f6d2708513d6.png)

2. The styles are [here](https://github.com/elementary/website/blob/adb201a5602a8006dca0356c84eb5e75034c03e5/_styles/home.css#L383) and the page template is [here](https://github.com/elementary/website/blob/8f839b9f59a32b102a3f9d08b823b9a5b3b35c57/index.php#L273)

3. You will need PHP and nodejs on your computer for development. Run `npm run build` to build all the styles and scripts, then you should be able to use `npm start` to serve the website.

Let me know if there is anything I can help with!

**Comment by p-shannon** [comment]
Very helpful! *Seems* as simple as updating a line or two in the style sheet. I'll get started in setting up my dev environment immediately. If you'd like you can go ahead and assign this to me, and I'll care for this as if it were a puppy.

**Comment by btkostner** [comment]
Sadly assigning people is limited to people in the elementary organiziation. This conversation should be adequate enough for anyone browsing this issue

**Comment by p-shannon** [comment]
Alrighty. Would any version of PHP do? Or will I need a specific version?

**Comment by btkostner** [comment]
Should be good with the "SImple PHP Server" section here: https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md#simple-php-server

**Comment by p-shannon** [comment]
Extremely helpful, thank you! 
Will post updates as I work.
