### ISSUE TITLE
Slingshot showing wrong apps in search

### ISSUE THREAD

**Issue by varanauskas** [elementary/website#1715]
### Edit
After further investigation into the "data/slingshot.json", it may appear that this is not actually an issue, and may be expected behavior, if so, please disregard this issue.

### Expected behavior

Slingshot showing the apps corresponding to the "entered" text.

### Actual behavior

Slingshot shows AppCenter at the top, despite "date" being entered
![screenshot](https://cloud.githubusercontent.com/assets/18397833/26203734/0f6cea26-3be5-11e7-8e8a-e120a6f0d9b5.PNG)

### Steps to reproduce the behavior

1. Open https://elementary.io/
2. Scroll down to the applications section
3. Wait for slingshot to begin searching

### System information

- **Operating system**: Windows 10
- **Operating system version**: 1703
- **Browser**: Firefox
- **Browser version**: 53.0.2 (64-bit)
- **Enabled Browser Extensions**: Greasemonkey, HTTPS Everywhere, JSONView, Reddit Enhancement Suite, Stylish, Youtube Plus

**Comment by btkostner** [comment]
I can confirm that AppCenter is the first listing when you type "dat" into Loki 0.4.1
