### ISSUE TITLE
Fix grammar in AppCenter image on index page.

### ISSUE THREAD

**Issue by MPratley** [elementary/website#1720]
Image in question:
https://elementary.io/images/screenshots/appcenter.jpg

Should be:
`It's an app`
Instead of:
`Its an app`

As "It's" is being used as a contraction of "it is" 

I'm guessing this is an issue with the description for NaSC but the mistake is therefore on the website so the image needs replacing here too.

**Comment by Appeltabak** [comment]
That's an typo in [appdata.xml](https://github.com/parnold-x/nasc/blob/nasc/data/com.github.parnold-x.nasc.appdata.xml#L10) file of the application, not in AppCenter ;) That file is used to display information.

Submit an issue or pull request to their repo in order to get it fixed.

**Comment by MPratley** [comment]
@Appeltabak I thought as much, so will pop over there. Although, the screenshots here will also need fixing after that's done.

**Comment by comradekingu** [comment]
The quality of the whole string overall is poor, it is needlessly long, and there is still another error just like it in there. It also invokes the question of "math/maths" for an audience of people whom will disagree both ways.

I tried fixing it:

> You are not a calculator.
> A clever interpreter takes only what it needs, from all of what you write, to give you only the answers you want. When used in conjunction with other equations, those change along with it.
> 
The name is not intuitive, it might even appear to be scary. Like NaCl is to "salt".
"Calculated normality" or something, would be better.

**Comment by btkostner** [comment]
I would recommend moving this conversation over to the nasc issue. It will be easier for everyone to track.

**Comment by larouxn** [comment]
Looks like this issue was fixed via https://github.com/parnold-x/nasc/pull/40. I believe this issue can be closed.
