### ISSUE TITLE
Reporting bugs section in docs references to Launchpad

### ISSUE THREAD

**Issue by Extravert-ir** [elementary/website#1724]
Seems like Elementary uses GitHub for development for a while but [this section](https://elementary.io/docs/code/reference#reporting-bugs) in docs refers to Launchpad which is confusing for new users (like me)

**Comment by lewisgoddard** [comment]
We are now in the last stages of moving all our applications away from Launchpad and over to GitHub, so I'm guessing that only a few small parts of this section actually need re-writing.
