### ISSUE TITLE
Download link in receipts does not trigger download

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1726]
Getting multiple reports of this lately

**Comment by btkostner** [comment]
The download link in the email shouldn't trigger downloads. It just sends them to the homepage with the paid cookie set so they see the "Download elementary OS" button. I double checked that emails are going out, and that the receipt email button works, and everything seems a-ok.

**Comment by danrabbit** [comment]
Ah okay, in that case still I seem to be able to reproduce an error. Clicking the button should set the cookie again right? I can't confirm that this happens. When you click the button it asks to pay again

**Comment by btkostner** [comment]
It's also based on release version. So if you are using an email from Loki 0.4 it won't set the download button on the website right now, because it's version 0.4.1

**Comment by danrabbit** [comment]
Ah that's probably the issue then. Though I am seeing mails from after 0.4.1 release about it. Can we make it not depend on release version?
