### ISSUE TITLE
Unable to find translation of slingshot demo in weblate

### ISSUE THREAD

**Issue by bigfatbird** [elementary/website#1731]
While trying to translate the website to German I wasn't able to translate the slingshot demo.

**Comment by lewisgoddard** [comment]
I think because the demo searches (and is generally dynamic) the decision was made to make it non-translatable. @btkostner should be able to confirm.

**Comment by btkostner** [comment]
Yes, that was intended behavior due to the nature of how the search was programmed. Translating it doesn't make much sence especially if the results can't change.
