### ISSUE TITLE
Hebrew and Arabic interfaces are reversed

### ISSUE THREAD

**Issue by yarons** [elementary/website#1732]
### Expected behavior

A special CSS should apply when switching to an RTL language, the entire website should be mirrored to the correct direction and the text labels and boxes should be RTL aligned.

### Actual behavior

The website keeps it default LTR appearance even after switching to an RTL language.

### Steps to reproduce the behavior

1. Switch to Hebrew or Arabic.

### System information

- **Operating system**: Mac
- **Operating system version**: 10.10
- **Browser**: Firefox
- **Browser version**: 55.0.1a
- **Enabled Browser Extensions**: AdBlock

**Comment by lewisgoddard** [comment]
I assume this seems strange but is still usable? I'd be interested to know how this is technically handled on other sites. Maybe a class on the body that switches respective alignments for all sub-elements.

**Comment by btkostner** [comment]
There is a branch that I started that does RTL for those two languages, but there is a bunch of stuff that needs to be fixed for those stylesheets.

Beta site: https://beta.elementary.io/rtl-lang/ar/

**Comment by yarons** [comment]
@btkostner This is much better, now lets talk about the individual fixes:
1. In <span> with class "pre-amount" the margin-left and margin-right values should be switched (So the $ sign will appear inside the box).
2. This css definition: .inline-tweet::after, .inline-tweet::after, the value for padding-left should actually be padding-right (So the Twitter symbol will be closer to the text)
3. The ".read-more::after" css definition should have content:""; so the arrow will face the opposite direction.
4. css definition ".read-more:hover::after" should have "transform:translateX(-10px);" so the arrow will move to the right direction.
5. <p> should have "text-align: right" in the css definition (So all the text boxes and labels will be aligned to the right direction).
6. The entire animation in Applications is messed up (There are several fixes to be applied):
<img width="742" alt="screen shot 2017-05-30 at 11 31 05" src="https://cloud.githubusercontent.com/assets/406826/26574834/8eda94c6-452b-11e7-9e83-0ded72b745d8.png">
7. This css definition: "#slingshot .app-display__description svg" should have "float: left" and "margin: 4px 0 4px 6px" (So the icon will be at the beginning of the sentence instead of at the end).

We're good for now, where can I find this magical CSS of yours?

**Comment by lewisgoddard** [comment]
Screenshots being translated is a separate issue.

Slingshot should probably be sub-enforced to left-to-right. Again, it's lack of translation is a separate issue.

**Comment by MahmoudKhalil** [comment]
I had a look at the beta site provided, I think everything is aligned properly except that I think that the icons in the 3 Way to Explore section (grid icon, categories icon, and search icon) should be aligned to the right of the words too. other than that and the problems you mention, I think everything is aligned properly now.

![elementary](https://cloud.githubusercontent.com/assets/9035341/26672839/fa644e86-46ba-11e7-9fe5-0acdb582f970.png)

**Comment by nasserbinlaboun** [comment]
Could you assign this Issue to me?

I will solve this problem.

**Comment by yarons** [comment]
Is there any special CSS loaded when Hebrew or Arabic is selected? If no I can fix it pretty quickly, thanks.

**Comment by yarons** [comment]
I'm not sure removing Slingshot will solve the RTL problem, am I right?
