### ISSUE TITLE
AppStream redirect

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1736]
We'll want to provide some sort of simple `appstream://` redirect server to handle users not on elementary OS as well as sites that don't like linking to non-http/https protocols.

I imagine we'd start by just transparently redirecting `appcenter.elementary.io/$foo` to `appstream://$foo`, but we'd want to catch non-elementary OS users and do some other error handling if possible.

**Comment by cassidyjames** [comment]
Also, this should _probably_ be its own little repo and mini app since:

1. It should live on its own subdomain,
2. It could be somewhat generally useful for other people, and
3. We could write it in node instead of PHP :stuck_out_tongue:

**Comment by btkostner** [comment]
This is finished and live at https://github.com/elementary/appstream-redirect https://appcenter.elementary.io
