### ISSUE TITLE
Switching between vertical and horizontal layout needs to be improved

### ISSUE THREAD

**Issue by fakabbir** [elementary/website#1737]
### Expected behavior
The webpage should switch to a vertical layout instead of horizontal display layout for image and text. 
![expected_1](https://cloud.githubusercontent.com/assets/13721550/26760429/51532696-4935-11e7-87ae-2528fcd15b3b.png)
![expected_2](https://cloud.githubusercontent.com/assets/13721550/26760431/51691d70-4935-11e7-9972-af3480235bd9.png)

The Paragraph :
**The Indie, Open Source App Store**
AppCenter delivers native, Open Source apps to elementary OS. Quickly discover new apps and easily update the ones you already have. Plus, support indie developers directly through pay-what-you-want purchases." 
***should move down and the image should cover the screen.***

### Actual behavior

The webpage maintains a horizontal display layout for image and text, which makes image cropped from right.
![actual_page](https://cloud.githubusercontent.com/assets/13721550/26760430/5166b076-4935-11e7-8cbd-2f0c7add9e1b.png)

### Steps to reproduce the behavior

1. Open the website in 15.6 in Screen.
2. Scroll to "The Indie, Open Source App Store" section.
3. While decreasing the zoom level, the bug could be observed.

### System information

- **Operating system**:  Antergos OS
- **Operating system version**: 
- **Browser**: Chromium
- **Browser version**: 56.0.2924.87 (64-bit)
- **Enabled Browser Extensions**: GNOME Shell integration only

**Comment by btkostner** [comment]
This is actually the intended design for that section.
