### ISSUE TITLE
Error title bar menu of wireless network auth window

### ISSUE THREAD

**Issue by hungtcs** [elementary/website#1739]
### Expected behavior
When I connect to my corporate's wireless network,system will popup authentication window automatic ,but this window is always on top and visible on all workspace,and when I right click the title bar ,will show this popup menu. The question is: when I click item `Always on top`,it's not work,but `Always on visible Workspace` worked.

![screenshot from 2017-06-05 11 34 21](https://cloud.githubusercontent.com/assets/11692935/26769646/255904ee-49e3-11e7-83d5-277d40e32589.png)

### Steps to reproduce the behavior
It is difficult to express in words ,and my English is not good ,so I recorded a video of my screen.Can I send it to you in any other way?

### System information

- **elementary OS 0.4.1 Loki**
- **0.4.1 Loki Built on "Ubuntu 16.04.2 LTS"**

Thank you

**Comment by lewisgoddard** [comment]
You're saying that this window is always on top, regardless of whether or not that option is checked within the menu?

I think that is by design, the window itself is made by [capnet-assist](https://github.com/elementary/capnet-assist), and this bug should probably be filed there instead.
