### ISSUE TITLE
Developer tutorial: error when cloning Debian template 

### ISSUE THREAD

**Issue by derkomai** [elementary/website#1746]
### Expected behavior

While following the developer tutorial, at the Debian Control section, it is requested to run the following command to clone the debain template:

`git clone git@github.com:elementary/debian-template.git`

### Actual behavior

The following error is shown in Terminal:
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This command worked instead:

`git clone https://github.com/elementary/debian-template`

### Steps to reproduce the behavior

1. Run `git clone git@github.com:elementary/debian-template.git` in Terminal.

### System information

- **elementary OS**
- **0.4.1 Loki**

**Comment by danrabbit** [comment]
It sounds like you haven't imported your public key to GitHub. Make sure to visit your [ssh keys](https://github.com/settings/keys) page and import it. See the documentation [here](https://elementary.io/docs/code/getting-started#github) for more info :)
