### ISSUE TITLE
Add pricing information to developer page

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1749]
At the moment there's no pricing information up front. It's kind of tucked away in the ToS. It should be more obvious what platform fees are before signing up.

**Comment by Laksha-Prashanth** [comment]
Where do you feel it should be mentioned in the page?

These are two locations it might fit:

![end of page](https://user-images.githubusercontent.com/6800048/27707613-8f429308-5d33-11e7-8262-b677cebf2ed1.png)
![above vala](https://user-images.githubusercontent.com/6800048/27707615-8fabf5b4-5d33-11e7-92c0-8f62a3e3e02a.png)

**Comment by lewisgoddard** [comment]
I think it was more implied that we actually dedicate a nicely designed section and state what the fees are in plain language, with ToS listing it in legalese.

**Comment by danrabbit** [comment]
Yes something like [this](https://stripe.com/us/pricing)

**Comment by danrabbit** [comment]
Closing this because this page is actually provided by elementary/houston. Tracking here: https://github.com/elementary/houston/issues/492
