### ISSUE TITLE
Don't translate docs/HIG

### ISSUE THREAD

**Issue by png2378** [elementary/website#1757]
After discussions in Slack, we decided that we don't need to translate developer docs, include docs-human-interface-guidelines, but now it is available for translation.

**Comment by png2378** [comment]
@btkostner thanks for quick fix!

Perhaps we should remove `docs-human-interface-guidelines` component from Weblate django panel? If no one mind, I can do it myself.

**Comment by btkostner** [comment]
@png2378 should be removed now ;)
