### ISSUE TITLE
The App Center doesn't work in italian Elementary OS

### ISSUE THREAD

**Issue by nikzuzu** [elementary/website#1763]
### Expected behavior

I can't open The AppCenter, the app center doesn't work on my italian language Elementary OS

### System information

- **Elementary OS**: 
- **21.06.2017**:

**Comment by btkostner** [comment]
Please open an issue on the [AppCenter repository](https://github.com/elementary/appcenter/issues/new) and include more details. Does it crash? Does a window appear first? What version of elementary are you using? etc.
