### ISSUE TITLE
Can't click the buttons for amount or buy

### ISSUE THREAD

**Issue by MoritzFago** [elementary/website#1769]
### Expected behavior

I enter 0 in the custom amount field
button changes to download
click, download

### Actual behavior

buttons not clickable

### Steps to reproduce the behavior

1. open elementary.io
2. click

### System information

- **Operating system**: macOS 
- **Operating system version**: 10.12.5
- **Browser**: Safari
- **Browser version**: 10.1.1
- **Enabled Browser Extensions**: Instapaper, TabLinks, 1Password, uBlock Origin

**Comment by btkostner** [comment]
1) what language is the site on?
2) can you right click > inspect element > console and see any errors?

**Comment by sumnerevans** [comment]
Just reproduced this issue with only the uBlock plugin installed. There are no errors in the console. The uBlock plugin shows that google-analytics.com was blocked.

I reproduced this in both the English, Spanish, and German versions of the site so I'm guessing this is a problem across the board.

**Comment by btkostner** [comment]
It seems I still can't reproduce. I installed adblocker and uBlock origin, I am getting a google analytics load error, but everything still seems to work.

@lewisgoddard have any thoughts of things I have missed?

![screenshot from 2017-07-13 21 21 23](https://user-images.githubusercontent.com/3385679/28198222-63fd0578-6811-11e7-9026-2b969feba10e.png)

**Comment by sumnerevans** [comment]
@btkostner, this problem only exists in the Safari browser.

**Comment by btkostner** [comment]
@sumnerevans ahhhh, that would explain why I could never reproduce it. I'll try working on it tomorrow when I have access to safari. Thanks for the help tracking that down.
