### ISSUE TITLE
Add "clicked" guidance to code reference

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#1770]
GTK widgets respond to "clicked" which is a press + release; for example, this lets you drag a window from a button without triggering the button. We should consider mentioning this in our code reference as it seems to be a recurring (https://github.com/elementary/granite/issues/39, https://github.com/elementary/granite/issues/82) issue.

**Comment by JackieCalapristi** [comment]
Is it alright if I try to take this one? It would be my first contribution to OS! :)

**Comment by btkostner** [comment]
You don't have to ask permission, just comment on the issue so people don't also start working on it :wink:

**Comment by JackieCalapristi** [comment]
Oh good to know! Ok, I'm working on this one! 😃

**Comment by JackieCalapristi** [comment]
I've created a [pull request](https://github.com/elementary/website/pull/1798) that includes "clicked" guidance in reference.md!
