### ISSUE TITLE
Link to Mastodon account

### ISSUE THREAD

**Issue by sorin-davidoi** [elementary/website#1776]
### Expected behavior

It contains a link to the [Mastodon account](https://mastodon.cloud/@elementary).

### Actual behavior

It contains links to other social networks but not to Mastodon.

### Steps to reproduce the behavior

1. Visit Get Involved page

**Comment by cassidyjames** [comment]
@sorin-davidoi good idea! Right now we're using Font Awesome to provide all of the social icons, and it looks like they don't (yet) have a Mastodon icon. I'm going to consider this as blocked until that's added (unless someone wants to find a good, clean way to add our own in).

**Comment by sorin-davidoi** [comment]
Issue to track: https://github.com/FortAwesome/Font-Awesome/issues/10897

**Comment by BaptisteGelez** [comment]
Someone opened a PR to add the Mastodon icon to FA: FortAwesome/Font-Awesome#12238

**Comment by micahilbery** [comment]
Font-Awesome doesn't accept PRs for icons. They haven't and probably won't implement the Mastodon logo in FA5 unfortunately. However there's a fork of the project [Fork-Awesome](fork-awesome.github.io), that is more open to contributions and has Mastodon icon we could use it.

**Comment by sorin-davidoi** [comment]
Looks like it was accepted: https://fontawesome.com/icons/mastodon
