### ISSUE TITLE
HIG: Add search for symbolic icons

### ISSUE THREAD

**Issue by stsdc** [elementary/website#1777]
### Expected behavior
Something like this: https://material.io/icons/

### Actual behavior
Maybe I mislooked this in HIG, but I couldn't find info how to add icons and what icons could be used.

**Comment by theotix** [comment]
Hello,
Looks like [Font Awesome](http://fontawesome.io/icons/) is used as icon libraries. So you can use their search module to find an icon. Otherwire I'm not sure is what you're looking for. 🙃
Don't hesitate to correct me on the point and/or develop more.

**Comment by btkostner** [comment]
I think he is talking about the desktop icon theme. The hard part of this is keeping it in sync with the desktop. I think the correct approach to this would be a desktop app where the developer can search the icons.

**Comment by danrabbit** [comment]
Yeah, I think this is probably out of scope for the website. On the desktop you can use `gtk3-icon-browser` to search through available icons :)
