### ISSUE TITLE
Remove shorthand tags

### ISSUE THREAD

**Issue by brunocamarggo** [elementary/website#1778]
### Expected behavior

Just replace the shorthand tags `<?= ?>`, `<? ?>` to full tag `<?php ?>`

### Actual behavior

The shorthand tags `<?= ?>`, `<? ?>` are used in various part of the project.

### Exemple
The following line:
`<img src="<?=$sitewide['root'];?>images/brand/logomark.png" alt="logomark">`
Turns to:
`<img src="<?php echo $sitewide['lang-root'];?>images/brand/logomark.png" alt="logomark">`

**Comment by lewisgoddard** [comment]
While I have nothing against using short tags, we do specify not to in [.github/CONTRIBUTING.md](https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md)

**Comment by javielico** [comment]
Submitted a fix on this, pull request #1790.
