### ISSUE TITLE
Unable To Download From Website

### ISSUE THREAD

**Issue by aguragorn** [elementary/website#1796]
### Expected behavior

Download would start? Or something that will enable me to download the iso/installer

### Actual behavior

There is an error in the console: 
**During page load**: Uncaught TypeError: _analytics2.default.then is not a function
**Upon Clicking the button**: Uncaught ReferenceError: ga is not defined

### Steps to reproduce the behavior

1. go to https://www.elementary.io
2. Click on **Purchase elementary OS** button

### System information

- **Operating system**: Windows 10 Enterprise
- **Operating system version**: 1703 (OS Build 15063.540)
- **Browser**: Vivaldi, Chrome, Firefox, Edge
- **Browser version**: latest
- **Enabled Browser Extensions**: any, even none

**Comment by aguragorn** [comment]
If there's a work around that I can do, it would be great.

**Comment by btkostner** [comment]
Interesting. It seems you are getting the old version of our JavaScript. Any chance you could open up chrome, clear your cache, and try again? This problem should already be fixed.

**Comment by aguragorn** [comment]
Works fine now. Thanks!
