### ISSUE TITLE
Update Medium Icon

### ISSUE THREAD

**Issue by alphachung** [elementary/website#1806]
### Expected behavior

The icon for Medium (elementary blog) in the new, current Medium logo. 

### Actual behavior

The icon is the old Medium logo. 

### Additional information

Blocked by FortAwesome/Font-Awesome#11431. Presumably when Font awesome 5.0 is released and this website updates to that version, this issue will be fixed automatically.

**Comment by lewisgoddard** [comment]
I agree that this is currently blocked. We have an auto-updating link to Font Awesome at [`_templates/header.php Line 79`](https://github.com/elementary/website/blob/master/_templates/header.php#L79). I also believe we have ordered the "Pro" version of 5.0

**Comment by alphachung** [comment]
Now Font Awesome 5 is released, I believe this can be worked on? As well as making sure every icon on the site is OK under FA5.

**Comment by btkostner** [comment]
I believe that elementary has a pro license from the Kickstarter. Secondly, I would start out just using the icons for now. We can do the svg and js logic later if we want.

**Comment by alphachung** [comment]
But it looks like you cannot just use the new stylesheet drop-in, if you wish to keep the 4.7 icon class names for now, you have to use JS+SVG with their V4 Shim: https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by btkostner** [comment]
We don't need to keep the same icon names, but I would like to keep JS logic to a minimum until we need it.

**Comment by danrabbit** [comment]
It looks like some of the icon names we're using from version 4 (long-arrow for example) are now only available in Pro. The Pro CDN isn't available yet, but they do offer packages with npm. We'll probably discuss how/when we want to provide further in Slack, just for the sake of quick  conversation

**Comment by cassidyjames** [comment]
This has been addressed.
