### ISSUE TITLE
HIG doesn't state anything about Accessbility

### ISSUE THREAD

**Issue by snowparrot** [elementary/website#1816]
### Expected behavior

Coders and designers need tools and patterns to get better accessibility in their apps but there is no section in the HIG. Write a section in the HIG about accessbility.

### Actual behavior

Nothing.

**Comment by danrabbit** [comment]
This issue is too vague to be actionable. Please modify the issue with a single specific actionable task

**Comment by snowparrot** [comment]
@danrabbit changed.

**Comment by cassidyjames** [comment]
From @danrabbit on Slack:

>One thing I've been thinking about is redoing the "minimal configuration" section with the ideas we talked about from the Mark Brown video about focusing on making things accessible
so it's not just negative and there's more clarity about how do we qualify the difference between settings and design/engineering decisions

**Comment by cassidyjames** [comment]
We've implemented the previous change. If there's more specific content you're looking for, feel free to open a new, more specific issue (or better: PR the content!) ;)
