### ISSUE TITLE
Kernel button text turns blue on hover

### ISSUE THREAD

**Issue by TraumaD** [elementary/website#1827]
None of the coloured buttons on the open source page change text colour on hover except the "Kernel" one.

![screenshot](https://user-images.githubusercontent.com/10608836/31301110-431f0b28-aabd-11e7-93f0-ac1424552a71.png)

### System information

- **Browser**: Firefox
- **Browser version**: 56

**Comment by joestrouth1** [comment]
Text within the elementary and pantheon buttons in the upper section of the page does change color. Button text in the lower section does not. #1829 makes the kernel button consistent with the others in its section.

If a universal hover state would be preferable, it will need to be different from the existing one. Legibility suffers when applied to the colored buttons, and depending on the background, falls below WCAG contrast guidelines.

**Comment by theotix** [comment]
I agree with the idea that It should be an hover/focus state, but the text color should depends of the same selector as for the button background color.
