### ISSUE TITLE
color palette should be in the developer docs

### ISSUE THREAD

**Issue by TraumaD** [elementary/website#1831]
We should probably reference and link to the <a href ="https://github.com/elementary/icons/blob/master/elementary.gpl">colour palette</a> in the docs for developers. So that devs are better equipped to make icons for their apps. It might be beneficial to explain how to use / install it as well.

**Comment by danrabbit** [comment]
It should probably be added to [this section](https://elementary.io/docs/human-interface-guidelines#color)

**Comment by Rishabh04-02** [comment]
I'd like to work on this.

**Comment by nel-co** [comment]
@Rishabh04-02 Have you started working on this already?

**Comment by Rishabh04-02** [comment]
@nel-co Not yet, was waiting for confirmation from the members. Should I do it now?

**Comment by nel-co** [comment]
@Rishabh04-02 Yeah you could, just asking because I was going to try and work on it.

**Comment by btkostner** [comment]
As far as I know, nobody else is working on it. You should be clear to work on it.

**Comment by nel-co** [comment]
Ok, awesome! I'll start on it now.

**Comment by btkostner** [comment]
@nel-co Thank you for the fix!

**Comment by nel-co** [comment]
@btkostner No problem!
