### ISSUE TITLE
feature request to support Keepassx

### ISSUE THREAD

**Issue by zqmuser** [elementary/website#1833]
### Expected behavior

Have Keepassx as one of the applications listed by default in the application manager.  I would recommend making it a supported, recommended application.

### Actual behavior

I had to install keepassx with apt-get.  It ran, but the background and menu names all went wonky (vertical stripes), although keepassx looked fine.  Same thing happened when running glxgears on a remote system.  

### Steps to reproduce the behavior

1. 
2. 
3. 

### System information

- **Operating system**:  Elementary OS downloaded 10/10/17
- **Operating system version**: 0.4.1
- **Browser**: NA
- **Browser version**: NA
- **Enabled Browser Extensions**: NA

**Comment by zqmuser** [comment]
Flakey video problems were on an old HP Pavilion dv2500 laptop.  AMD Turin 64 X2 TL-58, 2 GB memory.

**Comment by TraumaD** [comment]
This is the place to report bugs in the elementary website. Not a place for feature requests or OS bugs.
