### ISSUE TITLE
Link to UnixStickers from the store

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1834]
UnixStickers is now cutting us into their sales. Since we don't currently have a way to fulfill stickers, we should add a link in our store to redirect people looking for stickers

**Comment by cassidyjames** [comment]
I had a quick quick go at this in the inspector:
![screenshot from 2017-10-12 10-49-44](https://user-images.githubusercontent.com/611168/31508424-3e97c108-af3b-11e7-9aa6-aaf629773d24.png)
