### ISSUE TITLE
"Check Out" as opposed to "Checkout" button text on Cart page

### ISSUE THREAD

**Issue by rgb-one** [elementary/website#1839]
### Expected behavior

When visiting the Cart page the checkout button is labeled as "Checkout" or "Proceed to checkout" as opposed to "Check Out".

### Actual behavior

The checkout button on the Cart page has the text "Check Out" which has a different meaning from "Checkout".

### Steps to reproduce the behavior

1. Navigate to https://elementary.io/store/
2. Add an Item to the cart
3. Observe the checkout button text

### System information

- **Operating system**: 
- **Operating system version**: 
- **Browser**: 
- **Browser version**: 
- **Enabled Browser Extensions**:

**Comment by danrabbit** [comment]
This is expected and correct. "Checkout" is a noun. "Check Out" is a verbal phrase. Buttons are labeled with actions, so "Check Out" is the expected label.

**Comment by rgb-one** [comment]
"Proceed to checkout" would be a better description of what the button does as it navigates to the checkout view following the button click.

**Comment by danrabbit** [comment]
This logic would also lead to button labels like "Proceed to login" instead of just "Log In"

**Comment by rgb-one** [comment]
"Log in" as a link which leads to a page which has a "Log in" button would make a bit more sense if one takes this stuff too literally but hey, "Check Out" works. But one little thing though, "Check Out" or "Check out"? :p

**Comment by danrabbit** [comment]
Button labels are title case

**Comment by rgb-one** [comment]
Cool.
