### ISSUE TITLE
Update translation guide

### ISSUE THREAD

**Issue by png2378** [elementary/website#1848]
We need to update our translation guide.

- [ ] Because website and apps now translate on same platform, we need to merge the two parts into one
- [ ] Delete or update [outdated instructions](http://storage4.static.itmages.ru/i/17/1202/h_1512202311_7453371_aa619dfa22.png) that were applicable to Launchpad
- [ ] After that provide instructions for joining to translators team (for this translator must ask some admin in the chat)
- [ ] Links to Weblate documentation must be updated to the [latest version](https://docs.weblate.org/en/latest/) (instead of current hardcoded 2.15)
- Something else?

**Comment by btkostner** [comment]
Just a note, I am going to start locking weblate versions for a longer time. Upgrading it has been a point of pain and breakage. If there isn't a specific reason to upgrade, it probably will not happen. It might be better to keep the weblate version in the docs hard coded.

**Comment by ryonakano** [comment]
How about clarifying that there are some "won't support translation" pages, e.g. docs/getting-started? Some translators may ask or submit as a issue that they are not translatable.
