### ISSUE TITLE
Purchasing Download Error

### ISSUE THREAD

**Issue by explosive1111** [elementary/website#1858]
### Expected behavior

It would take me to a donate page

### Actual behavior

It just let me download it

### Steps to reproduce the behavior

1. Go to main page
2.  Go to purchase the item; click on any price
3.  It will just allow you to download; no donation page

### System information

- **Operating system**: Windows 
- **Operating system version**: Windows 10
- **Browser**: Microsoft Edge
- **Browser version**: 41.16299.15.0
- **Enabled Browser Extensions**: None

**Comment by btkostner** [comment]
Running edge on a Windows 10 vm doesn't seem to show any issues. What was the amount you entered after clicking "Custom"? Secondly, where there any errors in your console when viewing the page?

**Comment by coderlcd** [comment]
Could Not Replicate this issue when typing in various custom prices, or selecting the set donation amounts.

### System information
* **Operating system:** Windows
* **Operating system version:** Windows 10
* **Browser:** Microsoft Edge
* **Browser version:** 40.15063.674.0
* **Enabled Browser Extensions:** None

Updating Windows 10 now to test version Microsoft Edge 41+ to see if I can replicate this issue.

**Comment by coderlcd** [comment]
After Fully updating Windows 10, still unable to replicate this issue. 

### System information
* **Operating system:** Windows
* **Operating system version:** Windows 10
* **Browser:** Microsoft Edge
* **Browser version:** 41.16299.15.0
* **Enabled Browser Extensions:** None
