### ISSUE TITLE
Link to the elementary translators slack on the Get Involved page

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1859]
Now that slack has permanent self-invite links built in, maybe we should add a link for the translators slack on the get involved page.

I'd like to get feedback from our l10n community about if this would be helpful or generate unnecessary noise.

@leonardo-lemos @santileortiz ?

**Comment by png2378** [comment]
This would be useful, because currently for new translators there is no way to join the chat.

I expressed this idea here: https://github.com/elementary/website/issues/1848

**Comment by santileortiz** [comment]
Yes I agree this is a good idea. I haven't seen much activity in the translators slack, it could be very useful to allow people to join more easily.
