### ISSUE TITLE
Link to community Slack

### ISSUE THREAD

**Issue by TraumaD** [elementary/website#1860]
Would be nice to link to the Slack community channel. I feel like it falls into a similar category as the StackExchange or Reddit.

**Comment by larouxn** [comment]
Maybe we can add a Slack icon link up here?
<img width="963" alt="screen shot 2018-01-06 at 12 04 01" src="https://user-images.githubusercontent.com/1557529/34641963-c9c717b0-f2d9-11e7-9113-1e95326a4f53.png">

**Comment by p-shannon** [comment]
A slack icon definitely exists on font-awesome. Would be an easy fix. 
![image](https://user-images.githubusercontent.com/31411889/35060737-5269d934-fb8d-11e7-9583-404e008859de.png)


*Do we just go about and fix it, or do we wait for some sort of okay from the higher ups?*

**Comment by larouxn** [comment]
I think it's perfectly fine for us to go ahead and propose the change via a PR. 🙂

**Comment by coderlcd** [comment]
What is the url for the slack channel?

**Comment by p-shannon** [comment]
Reading up on [this reddit post](https://www.reddit.com/r/elementaryos/comments/25t7cg/where_to_talk_to_the_developers/) gives me pause as to whether or not this feature would be a good idea. I'm going to wait for a higher up to say something about it.

**Comment by TraumaD** [comment]
@p-shannon this post seems to talk more about getting in touch with the core team. The community slack is more akin to the stack exchange where the community talks amongst themselves to try and solve problems or talk about apps they're developing. Not necessarily to contact the core team (although some of them do hang out there every now and then.)

**Comment by p-shannon** [comment]
@TraumaD Thanks for that, I didn't know there was a distinction. In that case @coderlcd 's question still stands, as I don't know the elementary slack either.

**Comment by TraumaD** [comment]
The Slack is: elementarycommunity.slack.com

The self invite link is: http://bit.ly/2jb31NO

**Comment by coderlcd** [comment]
Thank you @TraumaD for the link! I will work on adding that to the site, if no one has claimed that yet.

**Comment by p-shannon** [comment]
@coderlcd  Nope, go ahead!

**Comment by coderlcd** [comment]
I have made the changes, but I am having some trouble getting the environment up and running on my machine to test the code on, anyone able to help/advice (I am on the slack channel if pm on there is easiest)? I read through the contribution guide, but still having some trouble. Thanks in advance! Look forward to contributing.

**Comment by TraumaD** [comment]
@coderlcd you might want to ask on the elementary website gitter as well.
https://gitter.im/elementary/mvp

**Comment by btkostner** [comment]
@coderlcd What kind of trouble? Console output if possible please.

**Comment by coderlcd** [comment]
Going off the documentation:

These can be most easily installed with this script:

```
sudo apt install php7.0-cli php7.0-curl php7.0-intl php7.0-json php7.0-sqlite php7.0-mbstring php7.0-xml composer &&
sudo apt install nodejs-legacy npm &&
npm install
```
Then inside the project directory, run npm run build && npm run start. Next, just navigate to localhost:8000 to view the site.

---

But I am running into a problem with the path and the .bash_profile. Tried a few different changes and all result in same error message.
```
sudo apt install php7.0-cli
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin/apt" (-1)
```

**Comment by btkostner** [comment]
Ah. I may not be the biggest help as I don't really develop on mac, but I can try. The error you are getting is because you are trying to run `apt`, but `apt` is not installed. It looks like you are trying to develop in a (Java?) virtual machine. Do you know what operating system it is running? Alternatively, do you have PHP installed locally? It might be easier to just run it outside a virtual machine. Sadly this might be a bit messier.

**Comment by coderlcd** [comment]
I can easily switch to a vm with linux. I know there is a section with the vagrant setup directly above this post, and i can use that to configure a virtual machine for me, but once I have that up and running, not sure how to get the website to display unless I send the display back to the host OS (which i will have to look into).

**Comment by larouxn** [comment]
I'm not aware of anyway you can use `apt` on macOS. I believe you'll want to use [Homebrew](https://brew.sh) to install things such as PHP and Node, as mentioned above.

**Comment by coderlcd** [comment]
I think ive got php, node, npm working. When navigating to localhost:8000 i get:

```
Warning: require_once(/Users/codered/Documents/ElementaryOSsite/website/_backend/vendor/autoload.php): failed to open stream: No such file or directory in /Users/codered/Documents/ElementaryOSsite/website/_backend/bootstrap.php on line 8

Fatal error: require_once(): Failed opening required '/Users/codered/Documents/ElementaryOSsite/website/_backend/vendor/autoload.php' (include_path='.:') in /Users/codered/Documents/ElementaryOSsite/website/_backend/bootstrap.php on line 8
```

**Comment by btkostner** [comment]
Nice! Almost there. You will need `composer` to install the PHP dependencies. If it's not installed already it should be `brew install composer`. Then just change directory to the `_backend` folder and run `composer install`.

**Comment by coderlcd** [comment]
Wow. Got it now! Huge thanks to @btkostner and @larouxn. Now back to making those changes! Will report back soon hopefully with a PR!

**Comment by btkostner** [comment]
@coderlcd Sweet! Let me know if you need any more help.

**Comment by coderlcd** [comment]
Now my addition of the Slack Icon with the Slack link shows on all pages, except when you hit the Developer button in the top navigation bar, it links to the Live Developer page (not a local page on my machine). How should i handle this? Will the change that I made correctly follow over to that developer.elementary.io page? Or is there additional work that I need to do on my end to make changes to that page as well?

**Comment by btkostner** [comment]
The developer page is part of houston, which is a separate project. It has a lot more complex of a setup, so you shouldn't worry about that page. I'll update it after it gets merged on the website.
