### ISSUE TITLE
elementary.io blocked in Russia

### ISSUE THREAD

**Issue by d1moncom** [elementary/website#1876]
104.28.5.44 and 104.28.4.44 in blocklist. Blocked by the state because of some other sites placed on IP. Check it out here http://blocklist.rkn.gov.ru/

Site and updates OS are not available. Please move your server to clean IP. Better to use for elementary.io individual IP, not connected with anothers questionable websites.

**Comment by cassidyjames** [comment]
@kodmgen we use CloudFlare for uptime and DDoS protection, which is apparently the IP blocked by Russia. That's extremely heavy-handed and problematic. I can have the team look into moving the site to a different IP block in CloudFlare, but that might also require upgrading to more expensive plan or something, which we don't have the resources for at the moment. 

OS updates are not served from elementary.io; we use Canonical's Launchpad infrastructure. If that is blocked, that is an entirely different (and possibly more troubling) issue. App updates from AppCenter are served via a subdomain at elementary.io, and I don't _think_ it's using CloudFlare but I can double check.

**Comment by kodmgen** [comment]
Thanks for answer! CloudFlare this is problem. A lot of IP addresses CloudFlare are blocked in Russia. In October 2015, 2831 IP addresses of CloudFlare were blocked. https://roskomsvoboda.org/13108/ I do not know how many today.

In Russia also love Elementary OS! :) A big thanks if you can somehow solve problem.

> sudo apt update
....
Пол:7 http://packages.elementary.io/appcenter xenial InRelease [5 894 B]                          
....

> ping packages.elementary.io
PING packages.elementary.io (104.28.5.44) 56(84) bytes of data.

**Comment by javidotpro** [comment]
Maybe we could offer to serve those updates through a different CDN like Buddy or Fastly?

**Comment by btkostner** [comment]
@javaguirre We use the free version of cloudflare for CDN because the cost for hosting that our self would be extreme. Unless we can get some other service to sponsor us, and do the massive amount of work it would be to switch our deployment / cdn ways, it's probably not going to happen.

@cassidyjames thoughts?

**Comment by javidotpro** [comment]
@btkostner @cassidyjames I can probably get you the support that you need to use a different CDN, I'm open to the idea of trying :-)

**Comment by cassidyjames** [comment]
@btkostner I saw the cost breakdowns you sent earlier. Let's chat about it privately and judge the cost/benefit to see if it would be prohibitive.

**Comment by lewisgoddard** [comment]
I think a more fundamental problem here is that Russia isn't exactly open-source friendly. They frequently block fairly benign tools. Telegram got blocked and that included Amazon Web Services and Google Cloud Platform IPs, which broke Mail.ru
