### ISSUE TITLE
to download a distribution without payment ;-)

### ISSUE THREAD

**Issue by Qvazarius** [elementary/website#1882]
_If you enter the amount_ **0,000 USD** _is download a distribution without payment_ ;-)

screenshot 0.00 USD  https://screenshots.firefox.com/QiurVcvomlZU0GkE/elementary.io
screenshot 0.000 USD https://screenshots.firefox.com/qbosbSTngNsvqIm9/elementary.io

**Comment by lewisgoddard** [comment]
Both of these let me download for free here. What localisation is that?

**Comment by png2378** [comment]
1. "Purchase elementary OS"
2. "Download elementary OS"

**Comment by lewisgoddard** [comment]
I understand what it says, but was wondering what localisation it was to see if it was somehow interfering with our number detection.

**Comment by sirkadirov** [comment]
@lewisgoddard it is russian. I checked it, but all works great...

**Comment by lewisgoddard** [comment]
Okay, I'm going to close this as incomplete since I cannot reproduce on elementary.io/ru/ and a definitive URL was not provided.
