### ISSUE TITLE
Switch developer docs to Meson

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#1885]
[All Aboard The Meson Future Hype Train](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e) explains that elementary OS will be switchting over from CMake to Meson. This means we'll also need to update the [getting started documentation](https://elementary.io/docs/code/getting-started)

> you can expect our documentation to be updated as soon as the first preview builds of Juno become available to developers.

From: [All Aboard The Meson Future Hype Train](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e)

I thought it might be interesting to have an issue for discussions and to track progress. 

Also see: https://github.com/elementary/debian-template/issues/3

**Comment by peteruithoven** [comment]
This might also be a good moment to simplify the icon files. Instead of them having to be in seperate directories, each with the full project name we could rename them during installation using something like:

```
icon_sizes = ['16', '24', '32', '48', '64', '128']

foreach i : icon_sizes
    # Installing icons using configure_file to rename the output file
    configure_file(
        input : join_paths('icons', i + '.svg'),
        install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', i + 'x' + i, 'apps'),
        output : meson.project_name() + '.svg',
        configuration : configuration_data()
    )
endforeach
```

I'm using [configure_file](http://mesonbuild.com/Reference-manual.html#configure_file) instead of [install_data](http://mesonbuild.com/Reference-manual.html#install_data) because install_data can't yet rename the file during installation, see: https://github.com/mesonbuild/meson/issues/1487

**Comment by cassidyjames** [comment]
We should really revisit this now that we're all aboard the Meson hype train.

**Comment by danrabbit** [comment]
The big blocker here is no support for Meson in debhelper in Loki
