### ISSUE TITLE
PAYEMENT ERROR 

### ISSUE THREAD

**Issue by Subfly** [elementary/website#1890]
### Expected behavior

I bought elementary for 3 times but İt didn't accept the cvc but it got the money 3 times. What should I need to do now?

### Actual behavior

As I said above, after checking for payement, it didn't accept the cvc code but got the mopney from the card.

### Steps to reproduce the behavior

1. Payement
2. Cvc prompt
3. Checking

### System information

- **Operating system**: Win 10
- **Operating system version**: ?
- **Browser**: Chrome
- **Browser version**: 63.0.3239.132
- **Enabled Browser Extensions**:McAfee

**Comment by fabianthoma** [comment]
Please contact payment elementary.io directly via email to resolve this issue.
