### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by iBvishal** [elementary/website#1908]
### Expected behavior

Link to Security notices is broken in the main page. 

### Actual behavior

It must take me to the security security notices available for public viewing.

### Steps to reproduce the behavior

1. open https://elementary.io/
2. scroll to the bottom of the page 
3. click  on security notices under safe and secure coloumn.

### System information

- **Windows10/64bit**
- **version 1709 for x64-based Systems (KB4090913)**
- **Google Chrome** 
- **Version 64.0.3282.186 (Official Build) (64-bit)** 
- **Momentum, AdBlock, Google Dictionary**

**Comment by chauhankiran** [comment]
Facing `404 Not Found` error while clicking on link.
