### ISSUE TITLE
Unclear what to do if your language has no translation admin

### ISSUE THREAD

**Issue by SamMorrowDrums** [elementary/website#1932]
### Expected behavior
The translation guide should provide some info (and possibly another link to the slack chat for translators), on how to administrate a language that has no support or admins currently.

https://github.com/elementary/website/blob/master/docs/translation-guide.md

Additional context: 

Even if the user is not able to admin their language, there should be some kind of process / communication so we don't just leave things hanging.

### Actual behavior

User has no clue what to do if submitting a translation is just left in limbo

https://elementaryos.stackexchange.com/questions/15222/translating-elementary-weblate-issues

### Steps to reproduce the behavior

1. visit: https://elementary.io/docs/translation-guide#translation-guide

**Comment by ryonakano** [comment]
This is mentioned here: https://github.com/elementary/website/issues/1848#issue-278667400

**Comment by SamMorrowDrums** [comment]
Perfect. Will close!
