### ISSUE TITLE
PHP 7.0 is not in the repository.

### ISSUE THREAD

**Issue by jwinnie** [elementary/website#1939]
The development instructions instruct you to install PHP7. This works in Ubuntu 16.04 (elementaryOS Loki), but will not work in Ubuntu 18.04 (elementaryOS Juno) as the PHP7 package was replaced by PHP7.1.

**Comment by lewisgoddard** [comment]
I think at that point we might as well instruct people to use PHP 7.2, I already am.

**Comment by btkostner** [comment]
Honestly, I just install php at this point and trust that it works. Does the ubuntu repos have a `php` package that installs the latest?

**Comment by lewisgoddard** [comment]
:man_shrugging:
