### ISSUE TITLE
gulp-util is deprecated

### ISSUE THREAD

**Issue by jwinnie** [elementary/website#1942]
`npm` tells me `gulp-util` should not be used.

More information:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by lewisgoddard** [comment]
I don't think this is something we use, specifically. I think some library we use to build uses this and would need to be updated upstream. I guess step 1 is figure out what things are using it.

**Comment by jwinnie** [comment]
Here's the output of `npm ls gulp-util`:
```
├─┬ gulp-imagemin@3.4.0
│ └── gulp-util@3.0.8 
└─┬ jpegtran-bin@3.2.0
  └─┬ bin-build@2.2.0
    └─┬ download@4.4.3
      └─┬ gulp-decompress@1.2.0
        └── gulp-util@3.0.8  deduped
```
Looks like `gulp-imagemin` and `jpegtran-bin` are to blame.

**Comment by jwinnie** [comment]
Since this is an upstream issue and `gulp-util` is still very widely used, I am going to close the issue.
