### ISSUE TITLE
Live reload?

### ISSUE THREAD

**Issue by jwinnie** [elementary/website#1943]
I am used to developing in Django, which automatically updates the CSS when using the development server. It makes developing much faster. Is there a way this can be implemented in NPM/PHP?

**Comment by btkostner** [comment]
There is an undocumented gulp task that will watch for css and image changes and rebuild. It will not reload the browser though. Run `npx gulp watch`.

**Comment by jwinnie** [comment]
Maybe it should be documented.

**Comment by btkostner** [comment]
1ddac104108c12e2c1161ef399a25e8a764440c8
