### ISSUE TITLE
Add translation link to 'Getting Started' page

### ISSUE THREAD

**Issue by btd1337** [elementary/website#1965]
The page https://github.com/elementary/website/blob/master/docs/code/getting-started.md doesn't available to translate.

**Comment by btkostner** [comment]
We made the decision to not translate the code docs. If I remember correctly it was due to the fast moving docs, and how hard it is to translate.

Slightly related to:
https://github.com/elementary/website/issues/1684
https://github.com/elementary/website/issues/1757
