### ISSUE TITLE
FontAwesome not showing

### ISSUE THREAD

**Issue by macarena** [elementary/website#1967]
### Expected behavior

Some icon character should appear after each link on footer of developer.elementary.io

### Actual behavior

A missing character is displayed.

### System information

- **Browser**: Firefox on Ubuntu, Chrome on Mac and Chrome on Android.

![captura de tela 2018-05-31 as 01 45 30](https://user-images.githubusercontent.com/79822/40761953-745cdfe6-6474-11e8-86c2-3eaf64b2b108.png)
![image 2018-05-31 01 44 54](https://user-images.githubusercontent.com/79822/40761954-747c0a88-6474-11e8-82b9-3f4de0699fff.jpg)

**Comment by cassidyjames** [comment]
It looks like we're trying to use Font Awesome 5 Pro in the CSS, but not loading the proper CSS like we are on the main site.

**Comment by cassidyjames** [comment]
Moved to the right repo at https://github.com/elementary/houston/issues/623
