### ISSUE TITLE
Some elementary OS built-in apps don't exist in open-source page

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1970]
### Actual behaviour

![screenshot from 2018-06-13 23-48-09](https://user-images.githubusercontent.com/26003928/41359376-5781dc68-6f65-11e8-94e6-87b17e5f204f.png)

It seems that some elementary OS built-in apps don't exist in [open-source page](https://elementary.io/open-source):

- AppCenter
- Calculator
- Screenshot

### Expected behaviour

We should add the three apps above in that page.

### Steps to reproduce the behaviour

1. Open [https://elementary.io/open-source](https://elementary.io/open-source) and confirm that the three words above don't exist.

**Comment by 5nai3r** [comment]
I would love to work on this :+1: 
i'm trying to add those links

**Comment by ryonakano** [comment]
Thank you, @5nai3r!!
