### ISSUE TITLE
dazzling shared dirs

### ISSUE THREAD

**Issue by shm007g** [elementary/website#1980]
### Expected behavior
can't see shared dirs names clearly.
 
![image](https://user-images.githubusercontent.com/16999665/42143066-bb5d9806-7de5-11e8-8808-69f009f7e897.png)

### Steps to reproduce the behavior

1.  I create a shared dir through vmware,  then link this dir to home dir.
2.  Then i ls this shared dir.. This really hurt my eyes. I can't see anything about this dir name!!

### System information

-  any windows 10 with vmware install eos

**Comment by btkostner** [comment]
Closing in favor of: https://github.com/elementary/terminal/issues/278
