### ISSUE TITLE
Update the description and screenshots in docs/installation

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1983]
Related #1850.

Now that Rufus is version 3.1 and Etcher is version 1.4.4, so their UI and how to operate them are a little different from them in our website. I think it's time to review and update the description and screenshots in docs/installation.

**Comment by 5nai3r** [comment]
I'll give try and  change Rufus screenshot and steps to operate

**Comment by 5nai3r** [comment]
For the checksum icon i need to give it a `margin:0 0 0 0;` i wanted to ask if i should creat a class for this element or there is an existante css class with  `margin:0 0 0 0; `  that i can use.

**Comment by btkostner** [comment]
I _think_ the inline class should be good

**Comment by 5nai3r** [comment]
@btkostner 
the inline class contain this 
```
div.inline, img.inline {
    display: inline-block!important;
    vertical-align: middle;
}
```
and the margin in the checksum icon is the result of this 
```
.docs img {
    margin: 1.5em auto;
}
```
i'm wondering if i should create a class for checksum icon and give it margin 0  or create a general class maybe .zero-margin

**Comment by 5nai3r** [comment]
Thank you @btkostner
And about **Etcher** they have a cool GIF in in their website, could we use it ? or  it is better to use a normal static image and keep the website lightweight

**Comment by btkostner** [comment]
I would say use your best judgement. If it's useful and explains something well, I see no problem in using it on the site.
