### ISSUE TITLE
Does not exist alert icon

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1987]
![screenshot from 2018-07-11 22-07-26](https://user-images.githubusercontent.com/26003928/42575550-c08c30c6-855b-11e8-9403-459b3f37b3a2.png)

IIRC, there was an alert icon beside this sentence. Where did it go?

**Comment by ryonakano** [comment]
@lewisgoddard I would like to work on this. 

> modify the font-size to fit.

How can I set the size? Do I just set the size in the class (e.g. `<i class="warning far fa-exclamation-triangle fa-3x"></i>`)? Or another way?

**Comment by lewisgoddard** [comment]
I think we use something like `fa-3x` or `fa-2x` somewhere else, so probably like that.

**Comment by lewisgoddard** [comment]
We definitely use `fa-128` somewhere, so a fixed size might be better.

**Comment by ryonakano** [comment]
![screenshot from 2018-07-17 11-29-11](https://user-images.githubusercontent.com/26003928/42793357-bd6484e0-89b4-11e8-80d2-53bd8f1a01b4.png)

@lewisgoddard I assigned 64px as a test. Do you think this size is appropriate?

**Comment by lewisgoddard** [comment]
Yes, do you have a branch for that?

**Comment by ryonakano** [comment]
@lewisgoddard Yes. May I create a pull request with that branch?

**Comment by lewisgoddard** [comment]
Yes please.

**Comment by ryonakano** [comment]
@lewisgoddard I've created [a PR](https://github.com/elementary/website/pull/2005) for this. I would appreciate it if you could review it.
