### ISSUE TITLE
The icon in the getting-started is not Code's one

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1991]
![screenshot from 2018-07-15 20-55-28](https://user-images.githubusercontent.com/26003928/42733732-906ebf4e-8871-11e8-9067-c6f58a537621.png)

The icon in the [getting-started](https://elementary.io/ja/docs/code/getting-started#code) is not Code's one. It is still Scratch's one.

**Comment by btkostner** [comment]
This was mentioned somewhere else as well. The icon shown is the theme icon which is a git submodule. We will need to copy the code icon from it's repo to this one and update the urls as needed.

**Comment by cassidyjames** [comment]
Fixed in 9c760f55f477630cbe86a317cd11ee0d90f4536e

**Comment by ryonakano** [comment]
Thank you very much!! :smile:
