### ISSUE TITLE
Move to Hack/HHVM

### ISSUE THREAD

**Issue by jwinnie** [elementary/website#1995]
Many PHP websites nowadays are moving to Hack and HHVM because it is supposedly faster and more  maintainable.
https://hacklang.org/
Not much work is required to convert: https://docs.hhvm.com/hack/tools/hackificator

**Comment by peterthomashorn** [comment]
When Hack was published in 2014 there were significant advantages. I challenge those arguments nowadays, especially with PHP 7.1 and newer. After working the last six years with PHP and being excited myself about Hack (back then) I would not advocate such effort. PHP has a much larger user base (so potential contributors) and simplifies operations (you can throw it on small shared hosting service). I wonder where that maintainability argument is coming from. In this case I guess it is influenced much more by other factors than using PHP or Hack.

**Comment by btkostner** [comment]
Considering we are running on latest (or close to) PHP 7, and have very low performance requirements, I don't consider this worth the time to port. Also, one of the biggest advantages of having this in regular PHP is it's pretty easy for new contributors to change the code.
