### ISSUE TITLE
A visual bug on the main page

### ISSUE THREAD

**Issue by brigazvi** [elementary/website#1997]
![bug](https://user-images.githubusercontent.com/37640970/42853238-e21ae07a-8a3d-11e8-8f8b-b2e1be6a86a4.gif)

- **Operating system**: Windows 10 pro
- **Operating system version**: 1803
- **Browser**: Google Chrome
- **Browser version**: 67.0.3396.99 
- **Enabled Browser Extensions**: Google Docs Offline, Docs, Sheets, Slides.

**Comment by cassidyjames** [comment]
@brigazvi do you have your zoom set to a different level?

**Comment by brigazvi** [comment]
@cassidyjames  No. It happens at every level.

**Comment by jwinnie** [comment]
The slingshot thing is very buggy, no matter what resolution or browser. May I ask why you don't just use a GIF?

**Comment by btkostner** [comment]
We use the animation because it's translatable, smaller in size, and a smoother.

**Comment by jwinnie** [comment]
There’s no easy way to translate images in Weblate?

IMO the cost is more than the benefit for this feature.

**Comment by brigazvi** [comment]
@cassidyjames I understood what the problem was:
Font size was set in the Browser to Large. When set to Medium, the problem is resolved.

**Comment by davidsaulrodriguez** [comment]
Glad you solved the issue @brigazvi. But shouldn't this issue be closed now?
