### ISSUE TITLE
Update Stack Exchange URLs which use old application codenames

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1998]
I suppose we should change Stack Exchange URLs which use old application codenames and update the links to them in support.php: [Snap](https://elementaryos.stackexchange.com/questions/tagged/snap) --> Camera, [Maya](https://elementaryos.stackexchange.com/questions/tagged/maya) --> Calendar, [Noise](https://elementaryos.stackexchange.com/questions/tagged/noise) --> Music.

**Comment by lewisgoddard** [comment]
All of these have been done on StackExchange.

**Comment by ryonakano** [comment]
Confirmed. Thank you @lewisgoddard !!

**Comment by ryonakano** [comment]
Oh we should reflect these changes to the website.
