### ISSUE TITLE
Supported & Unsupported hardware

### ISSUE THREAD

**Issue by jwinnie** [elementary/website#2001]
elementary should maintain a list of computers and what known bugs there are, if any.

This list could be shown on the installation guide or before download so people know what they’re getting in to.

Later on, it could almost become a to-do list for fixing hardware compatibility bugs

**Comment by cassidyjames** [comment]
We've discussed this a lot in the past, but it always comes down to: maintaining a list of supported hardware is just too insurmountable, as different firmware and hardware revisions, kernel versions, etc. can greatly change a piece of hardware's compatibility with Linux and elementary OS. A community-driven effort to document things would be welcome, but it's not something we can commit to officially.
