### ISSUE TITLE
Include elementary svg logo to translation

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#2002]
### Actual behavior

![screenshot from 2018-07-20 10-48-04](https://user-images.githubusercontent.com/26003928/42978973-c4dd65d6-8c0a-11e8-8788-b72bea9c2670.png)

![screenshot from 2018-07-20 10-48-29](https://user-images.githubusercontent.com/26003928/42978977-c84e2372-8c0a-11e8-9815-2f65d166e993.png)

At the present, we have these two sentences above which include elementary svg logo. They are not included to translations and just only "Get Support for" and "Thank You for Downloading" are translatable.

This causes the order problem: some languages have to bring the svg "elementary OS" to the different position of the sentence, e.g. in Japanese the translation of "Get Support for elementary OS" is actually "elementary OS のサポートを得ましょう" and in this case, the svg "elementary OS" have to come the beginning of the sentence. But since the svg is not included to translation, the svg comes to the last and can't translate this string correctly.

### Expected behavior

If possible, please include elementary svg log to the translation and make it possible to insert the logo to anywhere of the translation by using "%s" or something like that string. Then we can translate correctly "%s のサポートを得ましょう" or something like that.

**Comment by ashishgeeky** [comment]
Hi. When I downloaded zip file of website and tried to run index on xampp Linux (elementary os), it gives a php error relating to require_once bootstrap.php in _backend. I am new to open source. I have done competitive programming a lot but now I want to contribute to open source as well. I know PHP and CSS so i might be able to solve it. Please help me on how to fix this issue so i can modify code on my system and i can check it.

**Comment by btkostner** [comment]
That probably means you are missing PHP dependencies. Did you install `composer` and install the PHP dependencies?

https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md#simple-php-server

Also, please open up another issue instead of commenting on an unrelated issue.

**Comment by ryonakano** [comment]
![Screenshot from 2020-09-20 16-59-58](https://user-images.githubusercontent.com/26003928/93706595-bd543280-fb62-11ea-90ff-ea1b5b2a3bdc.png)

It seems to be fixed by removing the svg, closing.
