### ISSUE TITLE
Code did not come with the OS.

### ISSUE THREAD

**Issue by Dartomic** [elementary/website#2003]
The getting-started guide says that the app called, "Code," comes with elementary OS. I just installed the OS, and do not appear to have it. I entered the word "code" into the terminal, but the app is not on my system. 

I see an application called "Scratch," that has the same icon that the getting-started guide displays for "Code." Is "Scratch" the new name for "Code," is "Code" now a separate application, or are these instructions for the newest release of elementary OS, which I read lacks applications in the store?

**Comment by cassidyjames** [comment]
@Dartomic the getting started guide is targeted to app developers, who are encouraged to start building on elementary OS Juno. Juno comes with Code. Scratch is the equivalent version in Loki, and should be able to be used.

**Comment by Dartomic** [comment]
Thanks for the reply, sorry that I saw this late. I figured that out when I installed Juno lol.
