### ISSUE TITLE
The text "This is a development site." in docs/*.md has unneeded underline

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#2011]
### Expected behavior

![screenshot from 2018-07-26 20-33-28](https://user-images.githubusercontent.com/26003928/43260416-6027e198-9114-11e8-9503-b30d6bb5337b.png)
The text "This is a development site." in docs/*.md (HIG, Translation Guide, etc) should have same style with the one in the index.php: it should not have the underline.

### Actual behavior

![screenshot from 2018-07-26 20-33-18](https://user-images.githubusercontent.com/26003928/43260405-5a98447a-9114-11e8-8424-4a17fcd2260e.png)

The text "This is a development site." in docs/*.md has wrong style: it has unneeded underline.

### Steps to reproduce the behavior

1. Build and run the website on local as [instructed](https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md)
2. Open localhost:8000
3. After that, open localhost:8000/docs/installation

### System information

- **Operating system**: elementary OS
- **Operating system version**: Juno Beta1
- **Browser**: Firefox
- **Browser version**: 61.0.1 (64bit)

**Comment by jbull328** [comment]
Pr #2068
