### ISSUE TITLE
Update design proposal instructions

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2024]
I.e. don't tell people to use Blueprints at https://elementary.io/docs/code/reference#proposing-design-changes. We should update it to a GitHub-based workflow.

**Comment by RMcNeely** [comment]
Is there anything specific that should be in this section or the standard, we use Github, file an issue, pull request etc?

**Comment by cassidyjames** [comment]
We use GitHub Projects to track organization-wide design efforts, so there may be something there. But generally, the Needs Design issues are a place to start, and yeah, filing issues/PRs is the way to go.
