### ISSUE TITLE
Update docs to not include .desktop in appstream id

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#2032]
I've gotten the following error after attempting to publish the app:
> Appstream tests fail
> "id" field should be "com.github.peteruithoven.resizer"

I'm assuming this is about the appdata.xml file, the Getting Started however still contains an example with `.desktop`:
https://elementary.io/docs/code/getting-started#appdata

**Comment by btkostner** [comment]
The appstream spec changed to not include the `.desktop` part. We need to update our docs.
