### ISSUE TITLE
Add existing coverage to press page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2041]
Split from #2039. Once #2040 is merged, we should add a grid of existing coverage of some sort so press knows where we've been covered.

**Comment by lewisgoddard** [comment]
Is this just going to be a list of news sites that have covered elementary?

**Comment by cassidyjames** [comment]
@lewisgoddard it would probably be best to have logos and curated excerpts, like on the home page (but more extensive).

**Comment by Fatih20** [comment]
@lewisgoddard I'm assuming this is a dormant issue but if you got anything going on I'd be interested in helping.

**Comment by rajatgupta24** [comment]
Hey @lewisgoddard, I saw this is the only issue in the to-do section of the milestone, can I work on this issue?
