### ISSUE TITLE
ams3.dl.elementary.io uses an invalid security certificate.

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#2050]
I tried downloading the elementary Beta though the "Download via HTTPS" button, but on Firefox this shows me the following "Your connection is not secure" page:
![screenshot from 2018-09-11 00 29 47](https://user-images.githubusercontent.com/523210/45327929-ebf1a880-b559-11e8-8f12-5b522bc6898e.png)

**Comment by cassidyjames** [comment]
Thanks for the report @peteruithoven! It looks like the LetsEncrypt autorenew didn't, well… autorenew. We're aware and looking into it!

**Comment by lewisgoddard** [comment]
It appears that the Let's Encrypt auto renewal on our download servers broke at some point in the last 90 days and they haven't been renewing since then. They've been manually done for now and normal service has been restored. I will track internally with the web team to get the automation back.

**Comment by peteruithoven** [comment]
Damn you guys are quick, thanks!
