### ISSUE TITLE
Mention app development on Get Involved

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2054]
App developers have told me that making apps is another way they contribute to elementary OS. We've also seen core contributors start off as app developers, and it seems to be a good way to get practice and prove their work before they express interest in contributing to the OS itself.

We should mention app development as another way to contribute on the Get Involved page, and link it to the Developer site.

**Comment by bolariin** [comment]
@cassidyjames there is a [desktop](https://elementary.io/get-involved#desktop-development) section on the website which slightly mentions apps. Would you like this to link to the developer site?

**Comment by cassidyjames** [comment]
@bolariin I think app development might be considered its own thing, but I haven't thought super hard about where to put it.

**Comment by Asuza** [comment]
What if App development is included in the Desktop section, or combined into it? I'm imagining something like:

**App & Desktop Development**
Our desktop environment and all its apps are built using Vala, GTK+, Granite, and a number of other open libraries. We host our desktop code on GitHub, a free service for open source projects. If you've never built an elementary OS application or developed for elementary OS before, we recommend you check out our Getting Started guide. Learn More

**Comment by danrabbit** [comment]
This has been fixed
