### ISSUE TITLE
Making Responsive for smaller devices

### ISSUE THREAD

**Issue by Rohit280297** [elementary/website#2061]
### Expected behavior

the website doesnt seem responsive on smaller devices. The items in the navigation bar go out of the screen on smaller devices.

### Actual behavior

Describe what actually happened, being specific about how this differs from your expectations.

### Steps to reproduce the behavior

1. 
2. 
3. 

### System information

- **Linux: Ubuntu**: 
- **16.04**: 
- **Google Chrome**: 
- **Browser version**: 
- **Enabled Browser Extensions**:

**Comment by Rohit280297** [comment]
Can this task be assigned to me ? I would be glad to work on this.
Thanks

**Comment by cassidyjames** [comment]
Hey @Rohit280297. The current design is intentional, as the menu items scroll horizontally while the rest of the page adapts. This was chosen over using a "hamburger" menu that hides all items by default, or wrapping which takes a ton of space at the top of the page.

**Comment by Rohit280297** [comment]
Okay thanks...:-)

**Comment by cassidyjames** [comment]
That said, if you have another design suggestion, I'd love to hear it! I know the horizontal scrolling navigation isn't super conventional, and it's very possible that we could do better.
