### ISSUE TITLE
Remove Google+ link

### ISSUE THREAD

**Issue by micahilbery** [elementary/website#2074]
With Google+ shutting down soon we will probably want to remove the Google+ icon and links from the nav bar.

**Comment by harrison-broadbent** [comment]
hey I'll give this one a go

**Comment by harrison-broadbent** [comment]
just gave it a shot, one of my first requests so I hope everything is ok! heres the link to it- #2076

**Comment by ryonakano** [comment]
This issue should be closed since the PR is merged
