### ISSUE TITLE
Selected text in over-image areas should be readable when selected.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#2079]
### Expected behavior

Selected text is readable, regardless of where it is.

### Actual behavior

![image](https://user-images.githubusercontent.com/831389/47045227-359d6680-d18a-11e8-84b3-a7d1f35de510.png)

**Comment by adoi** [comment]
Hey @lewisgoddard I am willing to contribute to this issue. Assign it to me if possible.
