### ISSUE TITLE
Visual failures in Chrome/Chromium

### ISSUE THREAD

**Issue by MauricioFIUBA** [elementary/website#2080]
It's seems that are a ton of wierd failure with Chrome/Chromium in the mobile and desktop version of the elementary's website.

Here are some examples:

The website in Firefox:

![imagen](https://user-images.githubusercontent.com/31808401/47055510-16083d00-d18e-11e8-84be-f8e59627e24d.png)

![imagen](https://user-images.githubusercontent.com/31808401/47055736-4e5c4b00-d18f-11e8-9d99-a7985c352206.png)

The website in Chromium:

![imagen](https://user-images.githubusercontent.com/31808401/47055423-bdd13b00-d18d-11e8-844a-1825e9579c0a.png)

![imagen](https://user-images.githubusercontent.com/31808401/47055724-3edd0200-d18f-11e8-8470-4da31d07d9a2.png)

Click in Code (Firefox):

![imagen](https://user-images.githubusercontent.com/31808401/47055530-359f6580-d18e-11e8-8f8b-6fc4bbd93ef6.png)

Click in Code (Chromium):

![imagen](https://user-images.githubusercontent.com/31808401/47055382-8e223300-d18d-11e8-9172-82c423dfeba8.png)

Describe what actually happened, being specific about how this differs from your expectations.

### Steps to reproduce the behavior

1.  Open the website in Chrome/Chromium. 

### System information

On the desktop:

- **Operating system**:  Elementary OS.
- **Operating system version**:  0.4.1 Loki.
- **Browser**:  Chromium.
- **Browser version**: 69.0.3497.81.
- **Enabled Browser Extensions**: none.

On the mobile:

- **Operating system**:  Android.
- **Operating system version**:  8.0 (Oreo).
- **Browser**: Chrome.
- **Browser version**: 69.0.3497.100.
- **Enabled Browser Extensions**: none.

**Comment by peterthomashorn** [comment]
I have similar behaviour in Safari on macOS Mojave. It appears like the notebook screen is responsively adapted to the browser viewport.

<img width="2444" alt="screenshot 2018-10-17 at 09 35 08" src="https://user-images.githubusercontent.com/7641832/47069732-fa358300-d1ef-11e8-9122-1863ebc73bc2.png">
<img width="1005" alt="screenshot 2018-10-17 at 09 35 14" src="https://user-images.githubusercontent.com/7641832/47069734-fa358300-d1ef-11e8-821c-d45e3f9e4f55.png">

**Comment by gugacavalieri** [comment]
Same here in Chrome Version 69.0.3497.81 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4624484/47086214-46cc8e80-d1ef-11e8-8719-09a8d477d1b7.png)

**Comment by lewisgoddard** [comment]
None of these issues affect my Chrome, however Chrome does seem to more aggressively cache than other browsers and not honour our forced expiry with the new deployment. I would recommend trying <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> to force a reload without the cache and these issues should be resolved.
