### ISSUE TITLE
Multiple overlaying showcase issue in Firefox, Edge

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#2081]
There is an issue with the code showcase:
![screenshot from 2018-10-17 14 57 37](https://user-images.githubusercontent.com/523210/47087749-1996d500-d21d-11e8-8754-8f91618ccebe.png)
The other showcases work fine. 

This happens in Firefox. It seems to work fine in Epiphany and Chromium

From Twitter: https://twitter.com/aobhgoleor/status/1052541777360642048/photo/1

**Comment by peteruithoven** [comment]
Ah I see. This only happens when you use an url that includes a hash, like [#showcase-code](https://elementary.io#showcase-code) / [#showcase-terminal](https://elementary.io#showcase-terminal). When visiting https://elementary.io and just navigate through the showcases there is no issue.

**Comment by ncbaihly** [comment]
This seems to be working fine in Firefox 108.

**Comment by lewisgoddard** [comment]
I can only make this happen in Firefox and Edge by letting the page load and then trying to load the page again with the hash. We don't even expose these hashes any more so I think we can call this resolved.
