### ISSUE TITLE
Developer page still refers to Juno Beta 2 release

### ISSUE THREAD

**Issue by Adarsh-Barik** [elementary/website#2086]
### Expected behavior

Now that Juno is released, it should refer to the released version. 
### Actual behavior

Developer page refers to Juno Beta 2 release. 

![el_dev_issue](https://user-images.githubusercontent.com/1428298/47197014-a92da800-d331-11e8-9cea-e5e61bf8ae99.png)

1. "Download via HTTPS" button returns 404 error.
2. "Download via Torrent" redirects to a link which contains reference to Beta 2 release. 
### Steps to reproduce the behavior

1. Go to https://elementary.io/
2. Click on Developer button at the top, it redirects to https://developer.elementary.io/
3. Scroll down until you see above screenshot.

### System information

- **Operating system**: elementary OS 
- **Operating system version**: 0.4.1 Loki
- **Browser**: Chrome
- **Browser version**:  70.0.3538.67

**Comment by cassidyjames** [comment]
Strange, https://github.com/elementary/houston/pull/657 was merged for this reason. It might not have been deployed. Checking with @btkostner.

**Comment by btkostner** [comment]
Fixed
