### ISSUE TITLE
Inelegant handling of Loki "download again" links

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2089]
Right now if someone who purchased Loki clicks the "Download Again" link in their email, they just get dumped to the Juno page and get asked to pay again, but without any context. This comes off as something is broken, and they cannot download the previous version they already paid for. Consequently, we're receiving emails from customers who are unable to get at their download.

**Comment by cassidyjames** [comment]
If someone paid and clicks on the link to redownload the thing they already paid for, I think we should offer it back up to them regardless of a new version being released. But I'm open to other ideas.

Something we could do could be to have a sort of "new release" dialog or something, that lets users know there's a new release, and that they can pay-what-they-want for that, or download the old version they already paid for.

**Comment by btkostner** [comment]
@cassidyjames 	that's going to be a lot harder considering every piece of code on the website assumes there is a single release, and just pulls it from the config file...

**Comment by lewisgoddard** [comment]
It shouldn't be too hard to implement a "releases" to replace "release" and just have the latest of each major supported version. We'd only need the latest build of Loki and Juno, and it's barely referenced outside the homepage.

**Comment by btkostner** [comment]
But it's also used for sending emails, checking os email links, JS payments, etc.

**Comment by rhyseli** [comment]
I don't know about handling previous release downloads, but perhaps we could send to a download page without the payment method?
