### ISSUE TITLE
How test Elementary OS in Acer Aspire

### ISSUE THREAD

**Issue by wylnux** [elementary/website#2092]
### Expected behavior

Describe what you expected to happen.

I need probe this OS/elemenraty if is really to use in my classroom end for the community user.
for users who do not use a computer daily, that is visually friendly.

Please how i download for test.

### Actual behavior

Describe what actually happened, being specific about how this differs from your expectations.

### Steps to reproduce the behavior

1. 
2. 
3. 

### System information

- **windows**: 
- **Windows 8.1**: 
- **google chrome**:

**Comment by cassidyjames** [comment]
First, you can check the recommended system specs at https://elementary.io/docs/installation#recommended-system-specifications

Second, you can choose a "custom" payment of $0 to download the ISO. Follow the instructions at https://elementary.io/docs/installation to get the OS onto a flash drive and bood from it, then you can choose to try the OS live before installing. Note that this should be used as a rough estimate of the installed experience, as some things (like AppCenter and some performance) may not be the same between running from a flash drive versus your hard drive.
