### ISSUE TITLE
Browser caching on Chrome breaks website

### ISSUE THREAD

**Issue by jwinnie-the-great** [elementary/website#2093]
Looks like Chrome is caching the CSS/JS and it is not being updated when the website is updated. I would recommend cache fingerprinting  (use `main.0fklh924sd834.css` instead of `main.css`).

**Comment by btkostner** [comment]
We would need to create a manifest file, use PHP to read that file on every page render, and rewrite the script tags. Ideally we would do this with all assets. In general, this is kinda a pain to do with what we are currently using. I would love to see most of this site go JavaScript with a build step that handles all of this for us.

**Comment by jwinnie** [comment]
I am trying to create a PR for this. On the PHP end we could make a function like `get_asset`, which takes the asset name and adds the MD5 hash to it (in: `main.js`, out: `main.398f9df83.js`). On the JS end we could add (or write, it's not that hard) a Gulp plugin that renames all the assets by appending the hash. Then we would just need to replace all the `<script>`, `<img>` & `<link>` tags with `<?php get_asset ?>` calls.

This is pretty much how Django/Rails handles it.

**Comment by lewisgoddard** [comment]
Seeing as we already use per-page CSS and JS through a section of PHP, this _shouldn't_ actually be that hard.

**Comment by btkostner** [comment]
Moving to High priority as we are getting browser script caching errors that prevent people from buying elementary.

**Comment by lewisgoddard** [comment]
CSS is all built in Gulp but JS is webpack. This might need two separate manifests, although the PHP should be able to handle that automatically with one function.

**Comment by RMcNeely** [comment]
I cannot figure out why cache busting does not seem to work for CSS in Gulp. I could rework the CSS to also be done by webpack and it would leverage the same approach, but I wanted to check before I change the whole build process.

**Comment by lewisgoddard** [comment]
CSS moving to webpack would be fine so long as we had feature parity.

**Comment by RMcNeely** [comment]
Any objections to updating to Webpack 4?

**Comment by btkostner** [comment]
@RMcNeely nope!
