### ISSUE TITLE
Integrate Houston: Before You Publish info

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#2111]
Shouldn't the information on the following page on the Houston wiki be included on the website?
https://github.com/elementary/houston/wiki/Before-You-Publish
Maybe we could add it as a dedicated Before you Publish page? Or maybe "AppCenter requirements" would be a clearer name?

I find that people are still confused what they can publish to the AppCenter. Questions like other languages, command line only applications. 
The before you publish wiki page answers some of these questions.

**Comment by btkostner** [comment]
Yes this should. I think the main reason it hasn't been yet is because of our long term plans. Eventually we want our docs to be a part of houston where we can have them a bit more personalized. I see no reason this should stop us from putting this in the developer docs now though.

**Comment by peteruithoven** [comment]
If they are a part of Houston they would only appear after people attempt to publish or run Houston CI right? I think we also need some of this information on our website for people who want some answers before they start coding.

**Comment by btkostner** [comment]
@peteruithoven not necessarily. But being a part of houston would let us do cool things, like being able to tell if a user is logged in and replacing all of the `com.github.<username>.<project>` parts with the _correct_ RDNN of their project.

**Comment by danrabbit** [comment]
Should be fixed now :)
