### ISSUE TITLE
The website doesn't translate properly 

### ISSUE THREAD

**Issue by marcelogdeandrade** [elementary/website#2112]
### Expected behavior

I'm accessing PT-BR [version](https://elementary.io/pt_BR/) of the website.

It should translate almost all strings to PT-BR.

### Actual behaviour

A big part of the website is not translated.

Here a screenshot with an example:

![screenshot from 2018-11-07 17 04 21 2x](https://user-images.githubusercontent.com/11564309/48154232-391a9e00-e2af-11e8-974f-228e5122da7d.png)

This happens to other languages aswell.

**Comment by btkostner** [comment]
The translation module is working as inteneded. The translation template files have not been updated yet though. An update was just pushed and should show new strings in weblate soon.
