### ISSUE TITLE
Translators Slack invite link is expired

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#2121]
This community might not even be active anymore.

**Comment by btkostner** [comment]
It is active. The link should not be expired.

**Comment by btkostner** [comment]
https://ele-l10n.slack.com/

https://join.slack.com/t/ele-l10n/shared_invite/enQtNDkyOTA1MTEzMTQxLWQ1N2YyNDkwYTQwMjA4NWI1MTA5Mzk3MTQyNmMzNmMwODgyYWRjOWQwZDFkZjY5MzVjMTlmMDBlZGJlYmNiNWE
