### ISSUE TITLE
Improve payment flow trust

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2124]
Something I hear from users is that it's not clear they're using Stripe for the payment, or they're not sure what card types are accepted, or they're not comfortable entering their payment info on the site. I could see how this wouldn't be the most clear that Stripe is processing it and that they're not just handing over payment data directly to elementary:

![screenshot from 2018-12-04 12 30 06](https://user-images.githubusercontent.com/611168/49467777-7005a600-f7c0-11e8-8f18-011c987d7185.png)

Something we could do to combat those fears and help them realize they can trust the site is to surface the payment processor earlier, i.e. include a Stripe logo and possibly common card type icons below the payment options.

**Comment by lorenzocafaro** [comment]
I've made a quick prototype. It's far from pixel perfect but it should feel more trustworthy.

![custom – 1](https://user-images.githubusercontent.com/43943230/61201662-80321c00-a6e5-11e9-8589-f824d1e8d5a4.png)

Let me know what you think :)

**Comment by cassidyjames** [comment]
@lorenzocafaro thanks for the mockup! Right now we're using Stripe Checkout, which means this form is provided by Stripe themselves and we cannot modify it. However, we could switch to Stripe Elements to design the UI ourselves which might help solve this issue.

**Comment by cassidyjames** [comment]
This was about what I was thinking of, but I'm not super happy with the mono card icons.

![image](https://user-images.githubusercontent.com/611168/61250943-5ba26800-a716-11e9-992f-2a5f6fcf4cd0.png)

**Comment by lorenzocafaro** [comment]
Maybe we could desaturate them a little (e.g. `opacity: 0.8`) so they don't contrast as much with the rest of the interface

![desat](https://user-images.githubusercontent.com/43943230/61251641-5ca9b880-a75b-11e9-8f51-ee246c981ad1.png)

**Comment by cassidyjames** [comment]
See the latest progress at https://github.com/elementary/website/pull/2230
