### ISSUE TITLE
Privacy policy doesn't explicitly cover online accounts integration

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#2131]
Google requires that we:

> thoroughly disclose the manner in which your application accesses, uses, stores, or shares Google user data. Your use of Google user data must be limited to the practices explicitly disclosed in your published privacy policy.

We need to make sure we explicitly mention online accounts integration and cover the above

**Comment by danrabbit** [comment]
Got an email back from Google. They don't consider what we put up to be thorough enough

**Comment by cassidyjames** [comment]
@danrabbit did they give any more useful information or examples other than "not thorough enough"?

**Comment by danrabbit** [comment]
@cassidyjames No, but I found this https://developers.google.com/actions/policies/privacy-policy-guide

**Comment by cassidyjames** [comment]
@danrabbit ha I was just looking at that as well. I'll write something a little more extensive, but I think the disconnect is that our "service" is entirely offline and does not collect or share any information.
