### ISSUE TITLE
Hey just a heads up: Distrowatch's ElemOSLuna.iso link expired

### ISSUE THREAD

**Issue by MichaelTheGamer** [elementary/website#2134]
### Expected behavior

After Clicking on _"Download: elementaryos-5.0-stable.20181016.iso (1,410MB..."_    
end result would be: Acquisition of a sparkling new copy of   _**Linux Elementary 5.0,**_ in an **ISO** format. Of course that is what I expected: this is _Distro Watch,_ one of the top 5 (maybe even top 3 or \#1) most famous Linux sites in existence. **Nobody** gets that status by doing things like this on any regular basis. And if I can help keep it that way, then I feel it my absolute duty to notify who I can at once. Sure, it _is likely_ someone has beat me to it. With Elem OS getting >2k hits per day, very likely. But not definite. Enter...me.

Describe what you expected to happen.    
 Well, I **expected** to see either a _Mirror Site,_ or for the actual d/l to just begin. 

### Actual behavior

Describe what actually happened, being specific about how this differs from your expectations.

_**Redirect:**_  to the following website  [https://elementary.io/410](https://elementary.io/410)    

saying (basically)...   
### Steps to reproduce the behavior

1.  [From this Distrowatch page,](https://distrowatch.com/?newsid=10332)    
2. Click following "link":   **Download: elementaryos-5.0-stable.20181016.iso (1,410MB, pkglist)** 
**NOTE:**  the bullet-link just below the above link (on the Distro page) that I have C&Pasted a replica of just below this page's 3rd list item, I _did_ try out, since it pointed to same thing, but every time I did it just acted like a page refresh, putting me back at \# 1's link.
3. Find yourself on the "elementary.io/410" Whoopsie page. _**On that page,**_ however, is the link that did, in fact bring me **here.** (github/elem/website/issues/new)
• 2018-10-16: Distribution Release: elementary OS 5.0

### System information

- **Operating system**:   Kubuntu    
- **Operating system version**: 18.04 LTS bionic
- **Browser**: Firefox Quantum for Ubuntu
- **Browser version**: 64.0
- **Enabled Browser Extensions**: nothing

**Comment by danrabbit** [comment]
Download links expire intentionally. Downloads are balanced across localized servers. Distrowatch attempts to circumvent this system. They should link to our homepage
