### ISSUE TITLE
Payment Options: Alipay or WeChat

### ISSUE THREAD

**Issue by fcwys** [elementary/website#2136]
I hope elementary can support Alipay or WeChat payment. Credit card payment is not very convenient (I don't have a credit card). Because I didn't find your contact information on the official website, I would like to make suggestions here.

**Comment by danirabbit** [comment]
We recently merged a branch to migrate to the new Stripe Checkout and I've enabled WeChat and Alipay on our stripe dashboard, so this should be fixed when we deploy :)
