### ISSUE TITLE
Privacy page translation files aren't linked correctly

### ISSUE THREAD

**Issue by NathanBnm** [elementary/website#2143]
## Expected behavior

The **Privacy** page should be translated with the `privacy.json` file.

## Actual behavior

The **Privacy** page seems to be linked to a file named `privacy.json` in the but this file cannot be translated trough Weblate.

There is another file named `privacy-policy.json` which can be translated trough Weblate.

####  Solution 1

Content of `privacy-policy.json` file should be reported into `privacy.json` file and `privacy.json` file added to Weblate instead of `privacy-policy.json` file. Maybe` privacy-policy` file should be deleted ?

#### Solution 2

The **Privacy** page should be modified as **Privacy Policy** page (by changing the necessary files) to link the right translation file.

**Comment by NathanBnm** [comment]
So what can we do to fix ? Strings aren't really the same

**Comment by btkostner** [comment]
Delete all the `privacy-policy.json` files and update translation strings. The translation strings should be relatively recent as I updated them about a week ago.

**Comment by NathanBnm** [comment]
Great, I am going to fix this and open a PR

**Comment by NathanBnm** [comment]
@btkostner not a problem, I will update the missing translations
