### ISSUE TITLE
Get Involved nav links direct back to homepage

### ISSUE THREAD

**Issue by zeebok** [elementary/website#2146]
### Expected behavior

I click the Desktop nav link and it jumps down the page to the Desktop Development section.

### Actual behavior

I click the Desktop nav link and it returns to homepage.

**Comment by javidotpro** [comment]
Can you give more details of the browser you're using?

**Comment by zeebok** [comment]
Sorry, I never got an email saying anybody replied to this. Both in Epiphany and Brave I have this issue. Tried turning off blockers and all that. When I hover the cursor over the buttons the address it goes to is https://elementary.io/#desktop-development so it seems like whatever is generating the page is not including the current page I am on and then tacking on the proper section name.

**Comment by btkostner** [comment]
This does not seem to be an issue anymore. Closing.

![screenshot from 2019-02-21 13 48 35](https://user-images.githubusercontent.com/3385679/53200695-67fb1c80-35df-11e9-9b11-cd2e07c355e8.jpeg)

**Comment by MrGreenTea** [comment]
Seems to have crept back in:

![image](https://user-images.githubusercontent.com/9407731/105192066-08de1380-5b38-11eb-9e41-ee37d83cfdad.png)

**Comment by lewisgoddard** [comment]
Doesn't look like that for me. Are you browsing in a different language?

**Comment by MrGreenTea** [comment]
That's weird. On my phone this is correct. On my elementary Desktop, it shows these erroneous links.
I have my system set to English, with the region set to "United Kingdom" and Formats set to "Germany'.
Firefox settings are:

![Screenshot from 2021-01-25 09 45 02](https://user-images.githubusercontent.com/9407731/105681987-26253000-5ef2-11eb-9dcf-157473efbf00.png)
