### ISSUE TITLE
Update Slack Icon

### ISSUE THREAD

**Issue by NathanBnm** [elementary/website#2151]
Slack just reviewed their interface and icon as explained in this article : https://slackhq.com/say-hello-new-logo
Maybe the old icon should be replaced by the new one ?

**Comment by btkostner** [comment]
We use https://fontawesome.com/, so whenever font awesome updates, we will.

**Comment by NathanBnm** [comment]
Ok I didn't know you was using it, so it will be automatically updated

**Comment by cassidyjames** [comment]
Looks like the source is explicitly pointing to the old (wrong) logo.

**Comment by NathanBnm** [comment]
@cassidyjames you're right fontawesome updated their slack icon in version 5.7.0 as noticed here : https://fontawesome.com/icons/slack?style=brands but the imported version on the website is certainly older. In order to have the new icon on the website, we have to update the imported version of fontawesome.

**Comment by cassidyjames** [comment]
@NathanBnm somehow the current version works now though

**Comment by NathanBnm** [comment]
Yes but that's still the older one, only the last version will update the icon

**Comment by cassidyjames** [comment]
@NathanBnm ooooooh I'm an idiot. I saw the updated shape and forgot how the new logo was an awful, different shape. :laughing:
