### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by comradekingu** [elementary/website#2153]
Any chance of replacing Google Analytics with 

https://matomo.org/
http://www.openwebanalytics.com or
https://awstats.sourceforge.io ?

Edit: I think this would look good on the Privacy page, because privacy.

**Comment by javidotpro** [comment]
I think we should replace Google Analytics with Matomo, it's a great alternative and it's widely supported. In the case that we really needed analytics, we should question first if we really need to analyse the traffic of our site? Is this really needed? What does the metrics help us measure?

**Comment by javidotpro** [comment]
I could help to install and maintain an instance with Matomo if that is of any help :-)

**Comment by lewisgoddard** [comment]
Matomo doesn't offer every feature we currently use without paid add-ons to the free self-hosted edition. Open Web Analytics is a more feature-comparative solution.

**Comment by cassidyjames** [comment]
[Plausible.io](https://plausible.io/) is another option, whether self-hosted or not. Honestly, I'd be fine paying them to host it if it means it's hands-off for us—plus it helps support the development of it.

**Comment by lewisgoddard** [comment]
usefathom.com was something I saw with a similar thing, slightly smaller and more expensive, also has an open-source version https://github.com/usefathom/fathom

### Live Demos
- https://plausible.io/plausible.io
- https://app.usefathom.com/share/lsqyv/pjrvs#/?from=2020-06-12%2000%3A00%3A00&site=184&to=2020-06-19%2023%3A59%3A59

**Comment by cassidyjames** [comment]
@lewisgoddard if you think Plausible will handle what we need, I'm most in favor of it. The pricing seems reasonable, and I like what the project writes on their blog. :stuck_out_tongue: I also like that it appears it's fully open source, not just open core like Fathom.

**Comment by lewisgoddard** [comment]
Plausible is single user [for now](https://plausible.nolt.io/148), so presumably we need to sign up as plausible@elementary.io or something and share credentials. My #1 most common gripe with hosted software is not supporting enterprise teams.

**Comment by cassidyjames** [comment]
@lewisgoddard we can use the webdev@ alias and store credentials in Bitwarden like we do for other single-user accounts.

**Comment by cassidyjames** [comment]
I'm planning to get Plausible set up this week, and we can have some overlap with Google to ensure we're getting all the right data in Plausible before decommissioning Google. And then we probably need to figure out how to export old data out of Analytics if possible for historical trends, etc.

**Comment by danrabbit** [comment]
Reopening since this was auto-closed by keyword and it's still technically in progress

**Comment by lewisgoddard** [comment]
We still need to replace goals and events, then remove Google Analytics.

**Comment by fabianski7** [comment]
If you really need to use some service like google analytics, definitely the best option would be to self-host it. most sites are blocked by extensions like ublock and the linux hosts file.
Google analytics is always the first to be blocked in any of these extensions (and rightly so!), but plausible.io is also blocked by [some lists](https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt).

**Comment by lewisgoddard** [comment]
We're using a custom domain with Plausible, so a list like that likely won't work.

**Comment by comradekingu** [comment]
@lewisgoddard Is it self hosted? The blocklists update rather quickly.

**Comment by lewisgoddard** [comment]
No, it's a custom domain on the SAAS offering of Plausible.

**Comment by comradekingu** [comment]
One botnet to the next doesn't fix the issue I had originally.

**Comment by cassidyjames** [comment]
@comradekingu Plausible is entirely open source, does not store IP addresses or user agents, does not share data between domains, and does not track users. It is the exact same as if we were hosting it ourselves on a third-party web host—we retain control over the data, but don't have to be the ones maintaining the servers. Not sure why you're implying Plausible is a "botnet," but that's pretty far from reality. You can see [their data policy](plausible.io/data-policy) for more information. We are extremely confident in our decision to use Plausible while respecting user privacy. We just published a [blog post](https://blog.elementary.io/leaving-google-analytics-is-finally-plausible/) about it, too.

You are also welcome to review the source code: https://github.com/plausible/analytics

**Comment by comradekingu** [comment]
Subcontractors can't be malicious, and when they say they are running the software they say they are, it is always true. When they say they do something with identifiable information in their data policy, it must be true. It is after all, a document. There is no reason to distrust a small data collection company in the year 2020. And because that seems plausible, it would never be bought and moved to the US like example n de jour this week.

It is like funding a gardening outfit in the Columbian jungle, that just _happens_ to operate behind closed doors. But they film themselves giving food the poor and building sports arenas? If it is so much less data, why move it away from the much heavier page and into the cloud? Because it is presumably a VPS, but not(?) It isn't quicker, it doesn't save the environment. To me it just seems like lost opportunity in communicating a simple point of why something is bad, should be considered as such, and isn't done.

So the user is left with a solid maybe/10? It is exasperating. "Analytics" "Telemetry". How is a consumer meant to decide between the well-meaning corporate language of GAFAM and elementaryos? The idea that it isn't in the OS is one of those gotcha caveats that the user shouldn't have to entertain while reading about it. The googs of the world have more money and their language is honed to perfection. You have easily lost reputation, make of that what you will.

From the blogpost:
>Unlike Google, Plausible isn’t in the advertising game

yet

>and doesn’t have an incentive to collect and sell user data.

Except, exactly the exact same incentives as Google have, minus public image. (And I don't think you are thrashing Google Analytics nearly enough). Or if not their initiative, selling to willing takers sharing those ideals, as per the presented e-mail. This all boils down to elected ethics, which is, and I hate to say it, erecting a model of faith that fundamentally isn't trustworthy. The bigger the company you are building gets, the greater the incentive.

https://blog.elementary.io/privacy-and-elementary-os/
> elementary OS does not send any private data back to elementary. We don’t collect stats when you install it, we don’t collect usage analytics, and we don’t snoop on what you’re typing.

> However, the data is only as good as those who are using it, and too often these troves of data can be used simply to push a pre-existing agenda.

>As a smaller company, it’s simply more responsible for elementary to not dabble here at all.

It reminds me of this https://medium.com/elementaryos/adios-transifex-weve-gone-to-weblate-59870dea06b2 Transifex is presented as a "free service". It is to that effect neither libre or gratis. It is only no cost for non-commercial libre software, as in no income. It also has a tacit business model of holding projects to the fire once it thinks there is bank to be made.

>We’re happy to free up their resources so that their Open Source program can be used by smaller projects that need a leg up more than we do.

Read their terms of service, user agreement and cookie policy, then call a spade a spade. Transifex is cancer.
