### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by NathanBnm** [elementary/website#2154]
Some translations are still missing although they have been recently updated:

- In the footer "Press" and "Privacy" are probably not translatable so we have to add them to be translatable, here is a screenshot (French) (See #2162)

![image](https://user-images.githubusercontent.com/45366162/53207856-2eed9700-3635-11e9-9f41-160451e668e2.png)

- The "Store" page has been translated to French but still appearing in English for the moment. **Why is the store in the exclusions if it can be translated?**

**Comment by NathanBnm** [comment]
Second point (on "Privacy" page) is fixed now, there are still issues with the other ones

**Comment by btkostner** [comment]
The first point is due to https://github.com/elementary/website/issues/2162

**Comment by NathanBnm** [comment]
New translations should be added too after adding new content #2166. 
OEM Ressources page should also be added to Weblate.

**Comment by NathanBnm** [comment]
Any news about this?

I noticed that some new strings were not available for translation.

- "Payments processed & secured by `Stripe logo`"
- "What's new about elementary OS 5.1 Hera" section (homepage and press)
- "Get Work Done. Or Play" section with "Multitasking View", "Picture-in-Picture" and "Do Not Disturb" 
- The new paragraph above the featured apps
- "Screen Time" in the "Parental Control" section
- Indigogo popup
- "Blog" section (privacy page)
- The "Get involved" page should be updated as well

Maybe you could consider translating the blog too, I mean the structure, not the posts.

**Comment by ryonakano** [comment]
Recently some translation files of some pages like the index page or getting started guide got the ability to be updated automatically. However, both points the author mentioned has not been fixed yet. The footer (maybe [Website/layout](https://l10n.elementary.io/projects/website/layout/) on Weblate?) seems to be out of sync and the Store page is still shown in English, although it's 100% translated into Japanese on Weblate.

**Comment by NathanBnm** [comment]
Thanks for your comment @ryonakano you're right, this issue shouldn't have been close. @lewisgoddard could you please open this back?

**Comment by NathanBnm** [comment]
I just added checkbox to mark resolved ones.
