### ISSUE TITLE
Video freezing in youtube,facebook 

### ISSUE THREAD

**Issue by ahs95** [elementary/website#2159]
When I watch videos on youtube, facebook and any other video sharing websites using chrome or epiphany the video freezes. When I do nothing for a few minutes and I have to move the mouse so that the video continues.
Version - elementary os 5 (juno) 
It would be better if the bug will be fixed quickly!
Thanks in advance.

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/os/issues/121
Also this is the repository for the elementary OS website. 
Please refrain from using !'s it usually comes across as rude.

**Comment by ahs95** [comment]
I didn't know that.
Extremely sorry.
