### ISSUE TITLE
Design page - "The User is Drunk" video no longer works

### ISSUE THREAD

**Issue by lxqueen** [elementary/website#2177]
### Expected behavior
Expected to see video embed of Will Dayble's *"The User is Drunk"* 4-minute presentation on the [Design/HIG page](https://elementary.io/docs/human-interface-guidelines#design-philosophy) of docs.

### Actual behavior
The video seems to have been taken down or hidden from YouTube. I did a quick search online to see if there was a copy hosted somewhere else but no such luck, which is a shame as it's a great video.

There is [another video by Dayble](https://www.youtube.com/watch?v=zI9esN3BqbI) with the same content, but this version is a 20 minute long presentation, I don't know if that may be a little too long to throw at a user in these docs or not, but was worth bringing up as an alternative.

### Steps to reproduce the behavior
1. Go to [Design/HIG page](https://elementary.io/docs/human-interface-guidelines#design-philosophy) of docs
2. Scroll down to video embed
3. Lament loss of lack of amusing yet insightful video *(optional)*

### System information
- **Operating system**: Solus
- **Operating system version**: 4.0 *(using LTS kernel 4.9.163-127.lts)*
- **Browser**: Firefox
- **Browser version**: 65.0.1
- **Enabled Browser Extensions**: uBlock, uMatrix

**Comment by cassidyjames** [comment]
I've emailed the author to see if they could re-upload or provide us with a copy. We'll see what they say. The 4:30 version was a good length and I'd like to retain it if we could.

**Comment by cassidyjames** [comment]
The video has been reenabled as unlisted instead of private, fixing this issue.
