### ISSUE TITLE
Move ast_ES to just ast

### ISSUE THREAD

**Issue by fitojb** [elementary/website#2180]
https://github.com/elementary/website/tree/master/_lang/ast_ES

The additional country code is unnecessary.

**Comment by josprachi** [comment]
means i have to create a new folder named ast and move all the contents from ast_ES right?

**Comment by fitojb** [comment]
I think you can just [use the `git mv` command](https://koukia.ca/rename-or-move-files-in-git-e7259bf5a0b7) :)

**Comment by josprachi** [comment]
Thank you :)
