### ISSUE TITLE
Users reporting issues downloading

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#2201]
I've seen reports on social media and through email that users are having trouble with their download. So far it's unclear where the breakage is. Opening a ticket so we can track the issue and try to direct users here to provide more information

**Comment by danrabbit** [comment]
So far I can't reproduce the issue either with or without payment. The only thing I can say is that it seems like after paying the download dialog might take a second to pop up and there's no good loading indicator between the disappearance of the payment dialog and the appearance of the download dialog. I'm not sure if this is what users are experiencing, however. We'll need more information from those experiencing the issue

**Comment by lewisgoddard** [comment]
Based on the log in [this thread](https://www.reddit.com/r/elementaryos/comments/bs6699/i_can_not_download_the_iso_from_the_official/?utm_source=share&utm_medium=ios_app) it's actually not loading the config file and failing to get basics like the release name in the download.js

**Comment by lewisgoddard** [comment]
Also see https://sentry.io/organizations/elementary-llc/issues/727170057/?project=101325&query=download.js

**Comment by jhthenerd** [comment]
Hi, I'm also getting this issue. These are the console logs I get when opening the page:
```
Sentry loaded elementary.io:34:21
Google analytics pre-load catch set raven.js:58:31
TypeError: _config2.default.then is not a function main.js:1:1539
jQuery loaded raven.js:58:31
Loaded slingshot.js raven.js:58:31
jQuery.leanModal2 loaded raven.js:58:31
Unhandled promise rejection raven.js:58:31
    b raven.js:58
    onunhandledrejection (index):40
    result common.js:1
    exports common.js:1
    onUnhandled common.js:1
    exports common.js:1
    <anonymous> common.js:1
    run common.js:1
    listener common.js:1
TypeError: "config.release is undefined"
    61 https://elementary.io/scripts/download.js:1
    notify https://elementary.io/scripts/common.js:1
    notify https://elementary.io/scripts/common.js:1
    flush https://elementary.io/scripts/common.js:1
raven.js:58:31
    b raven.js:58
    onunhandledrejection (index):41
    result common.js:1
    exports common.js:1
    onUnhandled common.js:1
    exports common.js:1
    <anonymous> common.js:1
    run common.js:1
    listener common.js:1
Sitewide configuration loaded raven.js:58:31
```
Let me know if you need any more information.

**Comment by peteruithoven** [comment]
I think we should clarify how people can contribute information. 
I'd suggest sharing a screen recording or a set of screenshots. 
Maybe use the Developer tools and share the messages that appear in the Web console?
Maybe also check the Network tab for failed requests?

**Comment by MagayAlex** [comment]
Hi!
This is my screen record with this issue
[https://youtu.be/nDq-VgOkd-U](url)

**Comment by peteruithoven** [comment]
@MagayAlex Thanks! Could you maybe also share the contents of the console and network panels in the developer tools? (using Firefox / Chrome)

What do you get when you visit the following url?
https://elementary.io/api/config

**Comment by MagayAlex** [comment]
https://elementary.io/api/config => 
```
{
    "release": {
        "title": "Juno",
        "version": "5.0"
    },
    "previous": {
        "title": "Loki",
        "version": "0.4.1"
    },
    "keys": {
        "sentry": "https:\/\/5dc4884b382c42b3a0d6440797af3454@sentry.io\/101325",
        "stripe": "pk_live_ZtcG6SqsVtMbTuJARKujZ0lE"
    },
    "user": {
        "ip": "95.153.131.119",
        "region": "ams3",
        "timecode": "MTU1OTA0MzIyOQ==",
        "trackme": true
    }
}
```

**Comment by MagayAlex** [comment]
This is console from chromium, Ubuntu
```
Sentry loaded
raven.js:58 Google analytics pre-load catch set
main.js:1 Uncaught TypeError: Cannot read property 'then' of undefined
    at Object.73 (main.js:1)
    at __webpack_require__ (common.js:1)
    at Object.65 (main.js:1)
    at __webpack_require__ (common.js:1)
    at Object.138 (main.js:1)
    at __webpack_require__ (common.js:1)
    at window.webpackJsonp (common.js:1)
    at main.js:1
raven.js:58 jQuery loaded
raven.js:58 Stripe loaded
raven.js:58 Loaded slingshot.js
raven.js:58 jQuery.leanModal2 loaded
raven.js:58 Unhandled promise rejection
a.<computed> @ raven.js:58
raven.js:58 TypeError: Cannot read property 'release' of undefined
    at download.js:1
a.<computed> @ raven.js:58
download.js:1 Uncaught (in promise) TypeError: Cannot read property 'release' of undefined
    at download.js:1
raven.js:58 Sitewide configuration loaded
2sentry.io/api/101325/store/?sentry_version=7&sentry_client=raven-js%2F3.26.2&sentry_key=5dc4884b382c42b3a0d6440797af3454:1 Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)


```

**Comment by peteruithoven** [comment]
@MagayAlex and the network panel? Maybe share a screenshot of that? Especially any request that doesn't have the 200 status is interesting. 

Comparing that console output to mine I'm missing:
```
Loaded showcase.run.js
Loaded download.js
raven.js:58 Google analytics loaded
```

Could you try loading the following items?
- https://elementary.io/scripts/showcase.run.js
- https://elementary.io/scripts/download.js

**Comment by MagayAlex** [comment]
When i open your links - it just a lot of code, start from 'webpackJsonp'

This is screenshot of the network panel. 
Second wrong name - same except this field: X-Served-By: api-store-9d964d17 
[https://yadi.sk/i/kCMD7s7hG20QOw](url)

**Comment by stormchaser3000** [comment]
would it help if I posted a video I made of the problem? based on what I have read here it looks like it may not be needed

**Comment by peteruithoven** [comment]
@MagayAlex Please try that again with the side panel closed. (You can include images in Github directly) If there are any non 200 status items sharing the full contents of the side panel Headers tab would be usefull. 

@stormchaser3000 No thanks, a video has already been shared. Sharing the contents of the network panel (sidebar closed) would be useful. If there are any non 200 status items sharing the full contents of the side panel Headers tab would be useful.

**Comment by peteruithoven** [comment]
Another thing someone could do in Chromium for example is:
1. Open Developer tools
2. Go to Sources tab
3. In the top right click on the "Pause on Exceptions" icon (it should turn blue). (It's the second icon with a pause illustration)
4. Make sure the "Pause on caught exceptions" is unchecked
5. Reload page
6. It should show navigate in the code where the error originates, please share as much info as possible from the developer tools using screenshots.

**Comment by MagayAlex** [comment]
This is a log of Headers tab, item with status 429, instead of 200.
```
Request URL: https://sentry.io/api/101325/store/?sentry_version=7&sentry_client=raven-js%2F3.26.2&sentry_key=5dc4884b382c42b3a0d6440797af3454
Request Method: POST
Status Code: 429 TOO MANY REQUESTS
Remote Address: 35.188.42.15:443
Referrer Policy: origin
Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication
Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Connection: keep-alive
Content-Language: ru
Content-Length: 92
Content-Type: application/json
Date: Tue, 28 May 2019 12:42:03 GMT
Expires: Tue, 28 May 2019 12:42:03 GMT
Last-Modified: Tue, 28 May 2019 12:42:03 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Sentry-Error: Creation of this event was denied due to rate limiting
X-Served-By: api-store-206a9130
X-XSS-Protection: 1; mode=block
Provisional headers are shown
Content-Type: text/plain;charset=UTF-8
Origin: https://elementary.io
Referer: https://elementary.io/
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Mobile Safari/537.36
sentry_version: 7
sentry_client: raven-js/3.26.2
sentry_key: 5dc4884b382c42b3a0d6440797af3454
{project: "101325", logger: "javascript", platform: "javascript",…}
breadcrumbs: {,…}
event_id: "9eb6cb47080748d485fa02e126ecdec8"
exception: {,…}
extra: {session:duration: 211}
logger: "javascript"
platform: "javascript"
project: "101325"
release: "5.0"
request: {headers: {,…}, url: "https://elementary.io/ru/"}
transaction: "https://elementary.io/scripts/main.js"
```

**Comment by peteruithoven** [comment]
That `TOO MANY REQUESTS` to `sentry.io` means we're reporting a lot of errors, now we just need to figure out what errors.

**Comment by MagayAlex** [comment]
Pause on Exceptions

![Screenshot from 2019-05-28 15-52-07](https://user-images.githubusercontent.com/32357600/58479289-a6652200-8160-11e9-8691-166fabc77c7f.png)

**Comment by peteruithoven** [comment]
@MagayAlex Could you enlarge the panel? Maybe also enlarge the bottom part. That's kind of what I was going for with "as much info as possible"...

**Comment by MagayAlex** [comment]
i hope this is more usefull
![Screenshot from 2019-05-28 15-58-18](https://user-images.githubusercontent.com/32357600/58479721-75d1b800-8161-11e9-812e-2eab299521a2.png)

**Comment by peteruithoven** [comment]
I think the error comes from here: 
https://github.com/elementary/website/blob/7a4e1ba417309dedc5eaecd9cdaff764981a5fa3/_scripts/pages/download.js#L15-L16

But the weird thing is that this `config` is loaded successfully seeing the 'Sitewide configuration loaded' logs.
https://github.com/elementary/website/blob/7a4e1ba417309dedc5eaecd9cdaff764981a5fa3/_scripts/config.js

**Comment by peteruithoven** [comment]
@MagayAlex reported that clearing his cash and cookies solved the issue for him.

**Comment by stormchaser3000** [comment]
those two solutions did not help me. I should also mention that this issue persists across ever web browser I have tried to reproduce this issue on (firefox and epiphany)

**Comment by btkostner** [comment]
Considering that all browsers have the same issue, it's not a JS support issue. I would guess your network, firewall, or ISP are blocking Stripe from loading, resulting in that promise to fail.

**Comment by sharkaev** [comment]
There is no action after clicking on download button.
![image](https://user-images.githubusercontent.com/4406307/58492278-60c14d00-8192-11e9-9163-d9bede7e3fad.png)
Sometimes there is an error appears with message "Too many requests"

**Comment by btkostner** [comment]
@sharkaev Press `F12`, click "Network", make sure you have "All" selected next to "Hide data URLs", go to "elementary.io" then hit `Ctrl` `Shift` `R`. Take a screenshot of any red text items in that list please and thank you.

**Comment by sharkaev** [comment]
@btkostner 
There is only one error
![image](https://user-images.githubusercontent.com/4406307/58492999-d8dc4280-8193-11e9-80d7-4b3a2c7d4e93.png)
this one:
https://sentry.io/api/101325/store/?sentry_version=7&sentry_client=raven-js%2F3.26.2&sentry_key=5dc4884b382c42b3a0d6440797af3454

**Comment by peteruithoven** [comment]
@sharkaev I'm afraid that's: https://github.com/elementary/website/issues/2201#issuecomment-496503006

**Comment by sharkaev** [comment]
sorry for the off-top, but may be you have any mirror to download the latest distribute of Juno?
Can't wait to try out new elementary.os

**Comment by btkostner** [comment]
@sharkaev Try doing these things please:

1) What version of chrome are you running?

2) Press `F12`, click "Console", type this, and press enter:
```
Promise.all([]).then(() => console.log('testing'))
```

3) Go to "elementary.io", press `F12`, click "Console", type this, and press enter:
```
await $.getJSON('/api/config')
```

**Comment by sharkaev** [comment]
@btkostner 
Chrome Version 74.0.3729.169
this is step 3 screenshot:
![image](https://user-images.githubusercontent.com/4406307/58495643-d2e96000-8199-11e9-8acb-3d4d10e2af6a.png)

**Comment by lewisgoddard** [comment]
Can someone with a broken download button post the contents of the config item loaded under network? 

If it's working but erroring on something not being set later on, maybe the config is loading fine but the server is generating it wrong.

**Comment by btkostner** [comment]
@sharkaev I just disabled sentry JS on the website. Can you try doing it now?

**Comment by sharkaev** [comment]
@btkostner Yeap its working now!
Thank you very much!

**Comment by stormchaser3000** [comment]
it is still not working for me... I wonder if it is an issue on my end

**Comment by sharkaev** [comment]
@stormchaser3000  try to F5 or Ctrl + Shift +R to open page without cache

**Comment by stormchaser3000** [comment]
@sharkaev still didin't work

**Comment by sharkaev** [comment]
@stormchaser3000  try `F12` open `Network` and select checkbox `Disable cache`. And reopen page

**Comment by stormchaser3000** [comment]
@sharkaev still doesn't work

**Comment by sharkaev** [comment]
@stormchaser3000  what is the output inside `Console`

**Comment by stormchaser3000** [comment]
this:
![Screenshot from 2019-05-28 14-18-32](https://user-images.githubusercontent.com/6621537/58505857-867b3180-8153-11e9-99ea-658b3a6b4b82.png)

**Comment by sharkaev** [comment]
@stormchaser3000 and what is happening after clicking on download button? 
I mean both in console and web page

**Comment by stormchaser3000** [comment]
nothing is happening

**Comment by stormchaser3000** [comment]
would this 403 error have any bearing on this issue?
![Screenshot from 2019-05-29 10-36-27](https://user-images.githubusercontent.com/6621537/58570487-ae26d400-81fd-11e9-8d35-e37647a6cf60.png)

**Comment by btkostner** [comment]
@stormchaser3000 It does not. But an interesting other bug.

**Comment by MuhammedKpln** [comment]
I guess it has something to do with google analytics.

**Comment by aethezxd** [comment]
Still looking for a download.

**Comment by peteruithoven** [comment]
@aethezxd and stormchaser3000 Please don't spam this issue. 
@MuhammedKpln what makes you think this has to do with google analytics?

**Comment by peteruithoven** [comment]
If someone is experiencing this issue and is willing to help out, please try running the website locally and see if you still experience the issue. Instructions: https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md#simple-php-server

If you still experience the issue we should be able to more easily debug the javascript that is failing. 

Please reach out if you need help with this, for example through the [community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc).

**Comment by MonkeyNo28** [comment]
I checked the page on firefox with web developer and it looks like the $20 button is permanently highlighted .. could that be the problem?? 
![Capture](https://user-images.githubusercontent.com/51243676/58724122-c89db080-83a9-11e9-8300-66d04e48bfa3.PNG)

**Comment by peteruithoven** [comment]
@MonkeyNo28 No. I mean lot's of weird stuff will happen after a javascript error, we need to figure out why it errors. 
Seeing sourcemaps aren't connected online I need someone who can reproduce the issue to run the site locally, that would make it easier to debug the javascript.

**Comment by peteruithoven** [comment]
Alright, looks like there is a way in Chromium we can get more useful debugging information. We can manually add sourcemaps.

1. Open Developer tools (press <kbd>F12</kbd>)
2. Go to Sources tab
3. In the top right click on the _Pause on Exceptions_ icon (it should turn blue). (It's the second icon with a pause illustration)
4. Make sure the _Pause on caught exceptions_ is unchecked
5. Reload page
6. The middle section should navigate to the code where the error originates
7. Right click in middle section, select _Add source map..._
8. I've understood the issue happens in the common.js file, so please enter the following url to the sourcemap: 
`https://elementary.io/scripts/common.map.js`
9. It can take a while for Chromium to use the sourcemap, but when it's done the middle section should show more readable code. 
10. Now please share what you see in the developer tools. Please make sure we see the code in the middle section and make sure you share what you see in the right panel under _Call Stack_ and under _scope_. Examples:

![Screenshot from 2019-06-01 10-20-52@2x](https://user-images.githubusercontent.com/523210/58745881-52578780-8457-11e9-91af-f18344695c19.png)
![Screenshot from 2019-06-01 10-21-06@2x](https://user-images.githubusercontent.com/523210/58745882-55eb0e80-8457-11e9-9209-e3b66639d751.png)

The usefull information isn't always shared in the current "call stack" so we might ask you to navigate to another Call Stack and share again.

**Comment by doublehourglass** [comment]
I'd suggest something when it comes to filtering possible causes.
I cannot replicate a problem on any browser. But my config isn't probably very common.
First, to exclude an ISP blocking specific requests one can try downloading the distro directly using wget:

**Comment by lewisgoddard** [comment]
@MagayAlex or anyone else with the issue, could you provide new console logs after #2212 was merged?

**Comment by rickychristensen** [comment]
<img width="1279" alt="Screen Shot 2019-06-01 at 1 47 09 PM" src="https://user-images.githubusercontent.com/32140408/58752906-e2a3c580-8473-11e9-9833-3d37f3ad557c.png">

**Comment by lewisgoddard** [comment]
I'm marking this as incomplete until we can get a report with the debugging added.

**Comment by cassidyjames** [comment]
Do we know if this is still occurring for anyone? I've not heard any reports recently.

**Comment by lewisgoddard** [comment]
Based on Sentry statistics, this error happens very rarely if at all since early June. We have since fixed sourcemaps and added config logging so this error should be easier to debug if it recurs.
