### ISSUE TITLE
download button off center

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#2202]
After payment, the download button is very off center:

![Screenshot from 2019-05-25 10 16 19@2x](https://user-images.githubusercontent.com/7277719/58372699-3f343d00-7ed6-11e9-8514-ef75869156d0.png)

**Comment by lewisgoddard** [comment]
In `download.js` Line 155 we make an element `#choice-buttons` only contain hidden elements, but this still causes the grid system to compensate for its existence. We should remove it and append a new one to `#amounts` instead.
