### ISSUE TITLE
Not connected to sourcemaps

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#2209]
### Expected behavior
Using the browsers developer tools I should be able to browse the source files and view the original (pre-transpiled) source code. 
This should work because we also create sourcemaps, see: [webpack config](https://github.com/elementary/website/blob/master/webpack.config.babel.js).
These sourcemaps have also been deployed: https://elementary.io/scripts/download.map.js
This would make it much easier to look into issues like: https://github.com/elementary/website/issues/2201

### Actual behavior
I can only find the transpiled, hard to read files. 
I think, somehow the connected from the transpiled files to the sourcemaps is broken. 

### Steps to reproduce the behavior
1. Visit elementary.io
2. Open develoepr tools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>)
3. Go to Debugger (Firefox) of Sources
4. Use left side panel to browse through files.

### System information
Browser: Chromium or Firefox

**Comment by peteruithoven** [comment]
When I run the website locally I can find the sourcemaped files, even when I run build and start with `NODE_END=production`.

**Comment by lewisgoddard** [comment]
Do your generated scripts have a `//# sourceURL=source.map.js` at the top of the file?

**Comment by peteruithoven** [comment]
Looking at for example [download.js](https://elementary.io/scripts/download.js), there is no mention of `sourceURL`.
Looking at another project I see it does include the `sourceURL`: https://github-releases.peteruithoven.nl/static/js/main.577f15ee.chunk.js
When I run the website server locally there is a `sourceURL` in the `/scripts/download.js` file. 

So something removes this comment when it's deployed...

**Comment by peteruithoven** [comment]
Apparently it's possible in chromium to manually add sourcemaps, which could be a hacky workaround.

**Comment by peteruithoven** [comment]
We've figured out that auto-minify on cloudflare was stripping these sourceURL comments. Sourcemaps work now.
