### ISSUE TITLE
Save the word "Size" in the store

### ISSUE THREAD

**Issue by comradekingu** [elementary/website#2231]
Was looking at #1563
![image](https://user-images.githubusercontent.com/13802408/61319009-9edc0400-a806-11e9-83bd-94f629ecada5.png)
vs
![image](https://user-images.githubusercontent.com/13802408/61319134-dea2eb80-a806-11e9-8cc7-9a7d7fb79c5a.png)

with a small c I think it is good.

**Comment by luucamay** [comment]
What do you mean by save the word Size, that it should appear repeated?

**Comment by lewisgoddard** [comment]
I would probably just move "Size Chart" to under the "Size" dropdown, not try to combine it into the title to save one word.

**Comment by comradekingu** [comment]
@luucamay I mean the second instance can be saved for another day.
@lewisgoddard Sounds good. Perhaps the whole "Size chart" can be a link. When it is open there is even less noise.

**Comment by cassidyjames** [comment]
Not really relevant with the new store design
