### ISSUE TITLE
Just a digression

### ISSUE THREAD

**Issue by 1arrywei** [elementary/website#2232]
**Just a digression**     
The product is close to perfect, but it's not perfect, and the biggest pain I feel is: why can't I donate through WeChat and Alipay on your website?

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/website/issues/2136
(Also your title, could use work ;) )

**Comment by lewisgoddard** [comment]
Duplicate of #2136
