### ISSUE TITLE
The landing page is heavy on marketing and buzzwords

### ISSUE THREAD

**Issue by cwillu** [elementary/website#2240]
While it's not surprising that the above-the-fold is all gloss, I'm a bit dismayed that there's nothing written or linked on front page that summarizes what ElementaryOS is better than the first paragraph of wikipedia's description.

A less-fluffy sentence or two at the bottom above the footer (perhaps a "What's in ElementaryOS?" link?) would be easier to scan for; I missed the GNU/Linux bit kinda hidden away in the Safe & Secure section for long enough to start filing a bug :p.  Not that _that_ needs to be the focus by any means, just hard to scan.

(Apologies for the double post, logged in under the wrong account)

**Comment by cassidyjames** [comment]
I mean, the primary purpose of the website is basically marketing, and that's not a bad thing. :stuck_out_tongue: Our target audience doesn't and shouldn't care that elementary OS is "GNU/Linux" or the detailed technical aspects, especially on the home page. If there's more detail you'd like to add to the documentation somewhere, feel free, but I am inclined to close this as a design conflict.
