### ISSUE TITLE
Update the ISO download regularly

### ISSUE THREAD

**Issue by cyanit** [elementary/website#2242]
### Expected behavior
When clicking download, it'll download a somewhat recent iso.

### Actual behavior
Downloading the iso is fairly quick, but after installing it you have to download a lot of uptates for a while, which is incredibly annoing, especially when setting up multiple machines.

### Steps to reproduce the behavior
1. Download elementary os
2. Open AppCenter
3. Realize you will need to download way too many updates

### Why
Yes, its not the conventional way, but elementary os is geared towards ease of use, right?
It would definitly cut the time to get up and running.
Maybe even do this for paying users only, similar to the app center.

**Comment by Angedestenebres** [comment]
I agree with this.
Moreover, even if the ISO is not the latest version, you should have the possibility to update the OS during the installation as proposed but it's not the case, see: https://github.com/elementary/os-patches/issues/78

**Comment by danrabbit** [comment]
I'm going to close this as fixed since as of late we've been updating the download every month :)
