### ISSUE TITLE
Slack links (community and translations) regularly expire

### ISSUE THREAD

**Issue by Exalm** [elementary/website#2255]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The slack community [link](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) both from the icon on the main page and [here](https://elementary.io/docs/code/reference#you-can-get-a-bit-of-help) leads to the following page:

![Screenshot from 2019-09-25 23-29-43](https://user-images.githubusercontent.com/1510457/65629222-77ea3d00-dfc2-11e9-84f5-d089c2983b07.png)

### To Reproduce
1. Go to https://elementary.io/
2. Click on the slack icon in the upper right corner
3. See error

### Expected behavior
Something that allows to join the channels. :)

**Comment by icweb** [comment]
I can do this, what is the correct invitation link?

**Comment by ThomasRedstone** [comment]
It looks like the invite links are relatively temporary if you have a large, growing community:

`Workspace Owners and Admins can create a link that anyone can use to join their workspace. Invite links can be used by up to 2,000 people. You'll need to create a new link if you reach this limit.`

https://slack.com/intl/en-gb/help/articles/201330256-invite-new-members-to-your-workspace

Something like this may be more sustainable:
https://github.com/outsideris/slack-invite-automation

**Comment by zenithlight** [comment]
I think someone already in the channel is going to need to generate a new invite link.
I agree that using an automated solution is better, that way when an invite link expires, we don't have to change it in multiple places (website, subreddit, probably other places).
Does elementary already have a Heroku/AWS/etc. account that can be used to deploy something like this? Then the only thing would be skinning the invitation page to look "elementary-ish".

**Comment by btkostner** [comment]
elementary uses Digital Ocean for it's hosting

**Comment by lewisgoddard** [comment]
We could do that here by having a page on the main site that redirects to an up-to-date link.

These people can generate a link. 
![image](https://user-images.githubusercontent.com/831389/66355416-2a28e980-e95f-11e9-8ac3-cf407e943b41.png)

**Comment by zenithlight** [comment]
That works too. Can one of the above generate a new invite link?

**Comment by karlprieb** [comment]
Any update on that?

**Comment by ReyPena** [comment]
If someone can generate the link I will be happy to change it!

**Comment by lewisgoddard** [comment]
@cassidyjames @donadigo @btkostner @tintou @danrabbit @matzipan 

Looks like you guys are the only ones that can help fix this.

**Comment by btkostner** [comment]
https://join.slack.com/t/elementarycommunity/shared_invite/enQtNzk4MTA5Mzc1Mzc5LTUxN2FmNDY3NDE4ZTBiNDAxMzk2Mzg4MTY5OWFkMmEwMDMzNzllZDc1NjE0ZTA1ZTY5OWU4MzE1MGM2NzczYzY

**Comment by cassidyjames** [comment]
The problem is the link expires automatically after a short amount of time. Ideally we could generate an up-to-date invite link on the server side to keep it up to date.

**Comment by karlprieb** [comment]
The link expire when reach the limit of 2000 invited users, we can use the Slack API to generate another link on server side each X days and automatically update the website.

**Comment by lewisgoddard** [comment]
There are some comments further up about automation, but that requires slack keys from one of the same users.

**Comment by lewisgoddard** [comment]
Ultimately I think we should do that as the translators slack link is also broken.

**Comment by djaeris** [comment]
I would like to join the translators team, but there is no working Slack link. Could somebody please paste a new link here so that there is a way to join before this issue gets properly resolved? Thanks in advance.

**Comment by RMcNeely** [comment]
Hey everyone, I started to take a look at this issue to see if I could get it working. I went thru, created a personal slack team to test everything and follow Slack's guidelines and the the links above. It looks like Slack is strongly encouraging this sort of thing to be done via a Slack app now that runs as an OAuth application. There is a way to use a "legacy token" which it appears (though this is never explicitly stated one way or the other) to be how the previous links have been generated. There is an undocumented API that people have been hacking at with decent success but I'm not a fan of using undocumented API's at the mercy of another company. So what does this mean?

The absolutely easiest thing to do would be to change the link to on the header to link to another page that would allow a person to generate their own invitation, this seems to be Slacks preferred method. If we use the above mentioned repo it could be set up with Docker as soon as someone with admin access sets up the Slack app to generate the OAuth token. Most of this can be done easily enough by someone who has access to the elementary servers. We would then point the link to the page spun up by the Docker server.

This approach would not not have the invite page that would match elementary's style however which  may be an issue. If so we could decide to fork this work or redo everything. Let me know and I can start working on whatever the consensus is.

**Comment by ahayes** [comment]
New user of Elementary OS here. I just spent quite a bit of time tracking down a working invite link in the developer docs after running into an expired "Join Chat" link on the "Get Involved" page. I was going to do a pull request with the updated link and then saw the expired URL repeated in 10+ pages worth of GitHub search results and decided to file an issue instead. Searched first and found this thread. So, nice to see it has been thought through, but good grief is Slack ever being a pain in the butt about it. Have you looked into hosting your communications on something open source like Rocket.Chat where you can just link people to your channel without any fuss?

**Comment by lewisgoddard** [comment]
We should really just set up an instance of [rauchg/slackin](https://github.com/rauchg/slackin) at something like [slack.elementary.io](https://slack.elementary.io)

Then we have clickable invites through the API on the website:
![](https://cldup.com/IaiPnDEAA6.gif)

and badges for things like markdown documentation:
![](https://cldup.com/jWUT4QFLnq.png)

**Comment by NathanBnm** [comment]
I just firgured out that the "Join chat" link for elementary translation slack instance has expired too.
