### ISSUE TITLE
HIG: Dialog styling is whack

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2258]
![image](https://user-images.githubusercontent.com/611168/65837674-9c426400-e2b7-11e9-880e-0edf6178bffd.png)

**Comment by udithishara** [comment]
Hello, 

Are you looking for a new modal/dialog to be created ?
Is the provided image the design for it ?

If so, i'll be happy to work on this

**Comment by lorenzocafaro** [comment]
Hello,

could the issue be the width calculation here?

https://github.com/elementary/website/blob/601c3abb2fde8e95ab386726ede9ffb4b33cecbf/_styles/docs.css#L473

By reverting to an arbitrary fixed width it works fine:

![immagine](https://user-images.githubusercontent.com/43943230/66713505-0d037900-edac-11e9-9f37-7b602241e937.png)

**Comment by lewisgoddard** [comment]
https://github.com/elementary/website/blob/master/_styles/main.css#L1124
