### ISSUE TITLE
Fridays for Future & elementary OS website?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/website#2262]
Do you already host your website & servers with green and sustainable energy?
If not, I ask you to change!

I don't know if this is a good place for the issue. It's about your project infrastructure. Or would you prefer an email to contact@?

**Comment by lewisgoddard** [comment]
> Digital Ocean uses 11 data center locations across the world to house its infrastructure, but they are not exclusive. Instead, Digital Ocean leases space from other datacenter-focussed companies including Equinix, Telx (owned by Digital Realty Trust), and Interxion. In many cases, the exclusive focus on datacenter development can encourage companies toward greener set-ups, and **all three of these providers source a large portion of their energy from sustainable sources.**
> 
> [Equinix Sustainability Efforts](https://www.equinix.com/resources/infopapers/green-data-centers/)
> 
> [Digital Realty Trust Sustainability Efforts](https://www.digitalrealty.com/about/sustainability)
> 
> [Interxion Sustainability Efforts](https://www.interxion.com/why-interxion/sustainability/)

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your information! But that doesn't really make Digital Ocean a sustainable provider from the ground up, does it? Could you think about switching providers? I am happy to contribute my research work!
