### ISSUE TITLE
Purchase button is not working anymore.

### ISSUE THREAD

**Issue by teterkin** [elementary/website#2288]
## Prerequisites

- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Clicking on "Pay What You Want" button do nothing.

### To Reproduce

1. Go to https://elementary.io/
2. Click on 'Purchase Elementary OS' button.
3. Nothing happens.

I tried different languages, different ammounts, different browsers - it does not work.

I am not alone. See the [twitter](https://twitter.com/AlainSnes/status/1191942654038335488)

### Expected behavior

I want to purchase nice OS.

## Platform Information

- OS: elementary OS
- OS Version: Juno (latest)
- IBM ThinkPad X1 Carbon (Gen.1)
- Yandex browser (latest)

**Comment by lewisgoddard** [comment]
See also:
https://twitter.com/AlainSnes/status/1191942654038335488
https://twitter.com/teterkin/status/1192107029013377024
https://twitter.com/AntonAmelekhin/status/1192022137986572289

**Comment by btkostner** [comment]
This might be due to Yandex browser. It might also be location based. @teterkin Where are you located (what country), and if you can, please paste what the browser console outputs.

**Comment by lewisgoddard** [comment]
It could be Cloudflare handing out outdated copies of files.

**Comment by teterkin** [comment]
@btkostner I tried another browser (Epiphany) with no luck.
I am at Yekaterinburg city, Russia.

**Comment by lewisgoddard** [comment]
Ah, could this be #1876 Russia blocking Cloudflare or ourselves again?

**Comment by teterkin** [comment]
I tried via VPN - same thing.
Also tried to disable all plugins.
Actually it used to work some time ago.

**Comment by cassidyjames** [comment]
I've purged the CloudFlare cache. Is it working now?

**Comment by teterkin** [comment]
It didn't help. But after I installed Firefox it helped.
Also it works in Yandex browser, but in Incognito mode. So it is related to caches.

**Comment by teterkin** [comment]
Also it works after I made Control-F5 (browser refresh).
Thank you for the help!

**Comment by teterkin** [comment]
I finnaly made a purchase!
Thank you for great OS!
