### ISSUE TITLE
The "team" page is not available

### ISSUE THREAD

**Issue by dsmartins98** [elementary/website#2289]
The "team" page for the Brazilians is not available. By clicking on the "Equipe" (Team) button i am redirected to an error page 504. 

## Prerequisites
- [x] I have searched open and closed issues for duplicates.

### To Reproduce
1. Go to 'https://elementary.io/pt_BR/'
2. Scroll down to footer
3. Click on 'Equipe' (Team) button

### Expected behavior
I think the file was renamed or moved and the team forgot of update the directory

### Screenshots or screen recordings

![elementary team page error](https://user-images.githubusercontent.com/22434256/68671040-2e7f8e00-052d-11ea-874b-19c4c63fe9e1.png)

**Comment by btkostner** [comment]
Seems to be affecting all languages

**Comment by lewisgoddard** [comment]
> ### Presence
> Retrieving a workspace's presence with this method is now deprecated. Use `users.getPresence` or [presence subscriptions](https://api.slack.com/docs/presence-and-status#subcriptions) instead.

https://api.slack.com/methods/users.list#presence
