### ISSUE TITLE
CPU usage on main page

### ISSUE THREAD

**Issue by lrweck** [elementary/website#2296]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
CPU usage of the website hovers between 15 to 30 % without doing absolutely nothing.

![image](https://user-images.githubusercontent.com/26086198/70096842-c6413b00-1606-11ea-830a-e3d6280e1ccb.png)

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
Open website on elementary.io

### Expected behavior
Close to no CPU usage since the page isn't supposed to be doing anything.
elementary.io
### Screenshots or screen recordings
https://imgur.com/a/hNjhAap
### Logs
None
## Platform Information
Windows 10, running Chrome 78
Intel Core i7 7500U
nVidia 940MX

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by lewisgoddard** [comment]
I agree that the current website does result in considerable CPU usage on the homepage. I imagine this is animations running and triggering page-wide redraws while it is out of range. DOM updates and repaints should only happen when things are visible.

**Comment by Erbenos** [comment]
I think it's more likely it's the fact that the animations are not GPU accelerated, from the few I have checked - they are not using GPU accelerated CSS properties.

**Comment by Erbenos** [comment]
Also:
https://github.com/elementary/website/blob/b0b6c7fb6cc75230a0f55589aebff6af7c62d0aa/_scripts/pages/slingshot.js#L45
these selectors running every few seconds can be cached.
