### ISSUE TITLE
Double click on the Button "Purchase elementry OS" makes the website unusable

### ISSUE THREAD

**Issue by swathins079** [elementary/website#2311]
Hi,

I have seen an issue when I click on the Purchase Elementry OS button twice. The loading gif on the webpage is still present and it makes the other buttons unclickable.

Regards,
Swathin

**Comment by btkostner** [comment]
If you see the loading bar still, that signifies that there was probably a JS error on the page. Can you please give the OS you are using and the browser. Can you also go back to that page, press F12, click "Console", trigger the loading gif, and then screenshot what you see in terminal. Thank you.

**Comment by lewisgoddard** [comment]
I can reproduce this just by double-clicking faster than the payment modal opens, modal works fine, but the page is permanently stuck behind a second loading screen. We should probably disable the button onclick and re-enable it a second later.
