### ISSUE TITLE
elementary Weblate instance not working

### ISSUE THREAD

**Issue by NathanBnm** [elementary/website#2319]
I think there is an issue with [l10n.elementary.io](https://l10n.elementary.io/). I can't connect anymore and the menus are not reacting.

**Comment by btkostner** [comment]
@NathanBnm Thank you for bringing this to my attention. It should be fixed now. Try hard reloading with `Ctrl` + `Shift` + `R`. Let me know if this keeps being a problem.

**Comment by NathanBnm** [comment]
@btkostner it's working now :wink:
