### ISSUE TITLE
Out-of-date info on elementary OS Development page: How to disable auto-restarting of dock/wingpanel?

### ISSUE THREAD

**Issue by andreasfelix** [elementary/website#2324]
https://elementary.io/docs/code/os-dev#wingpanel

It still says that, one can prevent the wingpanel from auto-restarting by removing it from `/io/elementary/desktop/cerbere/monitored-processes`.

What is the equivalent way of doing this for gnome-session?

**Comment by danrabbit** [comment]
GNOME Session is a lot less tolerant than Cerbere, so you could kill it twice in a row or you could do `killall wingpanel && wingpanel`
