### ISSUE TITLE
Add Coinbase to Funding section

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2334]
We have a Coinbase account and can accept crypto now. Their site says to include this for the embed:

```html
<div> <a class="donate-with-crypto" href="https://commerce.coinbase.com/checkout/d4dbaa95-5a48-42ec-8731-af867e90e4b4"> Donate with Crypto </a> <script src="https://commerce.coinbase.com/v1/checkout.js?version=201807"> </script> </div>
```

Otherwise we can just link to that checkout link with our usual button styling.

**Comment by TheMartes** [comment]
https://github.com/elementary/website/pull/2458
