### ISSUE TITLE
Video in human interface guidelines doc is unavailable

### ISSUE THREAD

**Issue by Pardaigle** [elementary/website#2336]
## Prerequisites
I have searched open and closed issues for duplicates.

## Describe the bug
The video in Build for the "Out of The Box" Experience is unavailable

### To Reproduce

1. Go to [HIG doc](https://elementary.io/fr/docs/human-interface-guidelines#accessible-configuration)
2. Click on the video
3. See error "The account has been deleted"

### Expected behavior
Play the video

### Screenshots or screen recordings
![Capture d'écran du 2020-04-07 15 15 45](https://user-images.githubusercontent.com/410235/78673964-2d3b6d00-78e3-11ea-8da5-775e937758cd.png)

**Comment by lewisgoddard** [comment]
Fixed in #2345.
