### ISSUE TITLE
How to add ‘Open in Terminal’ option to File Manager UX’ right-click menu in elementaryOS - Open Terminal Here  

### ISSUE THREAD

**Issue by bensonkb** [elementary/website#2343]
To open a command line shell in the pantheon File Browser in elementary OS, you need to create a text file and paste code into it.

The location of the file which needs to be created is:

/usr/share/contractor/openinterminal.contract

One command you can use to edit it is:

sudo nano /usr/share/contractor/openinterminal.contract

On elementary OS 5.0 Juno

> [Contractor Entry]
> Name=Open terminal here
> Icon=terminal
> Description=Open terminal here
> MimeType=inode;application/x-sh;application/x-executable;
> Exec=io.elementary.terminal -w %U
> Gettext-Domain=io.elementary.terminal

Reference link : [link](https://www.youtube.com/watch?v=yg16QwupIzk)

**Comment by danrabbit** [comment]
OP I’m not sure what you’re trying to report here, but you can open a Terminal out of the box easily in the Open In menu. There’s no need to create a contract file manually.

Closing as this doesn’t appear to be an issue report regarding the website

**Comment by bensonkb** [comment]
@danrabbit Since it not explicit available in the menu. So many user are not aware of the same and many user are search for the same query like me.
