### ISSUE TITLE
Docs redirects not working as expected

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2348]
It looks like they only work when navigating to the URL including `.php` in the URL, which isn't what we want.

**Comment by lewisgoddard** [comment]
That's an Nginx-level config thing, everything in `/docs` gets passed to `/docs/_mdr/index.php` so it renders markdown.

I would suggest adding:
```
location = /docs/getting-started {
    return 302 https://docs.elementary.io/develop;
}
```
