### ISSUE TITLE
HTML code for Mint colour in Elementary OS HIG is incorrect

### ISSUE THREAD

**Issue by ECFE** [elementary/website#2353]
# Bug
The HTML code for the Mint colour in the [Elementary OS HIG](https://elementary.io/docs/human-interface-guidelines#color) is not listed correct, it corresponds to that of the Lime colour (see below image).

![image](https://user-images.githubusercontent.com/44121370/80304094-4897ea80-87b4-11ea-9899-9787ff2370c5.png)

### To Reproduce
1. Go to [Elementary OS HIG](https://elementary.io/docs/human-interface-guidelines#color)
2. Observe identical HTML colour code for Lime and Mint.

### Expected behavior
The expected colour for the Mint section should be #28bca3 if the colour on the HIG website is correct.

**Comment by micahilbery** [comment]
Sorry that's my bad. I missed this one in my original PR.
