### ISSUE TITLE
"Download later" on mobile.

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#24]
You can't download that shiz on your phone. It'd be useless there.

Maybe we should come up with some kind of clever "download later" mechanism. Send me a link to the download in my email?

**Comment by cassidyjames** [comment]
I agree with the email. Like I mentioned in #26, I think Mailchimp is the way to go. I've used it before, it's widely loved, and it's pretty easy.

**Comment by cassidyjames** [comment]
Caveat: MailChimp is for recurring emails, whereas their product Mandrill is for transactional (one-off) emails. Their API is super simple and we could integrate it on the site with very little hassle.

https://mandrillapp.com/api/docs/messages.JSON.html#method-send-template

First 12,000 emails per month are free, then it's like $0.20 or less per thousand emails: http://mandrill.zendesk.com/entries/21693768

**Comment by cassidyjames** [comment]
Ah, we're gonna need a teeny tiny bit of server-side code for this (to send an API call to Mandrill).

**Comment by cassidyjames** [comment]
If we're using PHP, here're the docs: https://mandrillapp.com/api/docs/messages.php.html

I imagine we'll just want to sent a request to the script on our domain with the person's email address? How do we prevent abuse?

**Comment by lewisgoddard** [comment]
Double-submit a special  cookie using a POST form? Should stop most bots and CSRF. Otherwise, the only way is recaptcha or other puzzles.

**Comment by lewisgoddard** [comment]
To keep the page clean, you could hit an internal API with JavaScript which then calls the mandrill api. I've already stripped down the Mailgun (similar service) API just for password resets, https://github.com/eustasy/browning-a-mailgun-script, so this shouldn't be a major issue.

**Comment by lewisgoddard** [comment]
ping #1287
