### ISSUE TITLE
Link to recommended system specs before purchase

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#2406]
Move recommended system specs to it's own page, and link to it before the purchase flow. Near the download size info maybe

**Comment by ITSRizz** [comment]
The minimum requirements are these:
*64-bit Intel Core i3 or comparable 64-bit dual-core processor;
*4 GB of RAM;
*15-20 GB of free hard disk space;
*Internet access;
*Video resolution 1024 × 768.
But it's not a bad idea to put them on the site too , even if a quick search on the web would be enough to see them (like I did).

**Comment by ITSRizz** [comment]
There is here:
https://elementary.io/it/docs/installation#installation
However, it's not a bad idea to put the requirements on the main page.
Just in case I left you the link
