### ISSUE TITLE
Add retailers to store page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2412]
Following #2411

**Comment by danrabbit** [comment]
I guess a questions is, do we want to add any retailers here or only ones with a referral program? My assumption would be that we'd only feature referral links

**Comment by cassidyjames** [comment]
@danrabbit I feel like any individual terms can be negotiated separately, but just getting them on the page would still be worthwhile. But these two are ones we've had conversations with in the past who were open to some sort of referral, at least.

**Comment by cassidyjames** [comment]
Limiting the scope of this to just get a section and at least one retailer up. We can file issues for other OEMs as we work with them on referral links and whatnot.
