### ISSUE TITLE
Disable Plausible for local development and beta subdomain

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2459]
We probably don't want those stats being grouped in with the others.

**Comment by cassidyjames** [comment]
If we can check what the current domain is in PHP, that would also work. I recently added that to Jekyll templates as another measure to prevent accidental garbage data.

**Comment by lewisgoddard** [comment]
`$_SERVER['HTTP_HOST']` will [usually](http://origin.shiflett.org/blog/2006/server-name-versus-http-host) do what we want.
