### ISSUE TITLE
Remove Google Fonts

### ISSUE THREAD

**Issue by LongJohn-Silver** [elementary/website#2464]
##Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Google has a lot of privacy concerns, and there are plenty of alternatives specifically to this subject, I know that you already use FontAwesome, but you also keep using Gfonts.

N/A

**Describe the solution you'd like**
To stop using completely the service and use a libre alternative instead.

**Existing work**
A lot of websites do not use Gfonts, I think there are too many to list them, and it's kind of irrelevant.

**Describe alternatives you've considered**
https://alternativeto.net/software/google-web-fonts/?license=opensource

**Additional context**
N/A

**Comment by lewisgoddard** [comment]
I'm pretty sure we don't want to move away from those fonts, but we are already distributing the thin variant of Raleway ourselves, so I'm sure we could look at what we're using and strip down.

#### Self-Hosted
- Raleway (100,100italic) :
  - [main.css](https://github.com/elementary/website/blob/master/_styles/main.css) `h1`

#### Google Fonts
- Raleway (800)
  - [home.css](https://github.com/elementary/website/blob/master/_styles/home.css) `#appcenter h1 span` (800)
- Open Sans (300,400,600,700,**300italic**,400italic)
  - [blog.css](https://github.com/elementary/website/blob/master/_styles/blog.css) `#whats-new .byline` (400,600)
  - [countdown.css](https://github.com/elementary/website/blob/master/_styles/countdown.css) `.digit` (600)
  - [docs.css](https://github.com/elementary/website/blob/master/_styles/docs.css) `h1` (600)
  - [home.css](https://github.com/elementary/website/blob/master/_styles/home.css) `.app p` `.slingshot-category` `.slingshot-search-results` `span.search-term, span.cursor` `span.results-title`
  - [main.css](https://github.com/elementary/website/blob/master/_styles/main.css) `html, body` (400) `h2` (300)
  - [pantheon.css](https://github.com/elementary/website/blob/master/_styles/pantheon.css) `h1` (400,700)
- Roboto Mono : 
  - [brand.css](https://github.com/elementary/website/blob/master/_styles/brand.css) `.page-brand .hex`
  - [docs.css](https://github.com/elementary/website/blob/master/_styles/docs.css) `code, pre, kbd` `table` 
  - [pantheon.css](https://github.com/elementary/website/blob/master/_styles/pantheon.css) `.pantheon .window`

**Comment by LongJohn-Silver** [comment]
Sure, I'm not against those specific fonts, only against using Google Fonts to fetch them.

**Comment by cassidyjames** [comment]
An update: we've switched to self-hosting Inter and using it for headings and body copy (as we've done in pre-release images of elementary OS 6). Inter is considered our new brand font, and it gives us a lot of flexibility with regards to weights, even without the variable version. So the site is now Google-Font-Free. :)

**Comment by LongJohn-Silver** [comment]
@cassidyjames Yay! Thank you all for the hard work!
