### ISSUE TITLE
Still no 5.1.6 download?

### ISSUE THREAD

**Issue by spirulin** [elementary/website#2474]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Still no 5.1.6 available to download.

**Describe the solution you'd like**
Updating the site and the .iso.

**Comment by danrabbit** [comment]
It’s a holiday weekend here in the US. Hang tight :)

**Comment by spirulin** [comment]
> It’s a holiday weekend here in the US. Hang tight :)

Yeah, I know. Happy holiday. But the post is a couple of days old and this is the reason I was asking. :)
