### ISSUE TITLE
Don't hardcode the filename of the iso

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#2484]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Whenever a new iso file of elementary OS is uploaded, the name of is file changes. And, because the paragraph in the "Boot Errors" section in [the installation instruction page](https://elementary.io/docs/installation#creating-an-installation-medium) includes it, the whole paragraph gets updated. I feel a little troublesome for this, because my translation for the whole paragraph is removed, although the other portion of the paragraph is not changed at all:

![Screenshot from 2020-07-12 06-22-41](https://user-images.githubusercontent.com/26003928/87234114-cd37f380-c408-11ea-8e99-4a25351c4de0.png)

**Describe the solution you'd like**
The name of an iso file is constant among all languages and will not be translated. So, I guess it should be replaced with a kind of a format specifier (I don't understand PHP, but I mean something like `%s` in Vala or `{#name}` in Ruby).

By doing this, the whole paragraph should become constant regardless of filenames:

```diff
- …, right click on the ISO file in Finder, and select &quot;Burn elementaryos-5.1-stable.20200706.iso to Disc&quot;.
+ …, right click on the ISO file in Finder, and select &quot;Burn {#filename} to Disc&quot;. 
```

In this way, translators no longer have to renew their translation each time when the iso file is updated.

**Existing work**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lewisgoddard** [comment]
Those docs aren't written in PHP, they are in Markdown, which doesn't support this kind of behavior. That is why this hasn't been done until now. I otherwise agree that the installation doc changes monthly with releases at this point, which is quite undesirable.

**Comment by ElDarco** [comment]
> Those docs aren't written in PHP, they are in Markdown, which doesn't support this kind of behavior. That is why this hasn't been done until now. I otherwise agree that the installation doc changes monthly with releases at this point, which is quite undesirable.

Maybe make a console command that will replace text like {#name} in .md files with the desired value? You can run this command every release. I could write that. This would be my first commit to this repository.
