### ISSUE TITLE
Duplicate style guides

### ISSUE THREAD

**Issue by mcclurgm** [elementary/website#2501]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
We have two separate style guides in different parts of the website. There's one in the "Get Involved" page: https://docs.elementary.io/develop/writing-apps/code-style and another in the Developer page: https://elementary.io/docs/code/reference#reference.

They include different information, so it's not clear where to go for what, or that both are available. For example, the guidance to initialize with properties is only in the `docs.elementary.io` page.

It would be nice if we could unify the two pages to create a single style guide so there's one destination and one source of information.

**Comment by schambers** [comment]
Is anyone else working on this? I'm looking for some hacktoberfest issues and this looks like a good one that isn't complex at all and I frequently reconcile documentation at work. If noone has grabbed it yet I'd like to submit a PR on 10/1 for it. 

Thanks

**Comment by mcclurgm** [comment]
I'm not aware of anyone working on this, so I say go for it!

**Comment by schambers** [comment]
Thanks. I'll start on it tomorrow

**Comment by danrabbit** [comment]
I think this has now been resolved

**Comment by mcclurgm** [comment]
Just to confirm, the issue I meant originally has indeed been closed!
