### ISSUE TITLE
Copyright material on the site

### ISSUE THREAD

**Issue by Freddie-Green** [elementary/website#2507]
### Steps to reproduce the behavior

1. Goto elementary.io 
2. Scroll down to "Apps You Need, Without Ones You Don’t."
3. Click on Music

**Comment by Freddie-Green** [comment]
That easter egg for baby shark is quite funny though

**Comment by lewisgoddard** [comment]
![image](https://user-images.githubusercontent.com/831389/91339191-0ae0b800-e7ce-11ea-914e-cd2d21583bd2.png)

**Comment by Freddie-Green** [comment]
@lewisgoddard The album covers are copyrighted

**Comment by lewisgoddard** [comment]
I'm fairly certain those would fall under fair usage, but I was just posting that here to avoid people needing to look the image up themselves.

**Comment by Freddie-Green** [comment]
But about the image itself, if it was Apple then okay but a FOSS project?, NOPE
