### ISSUE TITLE
Ukrainian localization disappeared

### ISSUE THREAD

**Issue by IhorHordiichuk** [elementary/website#2585]
A few days ago https://elementary.io/uk/ started to display text in English instead of Ukrainian text. All of the Ukrainian strings are translated on https://l10n.elementary.io/languages/uk/website/ It's even not included in the drop-down lang. menu at the bottom of the page.

A web site should display text in the Ukrainian language.

1. Go to https://elementary.io/uk/
2. Scroll down to the end of the page
3. Click on the drop-down lang. menu

**Comment by lewisgoddard** [comment]
The drop down and making translations available are both at [`_backend/Lib/L10n.php` Line #107](https://github.com/elementary/website/blob/master/_backend/Lib/L10n.php#L107)

**Comment by lewisgoddard** [comment]
Should this be "українська" ?

**Comment by IhorHordiichuk** [comment]
> Should this be "українська" ?

yes

**Comment by IhorHordiichuk** [comment]
@lewisgoddard thank you for your quick action 👍
