### ISSUE TITLE
Add YouTube to header

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#2620]
We don't currently link to our YouTube channel and we should

**Comment by lewisgoddard** [comment]
What is our YouTube channel link?

**Comment by danrabbit** [comment]
https://m.youtube.com/user/elementaryproject

Thanks Lewis!

**Comment by CrownCrafter** [comment]
Added the icon from Bootstrap class `fab` in my Pull request. I changed only one line in _templates -> header.php, but the reviews fail...

**Comment by CrownCrafter** [comment]
https://github.com/elementary/website/pull/2625
