### ISSUE TITLE
Redesign the Support page for GitHub Discussions

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#2630]
## Problem

Currently the support page is built around guiding users towards StackExchange. It sounds like we want to use GitHub Discussions instead since that's one less login, it's easier to convert issues into discussions or reference discussions in issues etc.

## Proposal

We need to remove the references to StackExchange from the support page and at a minimum replace the existing links with GitHub Discussions links. We also need to remove the StackExchange link from the header

**Comment by tintou** [comment]
One thing to take into account: Developers should be able to not getting any notification regarding Discussions. A developer isn't a support person.

**Comment by lewisgoddard** [comment]
I'm not sure how this is going to work without causing a lot of extra traffic over here. A lot of StackExchange questions are quite basic and repetitive, and around release time you are talking several thousand posts.

**Comment by danrabbit** [comment]
@tintou You can choose to disable notifications for discussions at https://github.com/watching

@lewisgoddard Yeah I think theoretically we can do a better job moderating on GitHub so it hopefully won't get as out of control as StackExchange has gotten. Marking duplicates etc. But also there are a lot of things on StackExchange that should probably be filed as issue reports instead and aren't really questions, so it'll be easier to direct people to do that and close those posts. Or vice versa, I've already converted a few issues into discussions which has been convenient
