### ISSUE TITLE
Incorrect capitalization for "Os Dev" page title

### ISSUE THREAD

**Issue by avojak** [elementary/website#2631]
## What Happened

The "Os Dev" page is incorrectly capitalized in the title (sorry this is super minor - I would open a PR myself, but I'm not sure how the title gets determined from the markdown files).

## Expected Behavior

Expected to show as "OS Dev"

## Steps to Reproduce

1. Navigate to https://elementary.io/docs/code/os-dev#elementary-sdk and look at the title in the browser tab

### Logs

N/A

## Platform Information

N/A

**Comment by TiagoCavalcanteTrindade** [comment]
Its too hard to change it, the title of all pages is defined capitalizing the name of the file and changing "-" to " ";

**Comment by cassidyjames** [comment]
Since we've moved the documentation to docs.elementary.io (and these pages only exist to direct people there), I think this is safe to close.
