### ISSUE TITLE
official process for major version updates

### ISSUE THREAD

**Issue by jwillikers** [elementary/website#2653]
## What Happened

Confusion over the process of upgrading between major versions.
This is a frequent source of questions on the elementary OS StackExchange and it would be nice to point users to a place on the official website.

## Expected Behavior

I expect there to be official documentation that mentions how to upgrade between major versions of elementary OS.
I think its expected that a clean install is the official way to accomplish this and perhaps it is mentioned in previous blog posts, but digging through those is inconvenient.
Perhaps just a note in the existing documentation on updates [here](https://elementary.io/docs/learning-the-basics#updating) which distinguishes the difference between regular system updates and major version updates would provide users much needed insight.

**Comment by jgildred** [comment]
Agree. I expect that Image Burner is the preferred tool for existing ElementaryOS users, instead of Etcher, and this is not described in the installation page on docs. Also, would be helpful to have a link to the installation instructions next to the home page down load link so folks don't have to fish for it at a minimum. Surprised that this is not a higher priority as OS6 launches.

**Comment by jgildred** [comment]
Also, is there any way to install the OS without wiping the existing system partition? I think the default install on previous version (5.x) does not create a separate partition for data volumes so you basically cannot upgrade an existing system if his has any apps/data that you want to keep. You can only do a clean install. This should be clearly spelled out in the installation instructions, but more importantly we need an upgrade capability that does not wipe the system.

**Comment by jgildred** [comment]
@danrabbit I'd love to help here. At least to provide clarity on the install process, especially for existing users who are upgrading.

**Comment by cassidyjames** [comment]
We have a project to attempt to address OS upgrades: https://github.com/orgs/elementary/projects/103/views/1

For now, this is the official guide which is linked to from the FAQ for each release and on the installation guide: https://github.com/elementary/os/wiki/Release-Upgrades
