### ISSUE TITLE
Unable to interact with the "Pay what you want" menu in the website.

### ISSUE THREAD

**Issue by punstar** [elementary/website#2669]
###  What Happened
-I tried to download the ISO from elementary.io, after a bit of trying I couldn't get the "Purchase elementaryOS" button to turn into the download repositories button, choosing any of the 10, 20, 30 dollar button doesn't show the "continue with purchase" button either, they seem to be unresponsive and don't add or change any details on the website-->

###  Expected Behavior
-When selecting a price range on the "Pay what you want" menu on the website, the "Purchase elementaryOS" button should change according to what was inputted-

###  Steps to Reproduce
1. Log into elementary.io
2. Try and interact with the "Pay what you want" menu in any capacity

### Platform Information
 Windows 10, with chrome browser, later tried on firefox browser, then tried on a Macbook with macOS Big Sur 11.02 on the safari browser, they all experienced this.
 **Relevant hardware information such as graphics drivers, unconventional setups, etc.**
Not any unconventional setups, just a windows 10 PC that would have very little interferance going to the internet, same for a macbook running the latest macOS release.
Might be a server instability error in my area? I'm from the Paraguayan/Brazilian amazon area, Not sure if it extends to the entirety of Latin America, co-worker from Venezuela seems to download the ISO and browse the site just fine.

**Comment by wolfiediscord** [comment]
Can confirm. Running Debian 10 with Ungoogled Chromium and Firefox ESR. I tried on multiple devices too, plus using a data connection. It appears to be an issue with their site. In the Firefox console, I get this as a result:
```
Loading failed for the <script> with source "https://stats.elementary.io/index.js".
Loaded slingshot.js
Loaded blog.js
```
It appears that download.js is never loaded, which means the download button doesn't work.

**Comment by danrabbit** [comment]
@wolfiediscord thanks for providing that additional information! Are you intentionally blocking JavaScript or is this unexpected for you?

**Comment by wolfiediscord** [comment]
> @wolfiediscord thanks for providing that additional information! Are you intentionally blocking JavaScript or is this unexpected for you?

I am not blocking JavaScript. I have tried disabling and enabling uBlock Origin, but to no avail. It seems that download.js is just never loaded.

**Comment by neilbryson** [comment]
Seems to be a network issue where some files won't download on certain locations. Without a VPN, I couldn't interact with the "Pay what you want" form but when set to some locations like US or NZ, it works normally.

**Comment by roberto-ayala** [comment]
I am from Chile, and I has the same problem only on chrome, safari is working fine. Testing on mac.

Chrome Web Console
```
jQuery Loaded common.js:1
Loaded slingshot.js slingshot.js:1
Loaded blog.js blog.js:1
```
Safari Web Console
```
[Log] jQuery loaded (common.js, line 1)
[Log] Stripe loaded (download.js, line 1)
[Log] jQuery.leanModal2 loaded (download.js, line 1)
[Log] Loaded slingshot.js (slingshot.js, line 1)
[Log] Loaded blog.js (blog.js, line 1)
[Log] Loaded showcase.run.js (showcase.run.js, line 1)
[Log] Sitewide configuration loaded (download.js, line 1)
[Log] Config at loading: (download.js, line 1)
[Log] {release: {title: "Hera", version: "5.1.7"}, previous: {title: "Juno", version: "0.4.1"}, keys: {sentry: "https://5dc4884b382c42b3a0d6440797af3454@sentry.io/101325", stripe: "pk_live_ZtcG6SqsVtMbTuJARKujZ0lE"}, user: Object} (download.js, line 1)
[Log] Config at download.js: (download.js, line 1)
[Log] {release: {title: "Hera", version: "5.1.7"}, previous: {title: "Juno", version: "0.4.1"}, keys: {sentry: "https://5dc4884b382c42b3a0d6440797af3454@sentry.io/101325", stripe: "pk_live_ZtcG6SqsVtMbTuJARKujZ0lE"}, user: Object} (download.js, line 1)
[Log] Loaded download.js (download.js, line 1)
```

**Comment by jacobhempel** [comment]
this still seems to be broken, can't interact with the menu using Firefox on Windows, Edge on Windows, or Firefox on macOS

**Comment by wilfredinni** [comment]
It seems they don't care. What a shame

**Comment by danrabbit** [comment]
@roberto-ayala can you still reproduce the issue after clearing your browser cache in Chrome?

**Comment by roberto-ayala** [comment]
Still broken, now broken in all browsers on mac. Testing with disabled cache.

These errors appear in the web console:

```
[Error] Error: Cannot find module "core-js/library/es6/promise"
[Error] Error: Cannot find module "core-js/library/es6/object"
```

**Comment by danrabbit** [comment]
Great, thanks! Looks like our web team has identified the issue. Hang tight

**Comment by roberto-ayala** [comment]
I cloned the project and did a test, it is only necessary to change:

```core-js/library/es6```  by ```core-js/es```


on files:
_scripts/widgets/payment.js
_scripts/polyfill.js

Do you need me to submit a pull request or do you already have it resolved?

**Comment by danrabbit** [comment]
@roberto-ayala If you have time that would be helpful, thanks :)

**Comment by btkostner** [comment]
The website is updated and deployed with the changes that @roberto-ayala made :confetti_ball:. There shouldn't be any more console errors. Please let me know if that didn't fix that for you and I'll reopen the issue.
