### ISSUE TITLE
Add JS requirement banner

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2672]
## Problem

If you disable JS, you're unable to download the OS (or at least pay for it afaik).

## Proposal

We add a "Portions of this site require JavaScript" banner that is then hidden with JS.

## Prior Art

Super common on the web, but System76 has a decent version. We could probably be a _little_ more subtle though.

![Screenshot from 2021-03-18 10-09-21](https://user-images.githubusercontent.com/611168/111658515-06afd280-87d2-11eb-93d8-7296ae8aacec.png)

**Comment by btkostner** [comment]
For what it's worth, this is what the store looks like with JS disabled

![image](https://user-images.githubusercontent.com/3385679/111666322-3910fe00-87d9-11eb-8e36-47fa459a4dd8.png)
