### ISSUE TITLE
Redirect HIG to new HIG

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2677]
We have ported the HIG to GitBook alongside our other docs, and started making large improvements. There are a few regressions, but we should probably still redirect the old HIG from here to the new one because all the effort is being put in there.

https://docs.elementary.io/hig/

We should also transfer all HIG issues from this repo to [elementary/hig](https://github.com/elementary/hig).

**Comment by MrPotatoBobx** [comment]
The new HIG is much more readable, I definitely like the new layout
