### ISSUE TITLE
Style guide outline entry in reference page contains broken link

### ISSUE THREAD

**Issue by mcclurgm** [elementary/website#2684]
## What Happened

In the reference page, the left sidebar contains a broken link for the style guide section. I assume this is a result of updating it to link to the new style guide. Its link points to `https://elementary.io/docs/code/reference#undefined`, when it should point to a valid header.

## Expected Behavior

It should either focus the header or take me to the new style guide

## Steps to Reproduce

1. Go to the reference page (https://elementary.io/docs/code/reference#reference)
2. Click on the "Code Style" entry in the left sidebar
3. I've seen 2 things here: either it takes you to an error page, or it navigates nowhere because it's pointing to a `/reference#undefined` section.

**Comment by cassidyjames** [comment]
I think this has been addressed with moving more things over to GitBook? If not feel free to re-open and clarify.
