### ISSUE TITLE
The Purchase Elementary Button wont work

### ISSUE THREAD

**Issue by KlassiC-Man** [elementary/website#2705]
### System information

- **Operating system**:  Ubuntu 
- **Operating system version**: 20.04 LTS
- **Browser**: Chrome
- **Browser version**: 90.0.4430.93
- **Enabled Browser Extensions**: I dont have any extensions

**Thank you very much hope you guys sort the problem at the earliest!**

**Comment by btkostner** [comment]
Can you press F12, then "Console", refresh the page, and paste anything you see in the logs here please.

**Comment by KlassiC-Man** [comment]
Wait a sec...
I just tried downloading the ISO from another computer of mine and it worked I don't know why it wasnt working on the first computer should I still tell you whatever gets logged in the console? @btkostner

**Comment by btkostner** [comment]
If you get the chance, please do.

**Comment by btkostner** [comment]
Do you know what version of chrome you are using? It should be in the "About Chrome" window.

**Comment by KlassiC-Man** [comment]
Yeah I have mentioned that in the issue itself when I opened it. It's Version **90.0.4430.93**

**Comment by btkostner** [comment]
Whoops sorry. I missed that. You're browser is up to date so it's nothing weird like being unsupported 🤔

**Comment by KlassiC-Man** [comment]
Yeah so what can I do? Even though you dont need to worry much I got my elementary OS already and am loving it.
