### ISSUE TITLE
Make background on favicon a circle or rounded square

### ISSUE THREAD

**Issue by hwittenborn** [elementary/website#2715]
## Problem

The favicon currently is the Elementary OS logo on it's blue color, but it's just a solid square in the background. This doesn't look very pleasant to the eyes, and makes it feel less like a logo, and more just like a cropped picture.

## Proposal

Make the border either a circle or rounded square. I've made some basic mockups in GIMP, but the edges are a bit rough:

![favicon](https://user-images.githubusercontent.com/74838472/118383999-7d95fb80-b5c8-11eb-8416-6a6146dd2865.png)

![favicon](https://user-images.githubusercontent.com/74838472/118384092-0ad95000-b5c9-11eb-9895-7e72ce5323ce.png)

## Prior Art

![favicon](https://raw.githubusercontent.com/elementary/website/master/favicon.ico)

**Comment by deleanuradu** [comment]
Hi! Would this be a good fit?
![favicon](https://user-images.githubusercontent.com/34350222/133610644-e614303e-030d-482d-9c69-995cada5e5eb.png)

**Comment by hwittenborn** [comment]
Yep, that looks lovely! I preferred the circle and was just providing the other as a backup, so that works out great :)
