### ISSUE TITLE
Website - Become a Developer - Design - Dead LInk

### ISSUE THREAD

**Issue by DaneAU** [elementary/website#2716]
## What Happened
- Simple page not found

## Expected Behavior
- The user would arrive at the page outlining the design best practices

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/1080820/118391787-75e25f80-b679-11eb-9820-ee1692e47c08.png)

1. Visit the Homepage of elementary.io
2. Clicked 'Become a Developer' halfway down the page - OK
3. Arrived at https://developer.elementary.io/ - OK
4. Clicked 'Design' 
5. Redirected to https://elementary.io/docs/human-interface-guidelines 
6. Observe The page you're looking for can't be found

### Logs
- NA

## Platform Information
- Chrome Brwoser

**Comment by Brin-o** [comment]
Should link to https://docs.elementary.io/hig/

**Comment by yogasukma** [comment]
it should be simple fix, but it seems https://developer.elementary.io/ are not on this repo.

**Comment by xcodz-dot** [comment]
It was found on 16 may and had not been fixed yet. Any idea where does the code for developer.elementary.io lies cause imo it is important to fix early. I came here to raise an issue for the same and found this.

**Comment by lewisgoddard** [comment]
Fixed the redirect.
