### ISSUE TITLE
Store redirect isn't working

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2719]
https://elementary.io/store/ should redirect to https://store.elementary.io, but appears not to be working. Might need server-side changes?

**Comment by yogasukma** [comment]
Hi @cassidyjames i tried to involved on this one, but i checked the site and found that the navigation on the top side are already linked to https://store.elementary.io/ so no need to redirect, since there is no way people go to https://elementary.io/store/. What do you think?

**Comment by cassidyjames** [comment]
@yogasukma there are old links e.g. on social media that point to `/store`, which is where the need originates.
