### ISSUE TITLE
SDL Valadoc link is broken

### ISSUE THREAD

**Issue by mcclurgm** [elementary/website#2753]
## What Happened

When I click the link to the SDL library, I get a 404 on valadoc.org.

## Expected Behavior

The link should go to the correct page.

## Steps to Reproduce

1. Go to https://developer.elementary.io/
2. Scroll to the bottom, at the end of the Vala section.
3. Under the "UI and Drawing" heading, click SDL.
4. You'll arrive at a 404 page.

**Comment by quazi-irfan** [comment]
I am assuming the link should be pointing to : https://valadoc.org/sdl2/SDL.html

But I don't know which repo to look into to send a pull request.

https://github.com/elementary/website/blob/master/developer.php seems to point to the http link of the page.

**Comment by cassidyjames** [comment]
Oops, forgot cross-repo `fixes` links don't auto-close issues. :)
