### ISSUE TITLE
The magnet link for downloading elementary OS uses a broken tracker

### ISSUE THREAD

**Issue by unbeatable-101** [elementary/website#2778]
## What Happened

The tracker used (udp://tracker.publicbt.com:80/announce) is dead

## Expected Behavior

A working tracker such as udp://tracker.opentrackr.org:1337/announce is used

## Steps to Reproduce

1. Go to https://elementary.io/
2. Click download
3. Click the magnet link
4. Open in your torrent client and see the tracker won't connect

**Comment by lewisgoddard** [comment]
There are several trackers for redundancy. I believe ccc.de and publicbt.com might be dead.
 
```
https://ashrise.com:443/phoenix/announce
udp://open.demonii.com:1337/announce
udp://tracker.ccc.de:80/announce
udp://tracker.openbittorrent.com:80/announce
udp://tracker.publicbt.com:80/announce
```
