### ISSUE TITLE
pt_BR installation instructions page is blank

### ISSUE THREAD

**Issue by o-alquimista** [elementary/website#2799]
https://elementary.io/pt_BR/docs/installation

```
Uncaught TypeError: currentSection is undefined
```

Other translations load fine, even Portuguese (Portugal). Only pt_BR fails.

The page is blank:

![Captura de tela de 2021-08-10 22-37-07](https://user-images.githubusercontent.com/25424263/128956461-ffe63151-b10e-45fc-8ede-7ab0b105d3bf.png)

**Comment by ryonakano** [comment]
I found a format error in a Brazilian Portuguese translation and fixed it just now.

https://l10n.elementary.io/translate/website/docs-installation/pt_BR/?checksum=fca907c1e1343945

Not 100% sure but this might fix the issue. Let's wait until the website loads the latest translation file.
