### ISSUE TITLE
Remove _lang/*/SECURITY.json?

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#2823]
[SECURITY.md](https://github.com/elementary/website/blob/master/SECURITY.md) seems to be marked to generate translation files into `_lang/*/SECURITY.json`. But this file does not seem to be displayed in the actual website. Maybe we can prevent `SECURITY.md` from generating `_lang/*/SECURITY.json`?

**Comment by lewisgoddard** [comment]
Relevant code: https://github.com/elementary/website/blob/master/_backend/Lib/L10n.php#L21
