### ISSUE TITLE
Navigation bar responsiveness

### ISSUE THREAD

**Issue by Xristodoulos99** [elementary/website#2838]
The navigation bar on the website , seems to stay the same when it doesn't fit in the page (small monitor or mobile devices) with a scroll so everything is accessible.
I would suggest that the Navigation changes it appearance when it doesn't fit to maybe a drop menu or some other method so the options are not so packed up together

Thanks

**Comment by Xristodoulos99** [comment]
I could work on it by the way

**Comment by btkostner** [comment]
I'm going to close this as a duplication of https://github.com/elementary/website/issues/1344

**Comment by Xristodoulos99** [comment]
Oh sorry it was too far down didn't notice it
