### ISSUE TITLE
Inaccurate information in docs

### ISSUE THREAD

**Issue by Pound-Hash** [elementary/website#2839]
## What Happened
The information under [Reporting Bugs](https://elementary.io/docs/code/reference#reporting-bugs) in the [Reference](https://elementary.io/docs/code/reference#reference) documentation is inaccurate.

## Expected Behavior
Specifically, the following sentence doesn't apply,

> If you open System Settings, select "About" and "Report a Problem", you can select the app to submit an issue.

## Steps to Reproduce
![docs](https://user-images.githubusercontent.com/51193876/134404929-38c44feb-a3d5-4da7-8d24-5d327c873d11.png)

**Comment by lewisgoddard** [comment]
New documentation is now available here: https://docs.elementary.io/contributor-guide/feedback/reporting-issues
