### ISSUE TITLE
I need an ISO for Elementary OS 5.1.7

### ISSUE THREAD

**Issue by LIlaUraraka** [elementary/website#2866]
### Expected behavior

Describe what you expected to happen.
download the ISO I need
### Actual behavior
link expired page
Describe what actually happened, being specific about how this differs from your expectations.

### Steps to reproduce the behavior

1. 
2. 
3. 

### System information

- **Operating system**: Windows 10
- **Operating system version**: 21H1
- **Browser**: Edge
- **Browser version**: 94
- **Enabled Browser Extensions**: none

**Comment by comradekingu** [comment]
Found it on https://web.archive.org/web/20201028000415/https://elementary.io/ however the magnet is dead
Maybe one of the trackers will announce it.

**Comment by lewisgoddard** [comment]
Why specifically 5.1.7? Is this following a link from a download receipt from an old version?

**Comment by lewisgoddard** [comment]
I think the web.archive.org is mangling the link in an attempt to archive it.
