### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by satviksinha12** [elementary/website#2908]
### What Happened?

Hi,the download buttton is not working on the website wether you click 1 dollar and purchase or set custom to zero . It just isn't working from some users. Tested on microsoft edge and brave browser.

### Steps to Reproduce

1- Go to website
2- Select 1 dollar
3-Click on purchase elementrary os

### Expected Behavior

When cutom value set to zero , the website should have redirected to download link but it didn't

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Windows 10 21H2
```

### Hardware Info

Nvidia MX130
Intel I5 8TH gen
256GB ssd

1TB Hdd

**Comment by tomasklaen** [comment]
Same issue here, and from looking at twitter, tons of other people are also experiencing this.

From a glance at the console, it seems like there is something trying to use jQuery before it finished loading:
![image](https://user-images.githubusercontent.com/47283320/146642652-391f3201-c1c4-40b7-bc68-08584a2106b5.png)

**Comment by satviksinha12** [comment]
For time being you guys can provide an alternate download link

**Comment by icflorescu** [comment]
This is totally unrelated to the browser and/or OS.
It's **simply NOT working**.
Providing an alternate download link would be a great idea.

**Comment by keyilan** [comment]
Can confirm it doesn't matter what OS or browser. Tried on Arch, macOS, Windows using Firefox, Brave, Chromium/Chrome, Safari.

**Comment by alirzaev** [comment]
Digged into the source code of the website and found a mismatch:

Expected at https://github.com/elementary/website/blob/master/_scripts/config.js#L18 this:
```js
console.log('Sitewide configuration loaded')
```

but got this (inspected in browser):
```js
return console.log('Sitewide configuration loaded'),
```

![изображение](https://user-images.githubusercontent.com/46632504/146678349-9d19655a-4bac-4fea-aeb0-3a9c48ffe876.png)

**Comment by satviksinha12** [comment]
So will anyone do a fix for this?

**Comment by Devynko** [comment]
The download button stopped working in firefox for me, but works in chromium.

**Comment by mygodlyname** [comment]
Not working on Win10 using Chrome. It does work using Edge.

**Comment by StylusEater** [comment]
@satviksinha12 This appears to be fixed.
