### ISSUE TITLE
Consistent Copy for Project and Website

### ISSUE THREAD

**Issue by StylusEater** [elementary/website#2929]
### Problem

Issue #2894 suggests adjusting web copy. If the PR is accepted the https://github.com/elementary project description should also be updated. It's currently set to: 

> We design and develop elementary OS—the fast, open, and privacy-respecting replacement for Windows and macOS—plus AppCenter, the pay-what-you-want app store.

### Proposal

Keep copy consistent.

**Comment by StylusEater** [comment]
I suspect there are also other locations like https://mastodon.social/@elementary that would need to be fixed if the proposed language is adopted.

**Comment by cassidyjames** [comment]
As mentioned in #2894, the wording is intentional.
