### ISSUE TITLE
Norka app's screenshot is not loading (404 error) 

### ISSUE THREAD

**Issue by SoulRiets** [elementary/website#2949]
### What Happened?

Accidentally found a bad screenshot in Appcenter overview on your website. 
![image](https://user-images.githubusercontent.com/60113596/151422889-99b6e8f7-9088-49d6-bfd4-ef08f604ffeb.png)

### Steps to Reproduce

1. Visit https://appcenter.elementary.io/com.github.tenderowl.norka/

### Expected Behavior

There has to be a screenshot

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by btkostner** [comment]
This seems to be due to norka renaming the file and not hard linking the screenshot to a commit.

**Comment by RMcNeely** [comment]
Looks like this has been fixed visiting the link. Issues with AppCenter web should actually be filed to @elementary/appcenter-web repo
