### ISSUE TITLE
Slack link for translation is broken

### ISSUE THREAD

**Issue by pikhosh** [elementary/website#2982]
### What Happened?

The Slack link for translation is broken and displays the "This link is no longer active" error.

### Steps to Reproduce

I just went to [this page](https://elementary.io/docs/translation-guide#translation-guide) and clicked on the Slack link! 😂

### Expected Behavior

Allow me to go and ask for permission to save translations on Weblate! 😂

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by 1280px** [comment]
Same for me. I just want to fix a broken translation string no one cares about, let me in!
