### ISSUE TITLE
Facebook button links to a non-existent website

### ISSUE THREAD

**Issue by JohnDumpling** [elementary/website#3006]
### What Happened?

After clicking on the Facebook icon in the top right corner of the website's homepage, it sends me to this link (basically, it says that the website was not found and could have been removed):
![obrázok](https://user-images.githubusercontent.com/89086803/167309747-b0e91311-fa6d-4be5-84d8-59bc16cac399.png)

### Steps to Reproduce

1. Go to elementary.io
2. Click on the Facebook icon in the top right

### Expected Behavior

The link should be removed, if elementary no longer posts on Facebook.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by owen-laney** [comment]
Hmm, it seems like the link is broken. Maybe the account was deleted? I found a different account [here](https://www.facebook.com/ElementaryOss/), so maybe the link could be updated to that.
