### ISSUE TITLE
Translations join chat link issue

### ISSUE THREAD

**Issue by Kurogani** [elementary/website#3047]
### What Happened?

Translations join chat link isnt working becouse the Slack chat link is not active

### Steps to Reproduce

Click on join chat on the translation section

### Expected Behavior

The link isnt working

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
We should change the redirect of `https://translators-slack.elementary.io/` to `https://matrix.to/#/%23elementary-l10n%3Amatrix.org`

**Comment by danrabbit** [comment]
It should be already done, but we need to deploy I think @lewisgoddard?
