### ISSUE TITLE
Responsive Navbar for Mobile Sizes

### ISSUE THREAD

**Issue by Ishan-pro** [elementary/website#3056]
### Problem

The navbar currently is not responsive on mobile sizes and everything seems to clutter up there. It is will lead to bad ueser experience.

### Proposal

The website should support mobile sizes via a hamburger which when clicked opens up with these links.
I will personally recommend something which opens fullscreen. This along with a sticky navbar will be cool, but even if you don't try out the sticky option (like github) the responsiveness is a must

### Prior Art (Optional)

Some examples are -

1. [Khan Academy](https://www.khanacademy.org/)
2. [Github](https://github.com)

**Comment by Adarshsingh7** [comment]
yes,mobile view will look beautiful by adding a slide-bar for social media icons in mobile view. 
The slide bar icon can be simply three horizontal line which many of the popular website use in the website

**Comment by colinkiama** [comment]
I can do this. I'll go for something similar to GitHub's solution.

**Comment by RMcNeely** [comment]
Is the idea here to add a  hamburger menu or some dropdown type menu instead of the sliding menu that currently exists on mobile?
