### ISSUE TITLE
Upgrade Node

### ISSUE THREAD

**Issue by RMcNeely** [elementary/website#3083]
### Problem

Currently, the website runs on Node 12 which hit end of life sometime around 2020 (it has actually scolled off of the releases page of Node's Github). This means that the version of node and npm are no longer receiving security fixes and improvements. We should switch to a newer supported version of Node and NPM with the project. As of the time of this issue the current LTS is Node 16 however it is scheduled to become the maintenance release before the end of the month. 

Node release cycle:
https://github.com/nodejs/release#release-schedule

### Proposal

Adopt either Node 16 or Node 18.

**Comment by Belta-shazzar** [comment]
@RMcNeely please assign me this. I would like to take up the project

**Comment by RMcNeely** [comment]
I don't think you can assign issues but if you file a PR you can request a review and I'll try to prioritize it.

**Comment by lewisgoddard** [comment]
I _know_ that upgrading Node on the current server breaks everything, but it's an older release of Ubuntu LTS (16.04.7) so it might be a problem with that. If Node 18.x is going to be LTS we should probably try and move to that.

**Comment by RMcNeely** [comment]
Is the breakage a result of the way Node is installed on the server or just that there are issues compiling with newer releases? I have been building with Node 16 LTS locally but I haven't noticed any issues so far.

**Comment by lewisgoddard** [comment]
It's probably intertwined with the outdated base and outdated node and npm all on that platform.

**Comment by davidmhewitt** [comment]
Blocked by #3101

**Comment by davidmhewitt** [comment]
This is now complete. We're running Node 18 on the server
