### ISSUE TITLE
ElementaryOS 6.1 ISO is marked as RC?

### ISSUE THREAD

**Issue by sryze** [elementary/website#3092]
### What Happened?

The file name is `elementaryos-6.1-stable.20211218-rc.iso` i.e. it has both `stable` and  `rc` in the name (supposedly meaning Release Candidate), which is confusing - it's not clear if it's a stable build or not. Could you please fix it?

### Steps to Reproduce

1. Go to elementary.io
2. Click Purchase / Download

### Expected Behavior

Expected to download a stable build

**Comment by lewisgoddard** [comment]
I think this is because this was originally an RC that was promoted to stable, and now it is stuck like it because changing it is quite manual across file hosting and torrent seeding. Instead, this will probably just get fixed when 7.x comes out.

**Comment by sryze** [comment]
Looks like 7.0 has the same issue
`elementaryos-7.0-stable.20230129rc.iso`
