### ISSUE TITLE
Migrate to the latest stripe checkout

### ISSUE THREAD

**Issue by danirabbit** [elementary/website#3097]
### Problem

We're still using the legacy Stripe checkout which presents as a modal on our website and doesn't support newer secure payment methods

### Proposal

Migrate to the new stripe checkout which supports the latest payment methods: https://stripe.com/docs/payments/checkout/migration

**Comment by danirabbit** [comment]
I believe this would automatically close #998

**Comment by Derek52** [comment]
Hi, I think I may be able to do this. I had to get familiar with Stripe's API for a client recently. If you look at the docs [here](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=checkout), you'll see there are 2 ways to use Stripe checkout. You can load a customizable checkout page directly from Stripe, or build your own custom "payment flow".

If you are happy with the first approach, I think I can implement that pretty easily.

And this doesn't automatically close #998, but It's a trivial couple of extra steps to take care of that too.

**Comment by RMcNeely** [comment]
How much work would it be to have the later option where you have a "payments flow" if the alternative is to redirect to a checkout page? Would this be using the newer checkout methods?

**Comment by Derek52** [comment]
The "payment flow" approach is basically creating a new modal. Both approaches use the newer checkout methods. The "custom payment flow" approach shouldn't be too much more work than just using the checkout page redirect approach. The documentation for the payment flow approach is [here.](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements) I'm just not super familiar with PHP, and would feel less comfortable attempting to implement that approach myself.

**Comment by RMcNeely** [comment]
I think the most important thing is that you can dynamically set the payment size. My thought process for keeping the modal is that it makes it easy to transact the sale without navigating elsewhere. That said if we were going to reuse the page it wouldn't be a custom one off effort. @danirabbit do you know what the store website uses for Stripe integration? (if that's also out of date).

**Comment by Derek52** [comment]
Dynamic payment size is easy. So is customizing the page. It's laid out for you, you can just configure the layout's theme, and add a logo and a couple other quick things. They have a sample demo that lets you also play around with the config options [here.](https://checkout.stripe.dev/)
