### ISSUE TITLE
Use Stripe Receipt Emails

### ISSUE THREAD

**Issue by danirabbit** [elementary/website#3109]
### Problem

We’re currently sending custom receipt emails through mandrill and I’m not sure why? I’m wondering if it has something to do with us not creating customers before and needed a way to download again for free? Or is it just to add social links?

We're currently paying $20/mo for a block of transactional emails, which isn't a ton of money but like if we don't have to be paying it it's worth thinking about not imo

### Proposal

Stripe has built in receipts that send from our domain and include a support link etc
![5986310A-5229-4E0A-93EE-43BA2713197C](https://user-images.githubusercontent.com/7277719/200417496-20dc4451-33d7-4d7d-b510-59199ca8e94f.png)

### Prior Art (Optional)

This is the current email that’s more verbose and has some other links
![A878CDDB-4BA1-4E5B-9686-759AFDC13DA2](https://user-images.githubusercontent.com/7277719/200418075-c90e75e9-5497-4b36-933b-dab2e8f22553.png)
![1BB82DC5-EFFA-4FBF-B280-BBC624670E3D](https://user-images.githubusercontent.com/7277719/200418091-380750aa-cb0a-4050-8495-251379d2e5ae.png)

**Comment by davidmhewitt** [comment]
We've switch to Stripe emails recently
