### ISSUE TITLE
Old documentation link in causes confusion in Get Involved (Design) section

### ISSUE THREAD

**Issue by Suzie97** [elementary/website#3136]
### What Happened?

In the Design section of the Get Involved page, there is this [Learn More](https://elementary.io/docs/code/reference#proposing-design-changes) which links to the old documentation site. That site mentions that the documentation has been moved over to a new site.

![8DC8724A-4865-4358-ABB0-965BC1D2C06A](https://user-images.githubusercontent.com/68198116/205762237-ac5d9dca-b8e5-4094-98d9-a81041517a9d.jpeg)

#### The Problem
![DA082448-46F4-4A82-B66D-CA46589AF8DC](https://user-images.githubusercontent.com/68198116/205762653-46702001-a2e6-468a-848d-8a7fa3f6f431.jpeg)

As seen in the picture, the purpose of that link is to show information about the design workflow so that contributors don’t have to find it out for themselves in the documentation. But since the old documentation only links to the new docs site and doesn’t actually take them to the exact location, it renders the purpose of the link useless.

### Steps to Reproduce

1. Go to https://elementary.io/get-involved#design.
2. Click on the Learn More link in the first paragraph. 
![E75EC86B-AA56-4CFB-A428-6416D0171DC7](https://user-images.githubusercontent.com/68198116/205763465-906cd56a-620d-4e97-82ee-042bd756036a.jpeg)
3. The old documentation site will be displayed which only mentions that the documentation has been moved to a new site and provides links to it.

### Expected Behavior

The Learn More link should directly navigate to the promised section in the new docs.

**Comment by talhatahir** [comment]
Added a fix for this.

**Comment by RMcNeely** [comment]
PS @talhatahir thanks for picking this up 👍

**Comment by talhatahir** [comment]
@RMcNeely can you please have a look at the PR and approve it if its alright.

**Comment by lewisgoddard** [comment]
I definitely think the correct new link is https://docs.elementary.io/hig/design-philosophy

**Comment by RMcNeely** [comment]
I think that is "correct" based on the text but I almost think that we should link directly to the HIG at some point if we're talking about design ideas.

**Comment by lewisgoddard** [comment]
I'm not sure dropping people on the introduction page for the HIG actually adds anything, but either would be fine.
