### ISSUE TITLE
Create an easy setup with docker for those who contribute

### ISSUE THREAD

**Issue by Claudio-code** [elementary/website#3159]
### Problem

The current setup of the project has several barriers for those who want to contribute to the maintenance of the site.
like:
- Have knowledge on how to install specific versions of php and node to avoid breaking the project.
- Install Nginx on the personal machine and other php packages.

### Proposal

My idea is to abstract this complexity in the setup using docker, so that even a windows user could upload the environment and contribute to the community.

**Comment by Claudio-code** [comment]
I made this pull request to add docker, I love this system and I intend to contribute to the community 😊
https://github.com/elementary/website/pull/3160

**Comment by davidmhewitt** [comment]
Resolved in #3160
