### ISSUE TITLE
The team page doesn't show any members

### ISSUE THREAD

**Issue by manojsinghnegiwd** [elementary/website#3178]
### What Happened?

When I visited the team page, the team member section was empty

### Steps to Reproduce

Just go to https://elementary.io/team

### Expected Behavior

There should be a list of team members

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by manojsinghnegiwd** [comment]
@lewisgoddard @danirabbit I would like to fix this.

**Comment by Claudio-code** [comment]
The only problem is that the team page is only for members, more than that to redirect to the people page.

![image](https://github.com/elementary/website/assets/42524939/51cb0986-7393-4836-81bb-e06103ff133d)

**Comment by RMcNeely** [comment]
Closed with #3271
