### ISSUE TITLE
Unable to join slack

### ISSUE THREAD

**Issue by leolost2605** [elementary/website#3220]
### What Happened?

The Slack link doesn't allow joining the community without an elementary.io email address. Is it supposed to be that way or should it maybe rather be an invitation for anyone to join? Or am I missing something else/is Slack still used at all?

### Steps to Reproduce

1. Go to elementary.io
2. In the top right corner click the slack icon
3. Try to sign up without an approved email address

### Expected Behavior

It should allow joining the community with any email address

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
The community link is https://matrix.to/#/%23elementary-l10n%3Amatrix.org

**Comment by danirabbit** [comment]
Unfortunately the Slack link seems to get deactivated all the time. It’s a huge pain. Not sure what to do about it.

this should be a valid link: https://join.slack.com/t/elementarycommunity/shared_invite/zt-1swweakcz-HHb4J_U3GcEz_y0fvigXuA

**Comment by leolost2605** [comment]
Thank you, this link works! Should I leave the issue open as reference for others?

**Comment by akhil888binoy** [comment]
now it works perfectly...I think this issue must be closed

**Comment by aitor-gomila** [comment]
> Unfortunately the Slack link seems to get deactivated all the time. It’s a huge pain. Not sure what to do about it.
> 
> this should be a valid link: https://join.slack.com/t/elementarycommunity/shared_invite/zt-1swweakcz-HHb4J_U3GcEz_y0fvigXuA

What a pain. Maybe we could add a redirect so the link getting thrown out doesn't mean you have to go into the repo, update it, deploy...?

**Comment by Claudio-code** [comment]
I want to enter too but unfortunately the link is not working

**Comment by ryonakano** [comment]
We now recommends Discord instead of Slack for community chatting and the navigation icon in the header of the webpage is replaced to Discord's icon. I think we can now close this issue.
