### ISSUE TITLE
Offer "Download Later" to desktop users, too

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#34]
The download later feature is definitely something essential on mobile devices, but it could be useful to offer to desktop users as well. For example, if someone sees it's 800MB (or whatever) and wouldn't normally download it right then, being able to send them a direct link will encourage them to give us money anyway and get their file later.

![img_20150109_141151](https://cloud.githubusercontent.com/assets/611168/5687415/c1877bea-9809-11e4-92f6-826c21e32240.jpg)

**Comment by cassidyjames** [comment]
Pardon the rough sketch. Kinda squeezed that in there.

**Comment by danrabbit** [comment]
I'm kind of -1 on this feature. I feel like it adds more clutter to the UI than it solves a problem people are actually encountering. I think offering the download now vs sending you a download link should be purely dependent on desktop vs mobile

**Comment by fabianthoma** [comment]
I'm not sure if we are getting the email adress from the payment, but how about just always sending a link and a notice about the payment if you actually do decide to pay?

**Comment by danrabbit** [comment]
Ah Hm that's a good point. If we format it as a receipt with a download link, I'm okay with sending one with every download.

Keep in mind that means like 80k mails a month at our current rate so that implies whatever monthly cost that is.

**Comment by lewisgoddard** [comment]
At 100,000 per month:

### Mailgun
| Amount | Price per Email | Total |
|--|--|--|
| 0 - 10,000 | Free | $0.00 |
| Next 500,000 | $0.00050 | $45.00  |				
| Total |  | **$45.00** |

### Mailgun
| Amount | Price per Email | Total |
|--|--|--|
| First 12,000 | Free | $0.00 |
| Next 88,000 | $0.00020 | $17.60  |				
| Total |  | **$17.60** |

**Comment by lewisgoddard** [comment]
Also, we need to make sure it is clear that this is a receipt, not an invoice.
https://dribbble.com/shots/171786-Receipt
https://dribbble.com/shots/1150131-Receipts

**Comment by charanrajtc** [comment]
For the Design simply we can have a Email Icon along with magnetic link icon will look simple rather having custom UI ! 
For Mailing we can us the postfix (https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-14-04) which is pretty simple for fire and forget e-mails . just needs the server to be configured correctly.

**Comment by lewisgoddard** [comment]
Just using Postfix isn't something I'd be happy with going forward. It is remarkably difficult maintaining a mailservers reputation and once elementary mails start getting marked as spam, it will be a time consuming task to make them stop.

**Comment by charanrajtc** [comment]
Yeah Postfix requires to take care of spams . i guess we should not use it .

**Comment by lewisgoddard** [comment]
ping #1287
