### ISSUE TITLE
Remove Twitter functionality from quotes on bottom of elementary.io

### ISSUE THREAD

**Issue by neelchauhan** [elementary/website#3451]
### What Happened?

When I go to the bottom of **elementary.io** and hover over the quotes, I get an option to tweet a "quote", basically what Ars Technica or Wired said about older versions of elementary, way back before Elon Musk took it over.

### Steps to Reproduce

Hover over a quote on the bottom of the page, you get a Twitter icon and an option to retweet the hovered over quote.

### Expected Behavior

If Elementary has gotten off Twitter, and is endorsing Mastodon instead, doesn't it make sense to remove Twitter functionality when hovering over the quotes?

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by Kissanth** [comment]
anyone working on the issue I can join you

**Comment by Kissanth** [comment]
after the removing the twitter functionality the quotes only showing hover or we are remove or modify them with others in Mastodon?
