### ISSUE TITLE
500 error when attempting to sign into builds.elementary.io using GitHub SSO

### ISSUE THREAD

**Issue by acerspyro** [elementary/website#3537]
### What Happened?

Nuxt crashes due to a 500 error from the backend on the auth/callback route

### Steps to Reproduce

1. Sponsored Elementary on GitHub
2. Went to builds.elementary.io
3. Clicked on "Get Early Access builds"
4. Nuxt 500 error

![image](https://github.com/elementary/website/assets/4400999/7a6aa895-cafd-43a5-b595-2fc50df3fd10)

### Expected Behavior

Get signed in through GitHub

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Firefox 125.0.3 Flatpak on Fedora 40

**Comment by lewisgoddard** [comment]
Looks like a graphql-request update broke logins, I've [reverted the change](https://github.com/elementary/builds/pull/182) and it seems to be working now.

**Comment by acerspyro** [comment]
Works, tysm :)
