### ISSUE TITLE
Legacy warning display on local development

### ISSUE THREAD

**Issue by NickColley** [elementary/website#3601]
The banner that shows when a browser is attempting to visit the site using HTTP shows when developing locally.

https://github.com/elementary/website/blob/master/_templates/legacy.php#L15

I thought maybe this was because the PHPENV variable that's checked for is not set to development here:

https://github.com/elementary/website/blob/master/dev/nginx.conf#L27

But when changing it and restarting things it didnt seem to change to development, might be something I did incorrectly though.

Main impact of this is it makes developing locally a bit annoying seeing the banner show up every refresh...

**Comment by lewisgoddard** [comment]
That is also checking for HTTPS, and showing a warning if the document is loading over HTTP only. We could add a simple bit of localstorage to the javascipt that closes the banner, but I think we could remove that warning entirely. We don't use the public testing branches anymore so there's not much need for it.
