### ISSUE TITLE
Able to bypass paywall

### ISSUE THREAD

**Issue by kiecker223** [elementary/website#3680]
### What Happened?

I was able to bypass what seemed to me a mandatory donation for download for your website

### Steps to Reproduce

1) Go to website
2) Fill out payment info, but most importantly DON'T put anything in the email field
3) Click "pay", the payment will fail since you didn't put in an email
4) Use the back button to go to the previous page from the payment part of the website
5) Download link will appear without any payment being submitted

### Expected Behavior

I assume y'all want to take my money

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by CovertDuck** [comment]
The "Pay What You Can" seems to be ambiguous to many newcomers, leading them to think it is a paid OS.
Heck, it happened to me too!

Perhaps the message could be reworded?

**Comment by danirabbit** [comment]
It’s intentional that you can download without paying. It’s pay-what-you-can and 0 is valid :)
