### ISSUE TITLE
⌘ does not display correctly on Android 4

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/website#462]
⌘ – &amp;#x2318; – &amp;#8984; – the Command Key symbol

https://beta.elementary.io/branch/docs-by-mdr/docs/learning-the-basics

http://tech.karbassi.com/2009/05/27/command-option-shift-symbols-in-unicode/
##

**Comment by emersion** [comment]
It does not display even on Slack and on Github.

**Comment by lewisgoddard** [comment]
This may be something we're just going to have to accept. This is how it is right now. It's an Android problem, not us.

**Comment by KeitIG** [comment]
Well, I wrote a "⌘" in a Readme in of one of my repo, it is displaying correctly on Android.

**Comment by lewisgoddard** [comment]
@KeitIG Can you get the ones here to display correctly? (under workspaces) https://beta.elementary.io/branch/docs-by-mdr/docs/learning-the-basics

Mine definitely do not, and emersion matches. Browser, Browser Version and Android Version please.

**Comment by KeitIG** [comment]
Yes it is displaying correctly (Nexus 5, Android 5.1, Chrome 41)

**Comment by lewisgoddard** [comment]
Ah, I think this might only affect Android 4 then.

**Comment by lewisgoddard** [comment]
Closing as invalid as this isn't our fault, and Android 7 is out now.
