### ISSUE TITLE
New carousel images are not retina/hidpi ready

### ISSUE THREAD

**Issue by aroman** [elementary/website#527]
they look blurry on my HiDPI laptop
##

**Comment by danrabbit** [comment]
I guess this is blocked until elementary OS actually works on HiDPI :p

**Comment by aroman** [comment]
couldn't we just take screenshots from a large resolution setup and then half-scale resize them?

**Comment by danrabbit** [comment]
Well the point of the design is that the screenshots are 1:1. Just scaling them down to 50% size would kind of defeat the purpose imo.

**Comment by cassidyjames** [comment]
Only workaround would be SVG screenshots, rendered out at double-size. But even then it's not an accurate representation of the OS.

**Comment by lewisgoddard** [comment]
This is being partially processed in https://github.com/elementary/mvp/pull/1157

**Comment by lewisgoddard** [comment]
@btkostner Was this entirely fixed in `loki`?

**Comment by danrabbit** [comment]
No there are a couple without HiDPI screenshots. Mainly because the apps themselves may not be 100% HiDPI ready

**Comment by cassidyjames** [comment]
This grab-bag issue is more or less resolved; afaict all the homescreen screenshots are HiDPI, and any new ones in the HIG are as well. If we've missed some, please open specific issues.
