### ISSUE TITLE
Add Mail & Calendar to Carousel

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#561]
### Mail
An advanced native email app, Geary supports multiple accounts, background syncing, and notifications. Plus its numbered dock badge shows you the number of new messages right on the dock. Stay connected and up-to-date outside the browser.

### Calendar
A basic calendaring app to keep track of dates and events. Supports online sync via CalDAV and Google Calendar so you can keep track of your events on the go.

**Comment by lewisgoddard** [comment]
I have this for my Calendar screenshot, but I can't get one for a populated mail.

![calendar](https://cloud.githubusercontent.com/assets/831389/14757790/5fa21f68-08ef-11e6-9a88-763a4b860c4a.png)

**Comment by btkostner** [comment]
Attaching to loki branch #1157
