### ISSUE TITLE
Wrap code in docs

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#583]
What it says on the tin. We should wrap code blocks and also not mess up line numbering.
##

**Comment by cassidyjames** [comment]
Wrap meaning line-wrap?

**Comment by lewisgoddard** [comment]
Line-wrapping is going to make our current numbering system very interesting.

**Comment by lewisgoddard** [comment]
I'm going to mark this down to wishlist because I can only see one instance where this would even have an affect.

**Comment by cassidyjames** [comment]
I'm actually :-1: on this for clarity; we don't want to make developers think they need a newline where they don't, especially if they're hand-re-writing the code instead of copying/pasting to learn.
