### ISSUE TITLE
Update Docs to use Git instead of Bzr

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#625]
Since the eventual goal is to switch third party devs to a GitHub-based workflow, it makes sense (to me) to switch the relevant portion of the docs to git now.

http://blog.launchpad.net/general/git-code-hosting-beta

https://help.launchpad.net/Code/Git#Configuring_Git
##

**Comment by lewisgoddard** [comment]
This is on hold thanks to Launchpads limited support for Git, as I understand it.

**Comment by sudopluto** [comment]
Launchpad has updated git support:
https://kdenlive.org/node/9460
https://help.launchpad.net/Code/Git
