### ISSUE TITLE
Link bug reporting guide from "get involved" page

### ISSUE THREAD

**Issue by nicekiwi** [elementary/website#696]
The bug report guide is current hidden in Developer > Code. Shouldn't it also be next to the link to open bug reports in Desktop development on the Get Involed page?

**Comment by danrabbit** [comment]
Hm I'm actually not sure about this. The button there is more about linking to existing reports as a list of work items. I've begun making sure that we have a link to the guide on various launchpad pages where it says "Bug reporting guidelines".

**Comment by lewisgoddard** [comment]
Maybe a new link is the way to go for this. "How to Report Bugs" > "Report a Bug"

**Comment by lewisgoddard** [comment]
I think `/support` should include a link to "How to Report a Bug"

**Comment by danrabbit** [comment]
I'm very very -1 on putting bug reporting in "Support". Reporting issues is not a form of support. There is no guarantee an issue will be addressed in a timely manner.

**Comment by lewisgoddard** [comment]
Support is still going to be the place people go when they experience a bug though, and we can help them report bugs better.
