### ISSUE TITLE
Migrate popovers to 100% CSS

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#726]
it's super simple, just have to sit down and do it.

**Comment by lewisgoddard** [comment]
I don't think we can do any of the fancy scrollwheel stuff in CSS, but certainly the styling should be do-able with `calc`

**Comment by lewisgoddard** [comment]
The popover script is very small, works well, and I can't seem to perfectly reproduce the positioning without javascript.

**Comment by lewisgoddard** [comment]
I don't think this is reasonable to do given that CSS3 and 3.2 don't include the necessary for scrollwheel magic. Feel free to re-open if you think you can.
