### ISSUE TITLE
Set up a screenshots server [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#901]
in the vein of https://screenshots.debian.net/

We need a screenshots server for the AppCenter app. Ideally this ties into AppHub eventually.
## 

[Bounty on Bountysource](https://www.bountysource.com/issues/27947166-set-up-a-screenshots-server)

**Comment by KeitIG** [comment]
What about d3 ?

**Comment by lewisgoddard** [comment]
Screenshots should be trivially small, I'm not sure we need to outsource them immediately, just make sure they are abstracted.

**Comment by ximion** [comment]
If you#re using AppStream, you pretty much just need to copy the `media/` output directory to some location accessible via HTTP(S) and set the `MediaBaseUrl` in your data accordingly.
This looks like https://appstream.debian.org/media/ on Debian.
For the whole Debian archive (all active suites & sections), this is currently 340MB.

**Comment by KeitIG** [comment]
Ok good to know, but this doesn't seem related to MVP right ? maybe we could create another repo or something ?

**Comment by btkostner** [comment]
You are correct, this should be separated from mvp, as it will most likely grow with more features.

**Comment by KeitIG** [comment]
This is a bit more than a little script to write, we need to choose the techs, the format... (API ?)... We should speak about that on Slack first I guess.

**Comment by charanrajtc** [comment]
I'm interested in working on this part if you guys could share some thing i can start with ?

**Comment by lewisgoddard** [comment]
A $5 digital ocean droplet with a volume attached should work fine for this.

**Comment by danrabbit** [comment]
Probably the more interesting/difficult part is figuring out how AppCenter gets the screenshots and/or how Houston gets those screenshots to this server. Probably would be convenient to discuss API with Corentin in Paris

**Comment by btkostner** [comment]
The developer sets the url links in the appstream file ([reference](https://github.com/vocalapp/vocal/blob/master/data/vocal.desktop.appdata.xml#L26)).  Then when you run appstream-generator it copies the links to a local directory that is used to serve them.  If this is correct then the screenshot server should already basically be setup when we setup the repo server. I am not 100% sure what I just said was accurate, as I have yet to test anything on it.

**Comment by ximion** [comment]
@btkostner is correct ;-)
asgen will download and resize the screenshots and then publish them in some user-defined location and set a user-defined link in the resulting collection AppStream metadata.

(so, you will get a bunch of image files in a defined directory structure which you can place on any server you want - you just need to tell asgen where they will be reachable from the web)

**Comment by danrabbit** [comment]
Yeah we want to bypass that because:
1. There's no validation. Most AppStream screenshots suck really bad and are of the apps on some other platform. If we have a web interface we can at least verify that they are a sane size and/or make screenshot checking part of the review process.
2. It's kind of complicated. Developers still have to 'host' the screenshots somewhere for us to copy them from.

**Comment by lewisgoddard** [comment]
So really this is an [elementary/infrastructure](https://github.com/elementary/infrastructure) issue for the server and an [elementary/houston](https://github.com/elementary/houston) issue for the front-end.

**Comment by ximion** [comment]
@danrabbit Well, the whole point of having screenshots in AppStream was to give upstream projects contol over them, and not users - because the screenshots on services like screenshots.debian.org sucked really bad for many applications.

But you obviously can replace any screenshots you want - at some point in future asgen will grow some screenshot override logic anyway, because we want this in Debian (so we can veto upstream-provided screenshots that may contain copyrighted material).

**Comment by danrabbit** [comment]
@ximion Yeah I just want to make sure we (as the distributor) have the final say so we can, like you said, veto upstream screenshots that might contain copyrighted content or just be of low quality

**Comment by btkostner** [comment]
Houston still needs to validate the app before it makes it to the main repo, so it doesn't bypass the validation step. We just need to add an image viewer step validation thing.

I was thinking about this a bit some time ago. One solution I got was hosting the images in git, with the code. Then redirecting the urls in appstream code to a `raw.github` proxy (probably hosted with houston) to fetch the images. This has the advantage of being easy for the developer. Bad thing being is that we would probably have to break appstream spec and use absolute paths in the appdata file.

**Comment by lewisgoddard** [comment]
It is not recommended to serve anything from raw.github, it purposefully doesn't return correct content type. You want us to proxy them rather than store them? With some caching, what's the difference?

**Comment by danrabbit** [comment]
@btkostner Yeah just including them in the git repo would probably be easy. I still think it would be nice to get immediate feedback and a bit of hand-holding though. Otherwise you have to go through the submission process to find out your screenshots are too small or a weird aspect ratio and submit a new version of your app just to fix it

**Comment by btkostner** [comment]
The proxy is to fix the `content-type` header for asgen. Past that everything would continue as it normally would with asgen grabbing the file.

**Comment by ximion** [comment]
@btkostner I don't see any reason why this would require any black magic in AppStream.
Only the generator would need to special-case Github URLs, but we can do that with less effort - patches welcome ;-)

**Comment by btkostner** [comment]
@ximion I was going to have houston rewrite the urls when it clones the code and builds it.

I'll keep you posted when I start working on the asgen screenshots to make sure we can get this done the best way possible.
