### ISSUE TITLE
Change repository name and description

### ISSUE THREAD

**Issue by KeitIG** [elementary/website#993]
They are not clear enough and a lot of people thinks this is the distribution repository whereas it's on Launchpad.

A few ideas:

Repo name: `elementary.io` ?
Description: `elementary.io sources (website only)` ?
something in README.md would be great too

**Comment by aleksandar-todorovic** [comment]
Honestly, I feel like nothing would change even if the switch was made.

**Comment by lewisgoddard** [comment]
We have been discussing moving this repo to "io" or "website", but I am concerned about link breakage, especially with our amount of automation, but I agree that that change is cosmetic and won't fix it. I think the main issue is #679 "/get-involved is ordered strangely."

**Comment by danrabbit** [comment]
I've noticed the button labels are "Fork us on GitHub" and "see our open bug reports" respectively. Perhaps the context is indeed not clear enough. Changing those button labels to explicitly mention the website could be helpful. Maybe to:

"Fork Our Website on GitHub"
"Report an Issue with Our Website"

**Comment by cassidyjames** [comment]
@lewisgoddard I do believe that the repo name is confusing and should be fixed, as I mentioned in #995. GitHub will set up indefinite redirects unless/until we create a new mvp project. But yes, we would need to coordinate a switch over.

**Comment by KeitIG** [comment]
We could, for later use, use a fixed url like `http://elementary.io/sources/website` and redirect it to the url we want.

**Comment by cassidyjames** [comment]
@KeitIG eh, that just shifts the issue elsewhere and complicates things. :) I think I prefer just coordinating with @fabianthoma and anyone else involved to get it all migrated quickly after updating the repo name.

**Comment by fabianthoma** [comment]
@cassidyjames I see no big issues here, but we have to move the automation in jenkins and some other stuff, so it should probably be me doing this

**Comment by fabianthoma** [comment]
What is the proposed new repo name here, do we just go with `website`, or `elementary.io` or something compleatly different?

**Comment by lewisgoddard** [comment]
@DanRabbit wanted us to be cool and use `io`.

**Comment by danrabbit** [comment]
Io would be really clever, but website might be more obvious

**Comment by btkostner** [comment]
What is the proposed new repo name here, do we just go with `website`, or `io`?

**Comment by lewisgoddard** [comment]
`website` seems to be the most suggested as a sensible option, `io` is cool but mysterious. @fabianthoma thinks descriptive is better.
