### ISSUE TITLE
Create customers with Stripe

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#998]
Stripe lets you create a customer as well as a transaction when someone is checking out. If possible, we should be creating a customer or potentially bypassing the payment if it is a return Stripe customer.

**Comment by charanrajtc** [comment]
This feature is for purchase OS checkout or shopping cart

**Comment by cassidyjames** [comment]
Purchasing the OS.

**Comment by charanrajtc** [comment]
ok i will be working on it !

**Comment by charanrajtc** [comment]
After going though your code we i can see that we can potentially bypassing the payment without creating the customers in the stripe using cookies ,are particularly looking forward to to creating customer account in Stripe ?

**Comment by cassidyjames** [comment]
Yes, we bypass payments with a cookie for now. However, we'd like to create a customer as well because it makes managing things like refunds and previous purchases much easier for us on the Stripe backend.
